/**
 * Static localized country names for all 9 supported UI languages.
 * Derived from the frontend COMPASS_REGIONS array (active-region.tsx).
 *
 * Used by the /api/culture/compass and /api/cultures endpoints to
 * return localized region_name even when compass_regions.content only
 * has an en-GB entry (which is the case for ~188 of the 206 published
 * countries).
 *
 * Lookup: REGION_NAMES[regionCode][lang] — lang is a base language code
 * (en | nl | fr | de | es | pt | it | ar | ja | zh).
 */
export const REGION_NAMES: Record<string, Record<string, string>> = {
  GB: { en: "United Kingdom", nl: "Verenigd Koninkrijk", fr: "Royaume-Uni", de: "Vereinigtes Königreich", es: "Reino Unido", pt: "Reino Unido", it: "Regno Unito", ar: "المملكة المتحدة", ja: "英国", zh: "英国" },
  US: { en: "United States", nl: "Verenigde Staten", fr: "États-Unis", de: "Vereinigte Staaten", es: "Estados Unidos", pt: "Estados Unidos", it: "Stati Uniti", ar: "الولايات المتحدة", ja: "アメリカ合衆国", zh: "美国" },
  AE: { en: "UAE / Dubai", nl: "VAE / Dubai", fr: "Émirats Arabes", de: "VAE / Dubai", es: "EAU / Dubái", pt: "EAU / Dubai", it: "EAU / Dubai", ar: "الإمارات / دبي", ja: "UAE / ドバイ", zh: "阿联酋 / 迪拜" },
  CN: { en: "China", nl: "China", fr: "Chine", de: "China", es: "China", pt: "China", it: "Cina", ar: "الصين", ja: "中国", zh: "中国" },
  JP: { en: "Japan", nl: "Japan", fr: "Japon", de: "Japan", es: "Japón", pt: "Japão", it: "Giappone", ar: "اليابان", ja: "日本", zh: "日本" },
  FR: { en: "France", nl: "Frankrijk", fr: "France", de: "Frankreich", es: "Francia", pt: "França", it: "Francia", ar: "فرنسا", ja: "フランス", zh: "法国" },
  DE: { en: "Germany", nl: "Duitsland", fr: "Allemagne", de: "Deutschland", es: "Alemania", pt: "Alemanha", it: "Germania", ar: "ألمانيا", ja: "ドイツ", zh: "德国" },
  NL: { en: "Netherlands", nl: "Nederland", fr: "Pays-Bas", de: "Niederlande", es: "Países Bajos", pt: "Países Baixos", it: "Paesi Bassi", ar: "هولندا", ja: "オランダ", zh: "荷兰" },
  AU: { en: "Australia", nl: "Australië", fr: "Australie", de: "Australien", es: "Australia", pt: "Austrália", it: "Australia", ar: "أستراليا", ja: "オーストラリア", zh: "澳大利亚" },
  CA: { en: "Canada", nl: "Canada", fr: "Canada", de: "Kanada", es: "Canadá", pt: "Canadá", it: "Canada", ar: "كندا", ja: "カナダ", zh: "加拿大" },
  IT: { en: "Italy", nl: "Italië", fr: "Italie", de: "Italien", es: "Italia", pt: "Itália", it: "Italia", ar: "إيطاليا", ja: "イタリア", zh: "意大利" },
  IN: { en: "India", nl: "India", fr: "Inde", de: "Indien", es: "India", pt: "Índia", it: "India", ar: "الهند", ja: "インド", zh: "印度" },
  ES: { en: "Spain", nl: "Spanje", fr: "Espagne", de: "Spanien", es: "España", pt: "Espanha", it: "Spagna", ar: "إسبانيا", ja: "スペイン", zh: "西班牙" },
  PT: { en: "Portugal", nl: "Portugal", fr: "Portugal", de: "Portugal", es: "Portugal", pt: "Portugal", it: "Portogallo", ar: "البرتغال", ja: "ポルトガル", zh: "葡萄牙" },
  SG: { en: "Singapore", nl: "Singapore", fr: "Singapour", de: "Singapur", es: "Singapur", pt: "Singapura", it: "Singapore", ar: "سنغافورة", ja: "シンガポール", zh: "新加坡" },
  BR: { en: "Brazil", nl: "Brazilië", fr: "Brésil", de: "Brasilien", es: "Brasil", pt: "Brasil", it: "Brasile", ar: "البرازيل", ja: "ブラジル", zh: "巴西" },
  ZA: { en: "South Africa", nl: "Zuid-Afrika", fr: "Afrique du Sud", de: "Südafrika", es: "Sudáfrica", pt: "África do Sul", it: "Sudafrica", ar: "جنوب أفريقيا", ja: "南アフリカ", zh: "南非" },
  MX: { en: "Mexico", nl: "Mexico", fr: "Mexique", de: "Mexiko", es: "México", pt: "México", it: "Messico", ar: "المكسيك", ja: "メキシコ", zh: "墨西哥" },
  CO: { en: "Colombia", nl: "Colombia", fr: "Colombie", de: "Kolumbien", es: "Colombia", pt: "Colômbia", it: "Colombia", ar: "كولومبيا", ja: "コロンビア", zh: "哥伦比亚" },
  BE: { en: "Belgium", nl: "België", fr: "Belgique", de: "Belgien", es: "Bélgica", pt: "Bélgica", it: "Belgio", ar: "بلجيكا", ja: "ベルギー", zh: "比利时" },
  CH: { en: "Switzerland", nl: "Zwitserland", fr: "Suisse", de: "Schweiz", es: "Suiza", pt: "Suíça", it: "Svizzera", ar: "سويسرا", ja: "スイス", zh: "瑞士" },
  AF: { en: "Afghanistan", nl: "Afghanistan", fr: "Afghanistan", de: "Afghanistan", es: "Afganistán", pt: "Afeganistão", it: "Afghanistan", ar: "أفغانستان", ja: "アフガニスタン", zh: "阿富汗" },
  AL: { en: "Albania", nl: "Albanië", fr: "Albanie", de: "Albanien", es: "Albania", pt: "Albânia", it: "Albania", ar: "ألبانيا", ja: "アルバニア", zh: "阿尔巴尼亚" },
  DZ: { en: "Algeria", nl: "Algerije", fr: "Algérie", de: "Algerien", es: "Argelia", pt: "Argélia", it: "Algeria", ar: "الجزائر", ja: "アルジェリア", zh: "阿尔及利亚" },
  AD: { en: "Andorra", nl: "Andorra", fr: "Andorre", de: "Andorra", es: "Andorra", pt: "Andorra", it: "Andorra", ar: "أندورا", ja: "アンドラ", zh: "安道尔" },
  AO: { en: "Angola", nl: "Angola", fr: "Angola", de: "Angola", es: "Angola", pt: "Angola", it: "Angola", ar: "أنغولا", ja: "アンゴラ", zh: "安哥拉" },
  AG: { en: "Antigua and Barbuda", nl: "Antigua en Barbuda", fr: "Antigua-et-Barbuda", de: "Antigua und Barbuda", es: "Antigua y Barbuda", pt: "Antígua e Barbuda", it: "Antigua e Barbuda", ar: "أنتيغوا وبربودا", ja: "アンティグア・バーブーダ", zh: "安提瓜和巴布达" },
  AR: { en: "Argentina", nl: "Argentinië", fr: "Argentine", de: "Argentinien", es: "Argentina", pt: "Argentina", it: "Argentina", ar: "الأرجنتين", ja: "アルゼンチン", zh: "阿根廷" },
  AW: { en: "Aruba", nl: "Aruba", fr: "Aruba", de: "Aruba", es: "Aruba", pt: "Aruba", it: "Aruba", ar: "أروبا", ja: "アルバ", zh: "阿鲁巴" },
  AT: { en: "Austria", nl: "Oostenrijk", fr: "Autriche", de: "Österreich", es: "Austria", pt: "Áustria", it: "Austria", ar: "النمسا", ja: "オーストリア", zh: "奥地利" },
  BS: { en: "Bahamas", nl: "Bahamas", fr: "Bahamas", de: "Bahamas", es: "Bahamas", pt: "Bahamas", it: "Bahamas", ar: "باهاماس", ja: "バハマ", zh: "巴哈马" },
  BH: { en: "Bahrain", nl: "Bahrein", fr: "Bahreïn", de: "Bahrain", es: "Baréin", pt: "Barém", it: "Bahrein", ar: "البحرين", ja: "バーレーン", zh: "巴林" },
  BD: { en: "Bangladesh", nl: "Bangladesh", fr: "Bangladesh", de: "Bangladesch", es: "Bangladés", pt: "Bangladesh", it: "Bangladesh", ar: "بنغلاديش", ja: "バングラデシュ", zh: "孟加拉国" },
  BB: { en: "Barbados", nl: "Barbados", fr: "Barbade", de: "Barbados", es: "Barbados", pt: "Barbados", it: "Barbados", ar: "بربادوس", ja: "バルバドス", zh: "巴巴多斯" },
  BY: { en: "Belarus", nl: "Wit-Rusland", fr: "Biélorussie", de: "Weißrussland", es: "Bielorrusia", pt: "Bielorrússia", it: "Bielorussia", ar: "بيلاروس", ja: "ベラルーシ", zh: "白俄罗斯" },
  BZ: { en: "Belize", nl: "Belize", fr: "Belize", de: "Belize", es: "Belice", pt: "Belize", it: "Belize", ar: "بليز", ja: "ベリーズ", zh: "伯利兹" },
  BJ: { en: "Benin", nl: "Benin", fr: "Bénin", de: "Benin", es: "Benín", pt: "Benin", it: "Benin", ar: "بنين", ja: "ベナン", zh: "贝宁" },
  BM: { en: "Bermuda", nl: "Bermuda", fr: "Bermudes", de: "Bermuda", es: "Bermudas", pt: "Bermuda", it: "Bermuda", ar: "برمودا", ja: "バミューダ", zh: "百慕大" },
  BT: { en: "Bhutan", nl: "Bhutan", fr: "Bhoutan", de: "Bhutan", es: "Bután", pt: "Butão", it: "Bhutan", ar: "بوتان", ja: "ブータン", zh: "不丹" },
  BO: { en: "Bolivia", nl: "Bolivia", fr: "Bolivie", de: "Bolivien", es: "Bolivia", pt: "Bolívia", it: "Bolivia", ar: "بوليفيا", ja: "ボリビア", zh: "玻利维亚" },
  BA: { en: "Bosnia and Herzegovina", nl: "Bosnië-Herzegovina", fr: "Bosnie-Herzégovine", de: "Bosnien und Herzegowina", es: "Bosnia y Herzegovina", pt: "Bósnia e Herzegovina", it: "Bosnia ed Erzegovina", ar: "البوسنة والهرسك", ja: "ボスニア・ヘルツェゴビナ", zh: "波斯尼亚和黑塞哥维那" },
  BW: { en: "Botswana", nl: "Botswana", fr: "Botswana", de: "Botswana", es: "Botsuana", pt: "Botswana", it: "Botswana", ar: "بوتسوانا", ja: "ボツワナ", zh: "博茨瓦纳" },
  BN: { en: "Brunei", nl: "Brunei", fr: "Brunei", de: "Brunei", es: "Brunéi", pt: "Brunei", it: "Brunei", ar: "بروناي", ja: "ブルネイ", zh: "文莱" },
  BG: { en: "Bulgaria", nl: "Bulgarije", fr: "Bulgarie", de: "Bulgarien", es: "Bulgaria", pt: "Bulgária", it: "Bulgaria", ar: "بلغاريا", ja: "ブルガリア", zh: "保加利亚" },
  BF: { en: "Burkina Faso", nl: "Burkina Faso", fr: "Burkina Faso", de: "Burkina Faso", es: "Burkina Faso", pt: "Burkina Faso", it: "Burkina Faso", ar: "بوركينا فاسو", ja: "ブルキナファソ", zh: "布基纳法索" },
  BI: { en: "Burundi", nl: "Burundi", fr: "Burundi", de: "Burundi", es: "Burundi", pt: "Burundi", it: "Burundi", ar: "بوروندي", ja: "ブルンジ", zh: "布隆迪" },
  KH: { en: "Cambodia", nl: "Cambodja", fr: "Cambodge", de: "Kambodscha", es: "Camboya", pt: "Camboja", it: "Cambogia", ar: "كمبوديا", ja: "カンボジア", zh: "柬埔寨" },
  CM: { en: "Cameroon", nl: "Kameroen", fr: "Cameroun", de: "Kamerun", es: "Camerún", pt: "Camarões", it: "Camerun", ar: "الكاميرون", ja: "カメルーン", zh: "喀麦隆" },
  CV: { en: "Cape Verde", nl: "Kaapverdië", fr: "Cap-Vert", de: "Cabo Verde", es: "Cabo Verde", pt: "Cabo Verde", it: "Capo Verde", ar: "الرأس الأخضر", ja: "カーボベルデ", zh: "佛得角" },
  KY: { en: "Cayman Islands", nl: "Caymaneilanden", fr: "Îles Caïmans", de: "Kaimaninseln", es: "Islas Caimán", pt: "Ilhas Cayman", it: "Isole Cayman", ar: "جزر كايمان", ja: "ケイマン諸島", zh: "开曼群岛" },
  CF: { en: "Central African Republic", nl: "Centraal-Afrikaanse Republiek", fr: "République centrafricaine", de: "Zentralafrikanische Republik", es: "República Centroafricana", pt: "República Centro-Africana", it: "Repubblica Centrafricana", ar: "جمهورية أفريقيا الوسطى", ja: "中央アフリカ共和国", zh: "中非共和国" },
  TD: { en: "Chad", nl: "Tsjaad", fr: "Tchad", de: "Tschad", es: "Chad", pt: "Chade", it: "Ciad", ar: "تشاد", ja: "チャド", zh: "乍得" },
  CL: { en: "Chile", nl: "Chili", fr: "Chili", de: "Chile", es: "Chile", pt: "Chile", it: "Cile", ar: "تشيلي", ja: "チリ", zh: "智利" },
  KM: { en: "Comoros", nl: "Comoren", fr: "Comores", de: "Komoren", es: "Comoras", pt: "Comores", it: "Comore", ar: "جزر القمر", ja: "コモロ", zh: "科摩罗" },
  CK: { en: "Cook Islands", nl: "Cookeilanden", fr: "Îles Cook", de: "Cookinseln", es: "Islas Cook", pt: "Ilhas Cook", it: "Isole Cook", ar: "جزر كوك", ja: "クック諸島", zh: "库克群岛" },
  CR: { en: "Costa Rica", nl: "Costa Rica", fr: "Costa Rica", de: "Costa Rica", es: "Costa Rica", pt: "Costa Rica", it: "Costa Rica", ar: "كوستاريكا", ja: "コスタリカ", zh: "哥斯达黎加" },
  CI: { en: "Côte d'Ivoire", nl: "Ivoorkust", fr: "Côte d'Ivoire", de: "Elfenbeinküste", es: "Costa de Marfil", pt: "Costa do Marfim", it: "Costa d'Avorio", ar: "ساحل العاج", ja: "コートジボワール", zh: "科特迪瓦" },
  HR: { en: "Croatia", nl: "Kroatië", fr: "Croatie", de: "Kroatien", es: "Croacia", pt: "Croácia", it: "Croazia", ar: "كرواتيا", ja: "クロアチア", zh: "克罗地亚" },
  CU: { en: "Cuba", nl: "Cuba", fr: "Cuba", de: "Kuba", es: "Cuba", pt: "Cuba", it: "Cuba", ar: "كوبا", ja: "キューバ", zh: "古巴" },
  CW: { en: "Curaçao", nl: "Curaçao", fr: "Curaçao", de: "Curaçao", es: "Curazao", pt: "Curaçao", it: "Curaçao", ar: "كوراساو", ja: "キュラソー", zh: "库拉索" },
  CY: { en: "Cyprus", nl: "Cyprus", fr: "Chypre", de: "Zypern", es: "Chipre", pt: "Chipre", it: "Cipro", ar: "قبرص", ja: "キプロス", zh: "塞浦路斯" },
  CZ: { en: "Czech Republic", nl: "Tsjechië", fr: "République tchèque", de: "Tschechien", es: "República Checa", pt: "República Checa", it: "Repubblica Ceca", ar: "جمهورية التشيك", ja: "チェコ", zh: "捷克" },
  CD: { en: "DR Congo", nl: "DR Congo", fr: "RD du Congo", de: "DR Kongo", es: "RD del Congo", pt: "RD do Congo", it: "RD del Congo", ar: "جمهورية الكونغو الديمقراطية", ja: "コンゴ民主共和国", zh: "刚果民主共和国" },
  DK: { en: "Denmark", nl: "Denemarken", fr: "Danemark", de: "Dänemark", es: "Dinamarca", pt: "Dinamarca", it: "Danimarca", ar: "الدنمارك", ja: "デンマーク", zh: "丹麦" },
  DJ: { en: "Djibouti", nl: "Djibouti", fr: "Djibouti", de: "Dschibuti", es: "Yibuti", pt: "Djibuti", it: "Gibuti", ar: "جيبوتي", ja: "ジブチ", zh: "吉布提" },
  DM: { en: "Dominica", nl: "Dominica", fr: "Dominique", de: "Dominica", es: "Dominica", pt: "Dominica", it: "Dominica", ar: "دومينيكا", ja: "ドミニカ国", zh: "多米尼克" },
  DO: { en: "Dominican Republic", nl: "Dominicaanse Republiek", fr: "République dominicaine", de: "Dominikanische Republik", es: "República Dominicana", pt: "República Dominicana", it: "Repubblica Dominicana", ar: "جمهورية الدومينيكان", ja: "ドミニカ共和国", zh: "多明尼加共和国" },
  EC: { en: "Ecuador", nl: "Ecuador", fr: "Équateur", de: "Ecuador", es: "Ecuador", pt: "Equador", it: "Ecuador", ar: "الإكوادور", ja: "エクアドル", zh: "厄瓜多尔" },
  EG: { en: "Egypt", nl: "Egypte", fr: "Égypte", de: "Ägypten", es: "Egipto", pt: "Egito", it: "Egitto", ar: "مصر", ja: "エジプト", zh: "埃及" },
  SV: { en: "El Salvador", nl: "El Salvador", fr: "El Salvador", de: "El Salvador", es: "El Salvador", pt: "El Salvador", it: "El Salvador", ar: "السلفادور", ja: "エルサルバドル", zh: "萨尔瓦多" },
  GQ: { en: "Equatorial Guinea", nl: "Equatoriaal-Guinea", fr: "Guinée équatoriale", de: "Äquatorialguinea", es: "Guinea Ecuatorial", pt: "Guiné Equatorial", it: "Guinea Equatoriale", ar: "غينيا الاستوائية", ja: "赤道ギニア", zh: "赤道几内亚" },
  ER: { en: "Eritrea", nl: "Eritrea", fr: "Érythrée", de: "Eritrea", es: "Eritrea", pt: "Eritreia", it: "Eritrea", ar: "إريتريا", ja: "エリトリア", zh: "厄立特里亚" },
  EE: { en: "Estonia", nl: "Estland", fr: "Estonie", de: "Estland", es: "Estonia", pt: "Estónia", it: "Estonia", ar: "إستونيا", ja: "エストニア", zh: "爱沙尼亚" },
  SZ: { en: "Eswatini", nl: "Eswatini", fr: "Eswatini", de: "Eswatini", es: "Esuatini", pt: "Essuatíni", it: "Eswatini", ar: "إسواتيني", ja: "エスワティニ", zh: "斯威士兰" },
  ET: { en: "Ethiopia", nl: "Ethiopië", fr: "Éthiopie", de: "Äthiopien", es: "Etiopía", pt: "Etiópia", it: "Etiopia", ar: "إثيوبيا", ja: "エチオピア", zh: "埃塞俄比亚" },
  FO: { en: "Faroe Islands", nl: "Faeröer", fr: "Îles Féroé", de: "Färöer", es: "Islas Feroe", pt: "Ilhas Faroé", it: "Isole Faroe", ar: "جزر فارو", ja: "フェロー諸島", zh: "法罗群岛" },
  FM: { en: "Micronesia", nl: "Micronesië", fr: "Micronésie", de: "Mikronesien", es: "Micronesia", pt: "Micronésia", it: "Micronesia", ar: "ميكرونيزيا", ja: "ミクロネシア", zh: "密克罗尼西亚" },
  FJ: { en: "Fiji", nl: "Fiji", fr: "Fidji", de: "Fidschi", es: "Fiyi", pt: "Fiji", it: "Figi", ar: "فيجي", ja: "フィジー", zh: "斐济" },
  FI: { en: "Finland", nl: "Finland", fr: "Finlande", de: "Finnland", es: "Finlandia", pt: "Finlândia", it: "Finlandia", ar: "فنلندا", ja: "フィンランド", zh: "芬兰" },
  PF: { en: "French Polynesia", nl: "Frans-Polynesië", fr: "Polynésie française", de: "Französisch-Polynesien", es: "Polinesia Francesa", pt: "Polinésia Francesa", it: "Polinesia Francese", ar: "بولينيزيا الفرنسية", ja: "フランス領ポリネシア", zh: "法属波利尼西亚" },
  GA: { en: "Gabon", nl: "Gabon", fr: "Gabon", de: "Gabun", es: "Gabón", pt: "Gabão", it: "Gabon", ar: "الغابون", ja: "ガボン", zh: "加蓬" },
  GM: { en: "Gambia", nl: "Gambia", fr: "Gambie", de: "Gambia", es: "Gambia", pt: "Gâmbia", it: "Gambia", ar: "غامبيا", ja: "ガンビア", zh: "冈比亚" },
  GH: { en: "Ghana", nl: "Ghana", fr: "Ghana", de: "Ghana", es: "Ghana", pt: "Gana", it: "Ghana", ar: "غانا", ja: "ガーナ", zh: "加纳" },
  GR: { en: "Greece", nl: "Griekenland", fr: "Grèce", de: "Griechenland", es: "Grecia", pt: "Grécia", it: "Grecia", ar: "اليونان", ja: "ギリシャ", zh: "希腊" },
  GL: { en: "Greenland", nl: "Groenland", fr: "Groenland", de: "Grönland", es: "Groenlandia", pt: "Gronelândia", it: "Groenlandia", ar: "غرينلاند", ja: "グリーンランド", zh: "格陵兰" },
  GD: { en: "Grenada", nl: "Grenada", fr: "Grenade", de: "Grenada", es: "Granada", pt: "Granada", it: "Grenada", ar: "غرينادا", ja: "グレナダ", zh: "格林纳达" },
  GT: { en: "Guatemala", nl: "Guatemala", fr: "Guatemala", de: "Guatemala", es: "Guatemala", pt: "Guatemala", it: "Guatemala", ar: "غواتيمالا", ja: "グアテマラ", zh: "危地马拉" },
  GN: { en: "Guinea", nl: "Guinee", fr: "Guinée", de: "Guinea", es: "Guinea", pt: "Guiné", it: "Guinea", ar: "غينيا", ja: "ギニア", zh: "几内亚" },
  GW: { en: "Guinea-Bissau", nl: "Guinee-Bissau", fr: "Guinée-Bissau", de: "Guinea-Bissau", es: "Guinea-Bisáu", pt: "Guiné-Bissau", it: "Guinea-Bissau", ar: "غينيا بيساو", ja: "ギニアビサウ", zh: "几内亚比绍" },
  GY: { en: "Guyana", nl: "Guyana", fr: "Guyana", de: "Guyana", es: "Guyana", pt: "Guiana", it: "Guyana", ar: "غيانا", ja: "ガイアナ", zh: "圭亚那" },
  HT: { en: "Haiti", nl: "Haïti", fr: "Haïti", de: "Haiti", es: "Haití", pt: "Haiti", it: "Haiti", ar: "هايتي", ja: "ハイチ", zh: "海地" },
  HN: { en: "Honduras", nl: "Honduras", fr: "Honduras", de: "Honduras", es: "Honduras", pt: "Honduras", it: "Honduras", ar: "هندوراس", ja: "ホンジュラス", zh: "洪都拉斯" },
  HK: { en: "Hong Kong", nl: "Hongkong", fr: "Hong Kong", de: "Hongkong", es: "Hong Kong", pt: "Hong Kong", it: "Hong Kong", ar: "هونج كونج", ja: "香港", zh: "香港" },
  HU: { en: "Hungary", nl: "Hongarije", fr: "Hongrie", de: "Ungarn", es: "Hungría", pt: "Hungria", it: "Ungheria", ar: "المجر", ja: "ハンガリー", zh: "匈牙利" },
  IS: { en: "Iceland", nl: "IJsland", fr: "Islande", de: "Island", es: "Islandia", pt: "Islândia", it: "Islanda", ar: "آيسلندا", ja: "アイスランド", zh: "冰岛" },
  ID: { en: "Indonesia", nl: "Indonesië", fr: "Indonésie", de: "Indonesien", es: "Indonesia", pt: "Indonésia", it: "Indonesia", ar: "إندونيسيا", ja: "インドネシア", zh: "印度尼西亚" },
  IR: { en: "Iran", nl: "Iran", fr: "Iran", de: "Iran", es: "Irán", pt: "Irã", it: "Iran", ar: "إيران", ja: "イラン", zh: "伊朗" },
  IQ: { en: "Iraq", nl: "Irak", fr: "Irak", de: "Irak", es: "Irak", pt: "Iraque", it: "Iraq", ar: "العراق", ja: "イラク", zh: "伊拉克" },
  IE: { en: "Ireland", nl: "Ierland", fr: "Irlande", de: "Irland", es: "Irlanda", pt: "Irlanda", it: "Irlanda", ar: "أيرلندا", ja: "アイルランド", zh: "爱尔兰" },
  IL: { en: "Israel", nl: "Israël", fr: "Israël", de: "Israel", es: "Israel", pt: "Israel", it: "Israele", ar: "إسرائيل", ja: "イスラエル", zh: "以色列" },
  JM: { en: "Jamaica", nl: "Jamaica", fr: "Jamaïque", de: "Jamaika", es: "Jamaica", pt: "Jamaica", it: "Giamaica", ar: "جامايكا", ja: "ジャマイカ", zh: "牙买加" },
  JO: { en: "Jordan", nl: "Jordanië", fr: "Jordanie", de: "Jordanien", es: "Jordania", pt: "Jordânia", it: "Giordania", ar: "الأردن", ja: "ヨルダン", zh: "约旦" },
  KZ: { en: "Kazakhstan", nl: "Kazachstan", fr: "Kazakhstan", de: "Kasachstan", es: "Kazajistán", pt: "Cazaquistão", it: "Kazakistan", ar: "كازاخستان", ja: "カザフスタン", zh: "哈萨克斯坦" },
  KE: { en: "Kenya", nl: "Kenia", fr: "Kenya", de: "Kenia", es: "Kenia", pt: "Quénia", it: "Kenya", ar: "كينيا", ja: "ケニア", zh: "肯尼亚" },
  KI: { en: "Kiribati", nl: "Kiribati", fr: "Kiribati", de: "Kiribati", es: "Kiribati", pt: "Kiribati", it: "Kiribati", ar: "كيريباتي", ja: "キリバス", zh: "基里巴斯" },
  XK: { en: "Kosovo", nl: "Kosovo", fr: "Kosovo", de: "Kosovo", es: "Kosovo", pt: "Kosovo", it: "Kosovo", ar: "كوسوفو", ja: "コソボ", zh: "科索沃" },
  KW: { en: "Kuwait", nl: "Koeweit", fr: "Koweït", de: "Kuwait", es: "Kuwait", pt: "Kuwait", it: "Kuwait", ar: "الكويت", ja: "クウェート", zh: "科威特" },
  KG: { en: "Kyrgyzstan", nl: "Kirgizstan", fr: "Kirghizistan", de: "Kirgisistan", es: "Kirguistán", pt: "Quirguistão", it: "Kirghizistan", ar: "قيرغيزستان", ja: "キルギスタン", zh: "吉尔吉斯斯坦" },
  LA: { en: "Laos", nl: "Laos", fr: "Laos", de: "Laos", es: "Laos", pt: "Laos", it: "Laos", ar: "لاوس", ja: "ラオス", zh: "老挝" },
  LV: { en: "Latvia", nl: "Letland", fr: "Lettonie", de: "Lettland", es: "Letonia", pt: "Letônia", it: "Lettonia", ar: "لاتفيا", ja: "ラトビア", zh: "拉脱维亚" },
  LB: { en: "Lebanon", nl: "Libanon", fr: "Liban", de: "Libanon", es: "Líbano", pt: "Líbano", it: "Libano", ar: "لبنان", ja: "レバノン", zh: "黎巴嫩" },
  LS: { en: "Lesotho", nl: "Lesotho", fr: "Lesotho", de: "Lesotho", es: "Lesoto", pt: "Lesoto", it: "Lesotho", ar: "ليسوتو", ja: "レソト", zh: "莱索托" },
  LR: { en: "Liberia", nl: "Liberia", fr: "Liberia", de: "Liberia", es: "Liberia", pt: "Libéria", it: "Liberia", ar: "ليبيريا", ja: "リベリア", zh: "利比里亚" },
  LY: { en: "Libya", nl: "Libië", fr: "Libye", de: "Libyen", es: "Libia", pt: "Líbia", it: "Libia", ar: "ليبيا", ja: "リビア", zh: "利比亚" },
  LI: { en: "Liechtenstein", nl: "Liechtenstein", fr: "Liechtenstein", de: "Liechtenstein", es: "Liechtenstein", pt: "Liechtenstein", it: "Liechtenstein", ar: "ليختنشتاين", ja: "リヒテンシュタイン", zh: "列支敦士登" },
  LT: { en: "Lithuania", nl: "Litouwen", fr: "Lituanie", de: "Litauen", es: "Lituania", pt: "Lituânia", it: "Lituania", ar: "ليتوانيا", ja: "リトアニア", zh: "立陶宛" },
  LU: { en: "Luxembourg", nl: "Luxemburg", fr: "Luxembourg", de: "Luxemburg", es: "Luxemburgo", pt: "Luxemburgo", it: "Lussemburgo", ar: "لوكسمبورغ", ja: "ルクセンブルク", zh: "卢森堡" },
  MO: { en: "Macau", nl: "Macau", fr: "Macao", de: "Macau", es: "Macao", pt: "Macau", it: "Macau", ar: "ماكاو", ja: "マカオ", zh: "澳门" },
  MG: { en: "Madagascar", nl: "Madagaskar", fr: "Madagascar", de: "Madagaskar", es: "Madagascar", pt: "Madagáscar", it: "Madagascar", ar: "مدغشقر", ja: "マダガスカル", zh: "马达加斯加" },
  MW: { en: "Malawi", nl: "Malawi", fr: "Malawi", de: "Malawi", es: "Malaui", pt: "Malawi", it: "Malawi", ar: "ملاوي", ja: "マラウイ", zh: "马拉维" },
  MY: { en: "Malaysia", nl: "Maleisië", fr: "Malaisie", de: "Malaysia", es: "Malasia", pt: "Malásia", it: "Malaysia", ar: "ماليزيا", ja: "マレーシア", zh: "马来西亚" },
  MV: { en: "Maldives", nl: "Malediven", fr: "Maldives", de: "Malediven", es: "Maldivas", pt: "Maldivas", it: "Maldive", ar: "المالديف", ja: "モルディブ", zh: "马尔代夫" },
  ML: { en: "Mali", nl: "Mali", fr: "Mali", de: "Mali", es: "Malí", pt: "Mali", it: "Mali", ar: "مالي", ja: "マリ", zh: "马里" },
  MT: { en: "Malta", nl: "Malta", fr: "Malte", de: "Malta", es: "Malta", pt: "Malta", it: "Malta", ar: "مالطا", ja: "マルタ", zh: "马耳他" },
  MH: { en: "Marshall Islands", nl: "Marshalleilanden", fr: "Îles Marshall", de: "Marshallinseln", es: "Islas Marshall", pt: "Ilhas Marshall", it: "Isole Marshall", ar: "جزر مارشال", ja: "マーシャル諸島", zh: "马绍尔群岛" },
  MR: { en: "Mauritania", nl: "Mauritanië", fr: "Mauritanie", de: "Mauretanien", es: "Mauritania", pt: "Mauritânia", it: "Mauritania", ar: "موريتانيا", ja: "モーリタニア", zh: "毛里塔尼亚" },
  MU: { en: "Mauritius", nl: "Mauritius", fr: "Maurice", de: "Mauritius", es: "Mauricio", pt: "Maurícia", it: "Mauritius", ar: "موريشيوس", ja: "モーリシャス", zh: "毛里求斯" },
  MD: { en: "Moldova", nl: "Moldavië", fr: "Moldavie", de: "Moldau", es: "Moldavia", pt: "Moldávia", it: "Moldavia", ar: "مولدوفا", ja: "モルドバ", zh: "摩尔多瓦" },
  MC: { en: "Monaco", nl: "Monaco", fr: "Monaco", de: "Monaco", es: "Mónaco", pt: "Mónaco", it: "Monaco", ar: "موناكو", ja: "モナコ", zh: "摩纳哥" },
  MN: { en: "Mongolia", nl: "Mongolië", fr: "Mongolie", de: "Mongolei", es: "Mongolia", pt: "Mongólia", it: "Mongolia", ar: "منغوليا", ja: "モンゴル", zh: "蒙古" },
  ME: { en: "Montenegro", nl: "Montenegro", fr: "Monténégro", de: "Montenegro", es: "Montenegro", pt: "Montenegro", it: "Montenegro", ar: "الجبل الأسود", ja: "モンテネグロ", zh: "黑山" },
  MA: { en: "Morocco", nl: "Marokko", fr: "Maroc", de: "Marokko", es: "Marruecos", pt: "Marrocos", it: "Marocco", ar: "المغرب", ja: "モロッコ", zh: "摩洛哥" },
  MZ: { en: "Mozambique", nl: "Mozambique", fr: "Mozambique", de: "Mosambik", es: "Mozambique", pt: "Moçambique", it: "Mozambico", ar: "موزمبيق", ja: "モザンビーク", zh: "莫桑比克" },
  MM: { en: "Myanmar", nl: "Myanmar", fr: "Myanmar", de: "Myanmar", es: "Birmania", pt: "Mianmar", it: "Myanmar", ar: "ميانمار", ja: "ミャンマー", zh: "缅甸" },
  NA: { en: "Namibia", nl: "Namibië", fr: "Namibie", de: "Namibia", es: "Namibia", pt: "Namíbia", it: "Namibia", ar: "ناميبيا", ja: "ナミビア", zh: "纳米比亚" },
  NR: { en: "Nauru", nl: "Nauru", fr: "Nauru", de: "Nauru", es: "Nauru", pt: "Nauru", it: "Nauru", ar: "ناورو", ja: "ナウル", zh: "瑙鲁" },
  NP: { en: "Nepal", nl: "Nepal", fr: "Népal", de: "Nepal", es: "Nepal", pt: "Nepal", it: "Nepal", ar: "نيبال", ja: "ネパール", zh: "尼泊尔" },
  NZ: { en: "New Zealand", nl: "Nieuw-Zeeland", fr: "Nouvelle-Zélande", de: "Neuseeland", es: "Nueva Zelanda", pt: "Nova Zelândia", it: "Nuova Zelanda", ar: "نيوزيلندا", ja: "ニュージーランド", zh: "新西兰" },
  NI: { en: "Nicaragua", nl: "Nicaragua", fr: "Nicaragua", de: "Nicaragua", es: "Nicaragua", pt: "Nicarágua", it: "Nicaragua", ar: "نيكاراغوا", ja: "ニカラグア", zh: "尼加拉瓜" },
  NE: { en: "Niger", nl: "Niger", fr: "Niger", de: "Niger", es: "Níger", pt: "Níger", it: "Niger", ar: "النيجر", ja: "ニジェール", zh: "尼日尔" },
  NG: { en: "Nigeria", nl: "Nigeria", fr: "Nigéria", de: "Nigeria", es: "Nigeria", pt: "Nigéria", it: "Nigeria", ar: "نيجيريا", ja: "ナイジェリア", zh: "尼日利亚" },
  NU: { en: "Niue", nl: "Niue", fr: "Niué", de: "Niue", es: "Niue", pt: "Niue", it: "Niue", ar: "نيوي", ja: "ニウエ", zh: "纽埃" },
  KP: { en: "North Korea", nl: "Noord-Korea", fr: "Corée du Nord", de: "Nordkorea", es: "Corea del Norte", pt: "Coreia do Norte", it: "Corea del Nord", ar: "كوريا الشمالية", ja: "北朝鮮", zh: "朝鲜" },
  MK: { en: "North Macedonia", nl: "Noord-Macedonië", fr: "Macédoine du Nord", de: "Nordmazedonien", es: "Macedonia del Norte", pt: "Macedónia do Norte", it: "Macedonia del Nord", ar: "مقدونيا الشمالية", ja: "北マケドニア", zh: "北马其顿" },
  NO: { en: "Norway", nl: "Noorwegen", fr: "Norvège", de: "Norwegen", es: "Noruega", pt: "Noruega", it: "Norvegia", ar: "النرويج", ja: "ノルウェー", zh: "挪威" },
  OM: { en: "Oman", nl: "Oman", fr: "Oman", de: "Oman", es: "Omán", pt: "Omã", it: "Oman", ar: "عُمان", ja: "オマーン", zh: "阿曼" },
  PK: { en: "Pakistan", nl: "Pakistan", fr: "Pakistan", de: "Pakistan", es: "Pakistán", pt: "Paquistão", it: "Pakistan", ar: "باكستان", ja: "パキスタン", zh: "باکستان" },
  PW: { en: "Palau", nl: "Palau", fr: "Palaos", de: "Palau", es: "Palaos", pt: "Palau", it: "Palau", ar: "بالاو", ja: "パラオ", zh: "帕劳" },
  PS: { en: "Palestine", nl: "Palestina", fr: "Palestine", de: "Palästina", es: "Palestina", pt: "Palestina", it: "Palestina", ar: "فلسطين", ja: "パレスチナ", zh: "巴勒斯坦" },
  PA: { en: "Panama", nl: "Panama", fr: "Panama", de: "Panama", es: "Panamá", pt: "Panamá", it: "Panama", ar: "بنما", ja: "パナマ", zh: "巴拿马" },
  PG: { en: "Papua New Guinea", nl: "Papoea-Nieuw-Guinea", fr: "Papouasie-Nouvelle-Guinée", de: "Papua-Neuguinea", es: "Papúa Nueva Guinea", pt: "Papua-Nova Guiné", it: "Papua Nuova Guinea", ar: "بابوا غينيا الجديدة", ja: "パプアニューギニア", zh: "巴布亚新几内亚" },
  PY: { en: "Paraguay", nl: "Paraguay", fr: "Paraguay", de: "Paraguay", es: "Paraguay", pt: "Paraguai", it: "Paraguay", ar: "باراغواي", ja: "パラグアイ", zh: "巴拉圭" },
  PE: { en: "Peru", nl: "Peru", fr: "Pérou", de: "Peru", es: "Perú", pt: "Peru", it: "Perù", ar: "بيرو", ja: "ペルー", zh: "秘鲁" },
  PH: { en: "Philippines", nl: "Filipijnen", fr: "Philippines", de: "Philippinen", es: "Filipinas", pt: "Filipinas", it: "Filippine", ar: "الفلبين", ja: "フィリピン", zh: "菲律宾" },
  PL: { en: "Poland", nl: "Polen", fr: "Pologne", de: "Polen", es: "Polonia", pt: "Polónia", it: "Polonia", ar: "بولندا", ja: "ポーランド", zh: "波兰" },
  QA: { en: "Qatar", nl: "Qatar", fr: "Qatar", de: "Katar", es: "Catar", pt: "Qatar", it: "Qatar", ar: "قطر", ja: "カタール", zh: "卡塔尔" },
  CG: { en: "Republic of Congo", nl: "Republiek Congo", fr: "République du Congo", de: "Republik Kongo", es: "República del Congo", pt: "República do Congo", it: "Repubblica del Congo", ar: "جمهورية الكونغو", ja: "コンゴ共和国", zh: "刚果共和国" },
  RO: { en: "Romania", nl: "Roemenië", fr: "Roumanie", de: "Rumänien", es: "Rumanía", pt: "Roménia", it: "Romania", ar: "رومانيا", ja: "ルーマニア", zh: "罗马尼亚" },
  RU: { en: "Russia", nl: "Rusland", fr: "Russie", de: "Russland", es: "Rusia", pt: "Rússia", it: "Russia", ar: "روسيا", ja: "ロシア", zh: "俄罗斯" },
  RW: { en: "Rwanda", nl: "Rwanda", fr: "Rwanda", de: "Ruanda", es: "Ruanda", pt: "Ruanda", it: "Ruanda", ar: "رواندا", ja: "ルワンダ", zh: "卢旺达" },
  BL: { en: "Saint-Barthélemy", nl: "Saint-Barthélemy", fr: "Saint-Barthélemy", de: "Saint-Barthélemy", es: "San Bartolomé", pt: "São Bartolomeu", it: "Saint-Barthélemy", ar: "سانت بارتيلمي", ja: "サン・バルテルミー", zh: "圣巴泰勒米" },
  KN: { en: "Saint Kitts and Nevis", nl: "Saint Kitts en Nevis", fr: "Saint-Kitts-et-Nevis", de: "St. Kitts und Nevis", es: "San Cristóbal y Nieves", pt: "São Cristóvão e Nevis", it: "Saint Kitts e Nevis", ar: "سانت كيتس ونيفيس", ja: "セントキッツ・ネービス", zh: "圣基茨和尼维斯" },
  LC: { en: "Saint Lucia", nl: "Saint Lucia", fr: "Sainte-Lucie", de: "St. Lucia", es: "Santa Lucía", pt: "Santa Lúcia", it: "Santa Lucia", ar: "سانت لوسيا", ja: "セントルシア", zh: "圣卢西亚" },
  VC: { en: "Saint Vincent and Grenadines", nl: "Saint Vincent en de Grenadines", fr: "Saint-Vincent-et-les-Grenadines", de: "St. Vincent und die Grenadinen", es: "San Vicente y Granadinas", pt: "São Vicente e Granadinas", it: "Saint Vincent e Grenadine", ar: "سانت فنسنت وجزر غرينادين", ja: "セントビンセント・グレナディーン", zh: "圣文森特和格林纳丁斯" },
  WS: { en: "Samoa", nl: "Samoa", fr: "Samoa", de: "Samoa", es: "Samoa", pt: "Samoa", it: "Samoa", ar: "ساموا", ja: "サモア", zh: "萨摩亚" },
  SM: { en: "San Marino", nl: "San Marino", fr: "Saint-Marin", de: "San Marino", es: "San Marino", pt: "San Marino", it: "San Marino", ar: "سان مارينو", ja: "サンマリノ", zh: "圣马力诺" },
  ST: { en: "São Tomé and Príncipe", nl: "Sao Tomé en Principe", fr: "Sao Tomé-et-Príncipe", de: "São Tomé und Príncipe", es: "Santo Tomé y Príncipe", pt: "São Tomé e Príncipe", it: "São Tomé e Príncipe", ar: "ساو تومي وبرينسيبي", ja: "サントメ・プリンシペ", zh: "圣多美和普林西比" },
  SA: { en: "Saudi Arabia", nl: "Saoedi-Arabië", fr: "Arabie saoudite", de: "Saudi-Arabien", es: "Arabia Saudita", pt: "Arábia Saudita", it: "Arabia Saudita", ar: "المملكة العربية السعودية", ja: "サウジアラビア", zh: "沙特阿拉伯" },
  SN: { en: "Senegal", nl: "Senegal", fr: "Sénégal", de: "Senegal", es: "Senegal", pt: "Senegal", it: "Senegal", ar: "السنغال", ja: "セネガル", zh: "塞内加尔" },
  RS: { en: "Serbia", nl: "Servië", fr: "Serbie", de: "Serbien", es: "Serbia", pt: "Sérvia", it: "Serbia", ar: "صربيا", ja: "セルビア", zh: "塞尔维亚" },
  SL: { en: "Sierra Leone", nl: "Sierra Leone", fr: "Sierra Leone", de: "Sierra Leone", es: "Sierra Leona", pt: "Serra Leoa", it: "Sierra Leone", ar: "سيراليون", ja: "シエラレオネ", zh: "塞拉利昂" },
  SK: { en: "Slovakia", nl: "Slowakije", fr: "Slovaquie", de: "Slowakei", es: "Eslovaquia", pt: "Eslováquia", it: "Slovacchia", ar: "سلوفاكيا", ja: "スロバキア", zh: "斯洛伐克" },
  SI: { en: "Slovenia", nl: "Slovenië", fr: "Slovénie", de: "Slowenien", es: "Eslovenia", pt: "Eslovénia", it: "Slovenia", ar: "سلوفينيا", ja: "スロベニア", zh: "斯洛文尼亚" },
  SB: { en: "Solomon Islands", nl: "Salomonseilanden", fr: "Îles Salomon", de: "Salomonen", es: "Islas Salomón", pt: "Ilhas Salomão", it: "Isole Salomone", ar: "جزر سليمان", ja: "ソロモン諸島", zh: "所罗门群岛" },
  SO: { en: "Somalia", nl: "Somalië", fr: "Somalie", de: "Somalia", es: "Somalia", pt: "Somália", it: "Somalia", ar: "الصومال", ja: "ソマリア", zh: "索马里" },
  KR: { en: "South Korea", nl: "Zuid-Korea", fr: "Corée du Sud", de: "Südkorea", es: "Corea del Sur", pt: "Coreia do Sul", it: "Corea del Sud", ar: "كوريا الجنوبية", ja: "韓国", zh: "韩国" },
  SS: { en: "South Sudan", nl: "Zuid-Soedan", fr: "Soudan du Sud", de: "Südsudan", es: "Sudán del Sur", pt: "Sudão do Sul", it: "Sudan del Sud", ar: "جنوب السودان", ja: "南スーダン", zh: "南苏丹" },
  LK: { en: "Sri Lanka", nl: "Sri Lanka", fr: "Sri Lanka", de: "Sri Lanka", es: "Sri Lanka", pt: "Sri Lanka", it: "Sri Lanka", ar: "سريلانكا", ja: "スリランカ", zh: "斯里兰卡" },
  SD: { en: "Sudan", nl: "Soedan", fr: "Soudan", de: "Sudan", es: "Sudán", pt: "Sudão", it: "Sudan", ar: "السودان", ja: "スーダン", zh: "苏丹" },
  SR: { en: "Suriname", nl: "Suriname", fr: "Suriname", de: "Surinam", es: "Surinam", pt: "Suriname", it: "Suriname", ar: "سورينام", ja: "スリナム", zh: "苏里南" },
  SE: { en: "Sweden", nl: "Zweden", fr: "Suède", de: "Schweden", es: "Suecia", pt: "Suécia", it: "Svezia", ar: "السويد", ja: "スウェーデン", zh: "瑞典" },
  SY: { en: "Syria", nl: "Syrië", fr: "Syrie", de: "Syrien", es: "Siria", pt: "Síria", it: "Siria", ar: "سوريا", ja: "シリア", zh: "叙利亚" },
  TW: { en: "Taiwan", nl: "Taiwan", fr: "Taïwan", de: "Taiwan", es: "Taiwán", pt: "Taiwan", it: "Taiwan", ar: "تايوان", ja: "台湾", zh: "台湾" },
  TJ: { en: "Tajikistan", nl: "Tadzjikistan", fr: "Tadjikistan", de: "Tadschikistan", es: "Tayikistán", pt: "Tajiquistão", it: "Tagikistan", ar: "طاجيكستان", ja: "タジキスタン", zh: "塔吉克斯坦" },
  TZ: { en: "Tanzania", nl: "Tanzania", fr: "Tanzanie", de: "Tansania", es: "Tanzania", pt: "Tanzânia", it: "Tanzania", ar: "تنزانيا", ja: "タンザニア", zh: "坦桑尼亚" },
  TH: { en: "Thailand", nl: "Thailand", fr: "Thaïlande", de: "Thailand", es: "Tailandia", pt: "Tailândia", it: "Tailandia", ar: "تايلاند", ja: "タイ", zh: "泰国" },
  TL: { en: "Timor-Leste", nl: "Oost-Timor", fr: "Timor oriental", de: "Osttimor", es: "Timor Oriental", pt: "Timor-Leste", it: "Timor Est", ar: "تيمور الشرقية", ja: "東ティモール", zh: "东帝汶" },
  TG: { en: "Togo", nl: "Togo", fr: "Togo", de: "Togo", es: "Togo", pt: "Togo", it: "Togo", ar: "توغو", ja: "トーゴ", zh: "多哥" },
  TO: { en: "Tonga", nl: "Tonga", fr: "Tonga", de: "Tonga", es: "Tonga", pt: "Tonga", it: "Tonga", ar: "تونغا", ja: "トンガ", zh: "汤加" },
  TT: { en: "Trinidad and Tobago", nl: "Trinidad en Tobago", fr: "Trinité-et-Tobago", de: "Trinidad und Tobago", es: "Trinidad y Tobago", pt: "Trinidad e Tobago", it: "Trinidad e Tobago", ar: "ترينيداد وتوباغو", ja: "トリニダード・トバゴ", zh: "特立尼达和多巴哥" },
  TN: { en: "Tunisia", nl: "Tunesië", fr: "Tunisie", de: "Tunesien", es: "Túnez", pt: "Tunísia", it: "Tunisia", ar: "تونس", ja: "チュニジア", zh: "突尼斯" },
  TR: { en: "Türkiye", nl: "Turkije", fr: "Turquie", de: "Türkei", es: "Turquía", pt: "Turquia", it: "Turchia", ar: "تركيا", ja: "トルコ", zh: "土耳其" },
  TM: { en: "Turkmenistan", nl: "Turkmenistan", fr: "Turkménistan", de: "Turkmenistan", es: "Turkmenistán", pt: "Turquemenistão", it: "Turkmenistan", ar: "تركمانستان", ja: "トルクメニスタン", zh: "土库曼斯坦" },
  TC: { en: "Turks and Caicos", nl: "Turks- en Caicoseilanden", fr: "Îles Turques-et-Caïques", de: "Turks- und Caicosinseln", es: "Islas Turcas y Caicos", pt: "Ilhas Turcas e Caicos", it: "Turks e Caicos", ar: "جزر تركس وكايكوس", ja: "タークス・カイコス諸島", zh: "特克斯和凯科斯群岛" },
  TV: { en: "Tuvalu", nl: "Tuvalu", fr: "Tuvalu", de: "Tuvalu", es: "Tuvalu", pt: "Tuvalu", it: "Tuvalu", ar: "توفالو", ja: "ツバル", zh: "图瓦卢" },
  UG: { en: "Uganda", nl: "Oeganda", fr: "Ouganda", de: "Uganda", es: "Uganda", pt: "Uganda", it: "Uganda", ar: "أوغندا", ja: "ウガンダ", zh: "乌干达" },
  UA: { en: "Ukraine", nl: "Oekraïne", fr: "Ukraine", de: "Ukraine", es: "Ucrania", pt: "Ucrânia", it: "Ucraina", ar: "أوكرانيا", ja: "ウクライナ", zh: "乌克兰" },
  UY: { en: "Uruguay", nl: "Uruguay", fr: "Uruguay", de: "Uruguay", es: "Uruguay", pt: "Uruguai", it: "Uruguay", ar: "أوروغواي", ja: "ウルグアイ", zh: "乌拉圭" },
  UZ: { en: "Uzbekistan", nl: "Oezbekistan", fr: "Ouzbékistan", de: "Usbekistan", es: "Uzbekistán", pt: "Uzbequistão", it: "Uzbekistan", ar: "أوزبكستان", ja: "ウズベキスタン", zh: "乌兹别克斯坦" },
  VU: { en: "Vanuatu", nl: "Vanuatu", fr: "Vanuatu", de: "Vanuatu", es: "Vanuatu", pt: "Vanuatu", it: "Vanuatu", ar: "فانواتو", ja: "バヌアツ", zh: "瓦努阿图" },
  VA: { en: "Vatican City", nl: "Vaticaanstad", fr: "Cité du Vatican", de: "Vatikanstadt", es: "Ciudad del Vaticano", pt: "Cidade do Vaticano", it: "Città del Vaticano", ar: "مدينة الفاتيكان", ja: "バチカン市国", zh: "梵蒂冈" },
  VE: { en: "Venezuela", nl: "Venezuela", fr: "Venezuela", de: "Venezuela", es: "Venezuela", pt: "Venezuela", it: "Venezuela", ar: "فنزويلا", ja: "ベネズエラ", zh: "委内瑞拉" },
  VN: { en: "Vietnam", nl: "Vietnam", fr: "Vietnam", de: "Vietnam", es: "Vietnam", pt: "Vietnã", it: "Vietnam", ar: "فيتنام", ja: "ベトナム", zh: "越南" },
  YE: { en: "Yemen", nl: "Jemen", fr: "Yémen", de: "Jemen", es: "Yemen", pt: "Iémen", it: "Yemen", ar: "اليمن", ja: "イエメン", zh: "也门" },
  ZM: { en: "Zambia", nl: "Zambia", fr: "Zambie", de: "Sambia", es: "Zambia", pt: "Zâmbia", it: "Zambia", ar: "زامبيا", ja: "ザンビア", zh: "赞比亚" },
  ZW: { en: "Zimbabwe", nl: "Zimbabwe", fr: "Zimbabwe", de: "Simbabwe", es: "Zimbabue", pt: "Zimbábue", it: "Zimbabwe", ar: "زيمبابوي", ja: "ジンバブエ", zh: "津巴布韦" },
};

/**
 * Returns the localized name for a region code and locale string.
 * Locale can be a full tag ("it-IT") or a base code ("it").
 * Falls back: requested lang → "en" → region_code.
 */
export function getLocalizedRegionName(
  regionCode: string,
  locale: string,
  fallback?: string,
): string {
  const names = REGION_NAMES[regionCode.toUpperCase()];
  if (!names) return fallback ?? regionCode;
  const base = locale.split("-")[0].toLowerCase();
  return names[base] ?? names["en"] ?? fallback ?? regionCode;
}
