import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import cultureRouter from "./culture";
import scenariosRouter from "./scenarios";
import nobleScoreRouter from "./noble_score";
import translationsRouter from "./translations";
import counselRouter from "./counsel";
import detectRegionRouter from "./detect-region";
import authRouter from "./auth";
import oidcRouter from "./oidc";
import adminRouter from "./admin";
import stripeAdminRouter from "./stripe-admin";
import subscriptionRouter from "./subscription";
import registerQualityRouter from "./register-quality";
import useCasesRouter from "./use_cases";
import mirrorLogRouter from "./mirror-log";
import googleOAuthRouter from "./google-oauth";
import learningTracksRouter from "./learning-tracks";
import venuesRouter from "./venues";
import guidesRouter from "./guides";
import questsRouter from "./quests";
import invitationsRouter from "./invitations";
import companionRouter from "./companion";
import roleplayRouter from "./roleplay";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(googleOAuthRouter);
router.use(oidcRouter);
router.use(usersRouter);
router.use(cultureRouter);
router.use(scenariosRouter);
router.use(nobleScoreRouter);
router.use(translationsRouter);
router.use(counselRouter);
router.use(detectRegionRouter);
router.use(adminRouter);
router.use(stripeAdminRouter);
router.use(subscriptionRouter);
router.use(registerQualityRouter);
router.use(useCasesRouter);
router.use(mirrorLogRouter);
router.use(learningTracksRouter);
router.use(venuesRouter);
router.use(guidesRouter);
router.use(questsRouter);
router.use(invitationsRouter);
router.use(companionRouter);
router.use(roleplayRouter);

export default router;
