-- Migration: Badge & Erkenningssysteem
-- Applied: 2026-04-27
-- Method: Applied via raw SQL (drizzle-kit push skipped — hangs on existing scenarios constraint)
-- All statements use IF NOT EXISTS / ON CONFLICT DO NOTHING.

-- 1. badges: master catalogue of all possible badges
CREATE TABLE IF NOT EXISTS badges (
  id              SERIAL PRIMARY KEY,
  slug            TEXT NOT NULL UNIQUE,
  title           TEXT NOT NULL,
  description     TEXT NOT NULL,
  badge_type      TEXT NOT NULL,   -- "pillar" | "phase" | "country" | "ambassador"
  register        TEXT NOT NULL,   -- "middle_class" | "elite"
  research_pillar TEXT,            -- "P1" | "P2" | "P3" (NULL for phase/country/ambassador)
  phase           INTEGER,         -- NULL for country/ambassador badges
  region_code     TEXT,            -- NULL for universal ambassador badge
  icon_url        TEXT,            -- App Storage URL (nullable — uses generated SVG if absent)
  created_at      TIMESTAMP DEFAULT NOW()
);

-- 2. user_badges: awarded badges per user (idempotent via UNIQUE constraint)
CREATE TABLE IF NOT EXISTS user_badges (
  id          SERIAL PRIMARY KEY,
  user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  badge_id    INTEGER NOT NULL REFERENCES badges(id),
  awarded_at  TIMESTAMP DEFAULT NOW(),
  visible     BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT ub_user_badge_unique UNIQUE (user_id, badge_id)
);

CREATE INDEX IF NOT EXISTS ub_user_idx ON user_badges (user_id);

-- Seed: 568 badges covering all 21 ACTIVE_REGIONS × 5 phases × middle_class pillars
-- + elite phase badges + country badges + ambassador badge
-- Applied via code_execution seed loop (see 0005_badge_seed.sql note)
-- Idempotent: ON CONFLICT (slug) DO NOTHING
-- Badge seed: 568 badges (idempotent — ON CONFLICT DO NOTHING)
INSERT INTO badges (slug, title, description, badge_type, register, research_pillar, phase, region_code, icon_url) VALUES
('mc-gb-ph1-p1', 'Adaptive Linguistics — The Foyer', 'Mastered Adaptive Linguistics in Phase 1 (The Foyer) for United Kingdom.', 'pillar', 'middle_class', 'P1', 1, 'GB', NULL),
('mc-gb-ph1-p2', 'Professional Branding — The Foyer', 'Mastered Professional Branding in Phase 1 (The Foyer) for United Kingdom.', 'pillar', 'middle_class', 'P2', 1, 'GB', NULL),
('mc-gb-ph1-p3', 'Social Navigation — The Foyer', 'Mastered Social Navigation in Phase 1 (The Foyer) for United Kingdom.', 'pillar', 'middle_class', 'P3', 1, 'GB', NULL),
('mc-gb-ph1-phase', 'The Foyer — United Kingdom', 'Completed all three pillars of Phase 1 (The Foyer) for United Kingdom.', 'phase', 'middle_class', NULL, 1, 'GB', NULL),
('elite-gb-ph1-phase', 'The Foyer (Elite) — United Kingdom', 'Mastered the Elite track of Phase 1 (The Foyer) for United Kingdom.', 'phase', 'elite', NULL, 1, 'GB', NULL),
('mc-gb-ph2-p1', 'Adaptive Linguistics — The Salon', 'Mastered Adaptive Linguistics in Phase 2 (The Salon) for United Kingdom.', 'pillar', 'middle_class', 'P1', 2, 'GB', NULL),
('mc-gb-ph2-p2', 'Professional Branding — The Salon', 'Mastered Professional Branding in Phase 2 (The Salon) for United Kingdom.', 'pillar', 'middle_class', 'P2', 2, 'GB', NULL),
('mc-gb-ph2-p3', 'Social Navigation — The Salon', 'Mastered Social Navigation in Phase 2 (The Salon) for United Kingdom.', 'pillar', 'middle_class', 'P3', 2, 'GB', NULL),
('mc-gb-ph2-phase', 'The Salon — United Kingdom', 'Completed all three pillars of Phase 2 (The Salon) for United Kingdom.', 'phase', 'middle_class', NULL, 2, 'GB', NULL),
('elite-gb-ph2-phase', 'The Salon (Elite) — United Kingdom', 'Mastered the Elite track of Phase 2 (The Salon) for United Kingdom.', 'phase', 'elite', NULL, 2, 'GB', NULL),
('mc-gb-ph3-p1', 'Adaptive Linguistics — The Arena', 'Mastered Adaptive Linguistics in Phase 3 (The Arena) for United Kingdom.', 'pillar', 'middle_class', 'P1', 3, 'GB', NULL),
('mc-gb-ph3-p2', 'Professional Branding — The Arena', 'Mastered Professional Branding in Phase 3 (The Arena) for United Kingdom.', 'pillar', 'middle_class', 'P2', 3, 'GB', NULL),
('mc-gb-ph3-p3', 'Social Navigation — The Arena', 'Mastered Social Navigation in Phase 3 (The Arena) for United Kingdom.', 'pillar', 'middle_class', 'P3', 3, 'GB', NULL),
('mc-gb-ph3-phase', 'The Arena — United Kingdom', 'Completed all three pillars of Phase 3 (The Arena) for United Kingdom.', 'phase', 'middle_class', NULL, 3, 'GB', NULL),
('elite-gb-ph3-phase', 'The Arena (Elite) — United Kingdom', 'Mastered the Elite track of Phase 3 (The Arena) for United Kingdom.', 'phase', 'elite', NULL, 3, 'GB', NULL),
('mc-gb-ph4-p1', 'Adaptive Linguistics — The Sanctum', 'Mastered Adaptive Linguistics in Phase 4 (The Sanctum) for United Kingdom.', 'pillar', 'middle_class', 'P1', 4, 'GB', NULL),
('mc-gb-ph4-p2', 'Professional Branding — The Sanctum', 'Mastered Professional Branding in Phase 4 (The Sanctum) for United Kingdom.', 'pillar', 'middle_class', 'P2', 4, 'GB', NULL),
('mc-gb-ph4-p3', 'Social Navigation — The Sanctum', 'Mastered Social Navigation in Phase 4 (The Sanctum) for United Kingdom.', 'pillar', 'middle_class', 'P3', 4, 'GB', NULL),
('mc-gb-ph4-phase', 'The Sanctum — United Kingdom', 'Completed all three pillars of Phase 4 (The Sanctum) for United Kingdom.', 'phase', 'middle_class', NULL, 4, 'GB', NULL),
('elite-gb-ph4-phase', 'The Sanctum (Elite) — United Kingdom', 'Mastered the Elite track of Phase 4 (The Sanctum) for United Kingdom.', 'phase', 'elite', NULL, 4, 'GB', NULL),
('mc-gb-ph5-p1', 'Adaptive Linguistics — The Summit', 'Mastered Adaptive Linguistics in Phase 5 (The Summit) for United Kingdom.', 'pillar', 'middle_class', 'P1', 5, 'GB', NULL),
('mc-gb-ph5-p2', 'Professional Branding — The Summit', 'Mastered Professional Branding in Phase 5 (The Summit) for United Kingdom.', 'pillar', 'middle_class', 'P2', 5, 'GB', NULL),
('mc-gb-ph5-p3', 'Social Navigation — The Summit', 'Mastered Social Navigation in Phase 5 (The Summit) for United Kingdom.', 'pillar', 'middle_class', 'P3', 5, 'GB', NULL),
('mc-gb-ph5-phase', 'The Summit — United Kingdom', 'Completed all three pillars of Phase 5 (The Summit) for United Kingdom.', 'phase', 'middle_class', NULL, 5, 'GB', NULL),
('elite-gb-ph5-phase', 'The Summit (Elite) — United Kingdom', 'Mastered the Elite track of Phase 5 (The Summit) for United Kingdom.', 'phase', 'elite', NULL, 5, 'GB', NULL),
('mc-gb-country', 'Gecertificeerd voor United Kingdom — Middenklasse', 'Earned all five Middle Class phase badges for United Kingdom.', 'country', 'middle_class', NULL, NULL, 'GB', NULL),
('elite-gb-country', 'Gecertificeerd voor United Kingdom — Elite', 'Earned all five Elite phase badges for United Kingdom.', 'country', 'elite', NULL, NULL, 'GB', NULL),
('mc-us-ph1-p1', 'Adaptive Linguistics — The Foyer', 'Mastered Adaptive Linguistics in Phase 1 (The Foyer) for United States.', 'pillar', 'middle_class', 'P1', 1, 'US', NULL),
('mc-us-ph1-p2', 'Professional Branding — The Foyer', 'Mastered Professional Branding in Phase 1 (The Foyer) for United States.', 'pillar', 'middle_class', 'P2', 1, 'US', NULL),
('mc-us-ph1-p3', 'Social Navigation — The Foyer', 'Mastered Social Navigation in Phase 1 (The Foyer) for United States.', 'pillar', 'middle_class', 'P3', 1, 'US', NULL),
('mc-us-ph1-phase', 'The Foyer — United States', 'Completed all three pillars of Phase 1 (The Foyer) for United States.', 'phase', 'middle_class', NULL, 1, 'US', NULL),
('elite-us-ph1-phase', 'The Foyer (Elite) — United States', 'Mastered the Elite track of Phase 1 (The Foyer) for United States.', 'phase', 'elite', NULL, 1, 'US', NULL),
('mc-us-ph2-p1', 'Adaptive Linguistics — The Salon', 'Mastered Adaptive Linguistics in Phase 2 (The Salon) for United States.', 'pillar', 'middle_class', 'P1', 2, 'US', NULL),
('mc-us-ph2-p2', 'Professional Branding — The Salon', 'Mastered Professional Branding in Phase 2 (The Salon) for United States.', 'pillar', 'middle_class', 'P2', 2, 'US', NULL),
('mc-us-ph2-p3', 'Social Navigation — The Salon', 'Mastered Social Navigation in Phase 2 (The Salon) for United States.', 'pillar', 'middle_class', 'P3', 2, 'US', NULL),
('mc-us-ph2-phase', 'The Salon — United States', 'Completed all three pillars of Phase 2 (The Salon) for United States.', 'phase', 'middle_class', NULL, 2, 'US', NULL),
('elite-us-ph2-phase', 'The Salon (Elite) — United States', 'Mastered the Elite track of Phase 2 (The Salon) for United States.', 'phase', 'elite', NULL, 2, 'US', NULL),
('mc-us-ph3-p1', 'Adaptive Linguistics — The Arena', 'Mastered Adaptive Linguistics in Phase 3 (The Arena) for United States.', 'pillar', 'middle_class', 'P1', 3, 'US', NULL),
('mc-us-ph3-p2', 'Professional Branding — The Arena', 'Mastered Professional Branding in Phase 3 (The Arena) for United States.', 'pillar', 'middle_class', 'P2', 3, 'US', NULL),
('mc-us-ph3-p3', 'Social Navigation — The Arena', 'Mastered Social Navigation in Phase 3 (The Arena) for United States.', 'pillar', 'middle_class', 'P3', 3, 'US', NULL),
('mc-us-ph3-phase', 'The Arena — United States', 'Completed all three pillars of Phase 3 (The Arena) for United States.', 'phase', 'middle_class', NULL, 3, 'US', NULL),
('elite-us-ph3-phase', 'The Arena (Elite) — United States', 'Mastered the Elite track of Phase 3 (The Arena) for United States.', 'phase', 'elite', NULL, 3, 'US', NULL),
('mc-us-ph4-p1', 'Adaptive Linguistics — The Sanctum', 'Mastered Adaptive Linguistics in Phase 4 (The Sanctum) for United States.', 'pillar', 'middle_class', 'P1', 4, 'US', NULL),
('mc-us-ph4-p2', 'Professional Branding — The Sanctum', 'Mastered Professional Branding in Phase 4 (The Sanctum) for United States.', 'pillar', 'middle_class', 'P2', 4, 'US', NULL),
('mc-us-ph4-p3', 'Social Navigation — The Sanctum', 'Mastered Social Navigation in Phase 4 (The Sanctum) for United States.', 'pillar', 'middle_class', 'P3', 4, 'US', NULL),
('mc-us-ph4-phase', 'The Sanctum — United States', 'Completed all three pillars of Phase 4 (The Sanctum) for United States.', 'phase', 'middle_class', NULL, 4, 'US', NULL),
('elite-us-ph4-phase', 'The Sanctum (Elite) — United States', 'Mastered the Elite track of Phase 4 (The Sanctum) for United States.', 'phase', 'elite', NULL, 4, 'US', NULL),
('mc-us-ph5-p1', 'Adaptive Linguistics — The Summit', 'Mastered Adaptive Linguistics in Phase 5 (The Summit) for United States.', 'pillar', 'middle_class', 'P1', 5, 'US', NULL),
('mc-us-ph5-p2', 'Professional Branding — The Summit', 'Mastered Professional Branding in Phase 5 (The Summit) for United States.', 'pillar', 'middle_class', 'P2', 5, 'US', NULL),
('mc-us-ph5-p3', 'Social Navigation — The Summit', 'Mastered Social Navigation in Phase 5 (The Summit) for United States.', 'pillar', 'middle_class', 'P3', 5, 'US', NULL),
('mc-us-ph5-phase', 'The Summit — United States', 'Completed all three pillars of Phase 5 (The Summit) for United States.', 'phase', 'middle_class', NULL, 5, 'US', NULL),
('elite-us-ph5-phase', 'The Summit (Elite) — United States', 'Mastered the Elite track of Phase 5 (The Summit) for United States.', 'phase', 'elite', NULL, 5, 'US', NULL),
('mc-us-country', 'Gecertificeerd voor United States — Middenklasse', 'Earned all five Middle Class phase badges for United States.', 'country', 'middle_class', NULL, NULL, 'US', NULL),
('elite-us-country', 'Gecertificeerd voor United States — Elite', 'Earned all five Elite phase badges for United States.', 'country', 'elite', NULL, NULL, 'US', NULL),
('mc-ae-ph1-p1', 'Adaptive Linguistics — The Foyer', 'Mastered Adaptive Linguistics in Phase 1 (The Foyer) for UAE / Dubai.', 'pillar', 'middle_class', 'P1', 1, 'AE', NULL),
('mc-ae-ph1-p2', 'Professional Branding — The Foyer', 'Mastered Professional Branding in Phase 1 (The Foyer) for UAE / Dubai.', 'pillar', 'middle_class', 'P2', 1, 'AE', NULL),
('mc-ae-ph1-p3', 'Social Navigation — The Foyer', 'Mastered Social Navigation in Phase 1 (The Foyer) for UAE / Dubai.', 'pillar', 'middle_class', 'P3', 1, 'AE', NULL),
('mc-ae-ph1-phase', 'The Foyer — UAE / Dubai', 'Completed all three pillars of Phase 1 (The Foyer) for UAE / Dubai.', 'phase', 'middle_class', NULL, 1, 'AE', NULL),
('elite-ae-ph1-phase', 'The Foyer (Elite) — UAE / Dubai', 'Mastered the Elite track of Phase 1 (The Foyer) for UAE / Dubai.', 'phase', 'elite', NULL, 1, 'AE', NULL),
('mc-ae-ph2-p1', 'Adaptive Linguistics — The Salon', 'Mastered Adaptive Linguistics in Phase 2 (The Salon) for UAE / Dubai.', 'pillar', 'middle_class', 'P1', 2, 'AE', NULL),
('mc-ae-ph2-p2', 'Professional Branding — The Salon', 'Mastered Professional Branding in Phase 2 (The Salon) for UAE / Dubai.', 'pillar', 'middle_class', 'P2', 2, 'AE', NULL),
('mc-ae-ph2-p3', 'Social Navigation — The Salon', 'Mastered Social Navigation in Phase 2 (The Salon) for UAE / Dubai.', 'pillar', 'middle_class', 'P3', 2, 'AE', NULL),
('mc-ae-ph2-phase', 'The Salon — UAE / Dubai', 'Completed all three pillars of Phase 2 (The Salon) for UAE / Dubai.', 'phase', 'middle_class', NULL, 2, 'AE', NULL),
('elite-ae-ph2-phase', 'The Salon (Elite) — UAE / Dubai', 'Mastered the Elite track of Phase 2 (The Salon) for UAE / Dubai.', 'phase', 'elite', NULL, 2, 'AE', NULL),
('mc-ae-ph3-p1', 'Adaptive Linguistics — The Arena', 'Mastered Adaptive Linguistics in Phase 3 (The Arena) for UAE / Dubai.', 'pillar', 'middle_class', 'P1', 3, 'AE', NULL),
('mc-ae-ph3-p2', 'Professional Branding — The Arena', 'Mastered Professional Branding in Phase 3 (The Arena) for UAE / Dubai.', 'pillar', 'middle_class', 'P2', 3, 'AE', NULL),
('mc-ae-ph3-p3', 'Social Navigation — The Arena', 'Mastered Social Navigation in Phase 3 (The Arena) for UAE / Dubai.', 'pillar', 'middle_class', 'P3', 3, 'AE', NULL),
('mc-ae-ph3-phase', 'The Arena — UAE / Dubai', 'Completed all three pillars of Phase 3 (The Arena) for UAE / Dubai.', 'phase', 'middle_class', NULL, 3, 'AE', NULL),
('elite-ae-ph3-phase', 'The Arena (Elite) — UAE / Dubai', 'Mastered the Elite track of Phase 3 (The Arena) for UAE / Dubai.', 'phase', 'elite', NULL, 3, 'AE', NULL),
('mc-ae-ph4-p1', 'Adaptive Linguistics — The Sanctum', 'Mastered Adaptive Linguistics in Phase 4 (The Sanctum) for UAE / Dubai.', 'pillar', 'middle_class', 'P1', 4, 'AE', NULL),
('mc-ae-ph4-p2', 'Professional Branding — The Sanctum', 'Mastered Professional Branding in Phase 4 (The Sanctum) for UAE / Dubai.', 'pillar', 'middle_class', 'P2', 4, 'AE', NULL),
('mc-ae-ph4-p3', 'Social Navigation — The Sanctum', 'Mastered Social Navigation in Phase 4 (The Sanctum) for UAE / Dubai.', 'pillar', 'middle_class', 'P3', 4, 'AE', NULL),
('mc-ae-ph4-phase', 'The Sanctum — UAE / Dubai', 'Completed all three pillars of Phase 4 (The Sanctum) for UAE / Dubai.', 'phase', 'middle_class', NULL, 4, 'AE', NULL),
('elite-ae-ph4-phase', 'The Sanctum (Elite) — UAE / Dubai', 'Mastered the Elite track of Phase 4 (The Sanctum) for UAE / Dubai.', 'phase', 'elite', NULL, 4, 'AE', NULL),
('mc-ae-ph5-p1', 'Adaptive Linguistics — The Summit', 'Mastered Adaptive Linguistics in Phase 5 (The Summit) for UAE / Dubai.', 'pillar', 'middle_class', 'P1', 5, 'AE', NULL),
('mc-ae-ph5-p2', 'Professional Branding — The Summit', 'Mastered Professional Branding in Phase 5 (The Summit) for UAE / Dubai.', 'pillar', 'middle_class', 'P2', 5, 'AE', NULL),
('mc-ae-ph5-p3', 'Social Navigation — The Summit', 'Mastered Social Navigation in Phase 5 (The Summit) for UAE / Dubai.', 'pillar', 'middle_class', 'P3', 5, 'AE', NULL),
('mc-ae-ph5-phase', 'The Summit — UAE / Dubai', 'Completed all three pillars of Phase 5 (The Summit) for UAE / Dubai.', 'phase', 'middle_class', NULL, 5, 'AE', NULL),
('elite-ae-ph5-phase', 'The Summit (Elite) — UAE / Dubai', 'Mastered the Elite track of Phase 5 (The Summit) for UAE / Dubai.', 'phase', 'elite', NULL, 5, 'AE', NULL),
('mc-ae-country', 'Gecertificeerd voor UAE / Dubai — Middenklasse', 'Earned all five Middle Class phase badges for UAE / Dubai.', 'country', 'middle_class', NULL, NULL, 'AE', NULL),
('elite-ae-country', 'Gecertificeerd voor UAE / Dubai — Elite', 'Earned all five Elite phase badges for UAE / Dubai.', 'country', 'elite', NULL, NULL, 'AE', NULL),
('mc-cn-ph1-p1', 'Adaptive Linguistics — The Foyer', 'Mastered Adaptive Linguistics in Phase 1 (The Foyer) for China.', 'pillar', 'middle_class', 'P1', 1, 'CN', NULL),
('mc-cn-ph1-p2', 'Professional Branding — The Foyer', 'Mastered Professional Branding in Phase 1 (The Foyer) for China.', 'pillar', 'middle_class', 'P2', 1, 'CN', NULL),
('mc-cn-ph1-p3', 'Social Navigation — The Foyer', 'Mastered Social Navigation in Phase 1 (The Foyer) for China.', 'pillar', 'middle_class', 'P3', 1, 'CN', NULL),
('mc-cn-ph1-phase', 'The Foyer — China', 'Completed all three pillars of Phase 1 (The Foyer) for China.', 'phase', 'middle_class', NULL, 1, 'CN', NULL),
('elite-cn-ph1-phase', 'The Foyer (Elite) — China', 'Mastered the Elite track of Phase 1 (The Foyer) for China.', 'phase', 'elite', NULL, 1, 'CN', NULL),
('mc-cn-ph2-p1', 'Adaptive Linguistics — The Salon', 'Mastered Adaptive Linguistics in Phase 2 (The Salon) for China.', 'pillar', 'middle_class', 'P1', 2, 'CN', NULL),
('mc-cn-ph2-p2', 'Professional Branding — The Salon', 'Mastered Professional Branding in Phase 2 (The Salon) for China.', 'pillar', 'middle_class', 'P2', 2, 'CN', NULL),
('mc-cn-ph2-p3', 'Social Navigation — The Salon', 'Mastered Social Navigation in Phase 2 (The Salon) for China.', 'pillar', 'middle_class', 'P3', 2, 'CN', NULL),
('mc-cn-ph2-phase', 'The Salon — China', 'Completed all three pillars of Phase 2 (The Salon) for China.', 'phase', 'middle_class', NULL, 2, 'CN', NULL),
('elite-cn-ph2-phase', 'The Salon (Elite) — China', 'Mastered the Elite track of Phase 2 (The Salon) for China.', 'phase', 'elite', NULL, 2, 'CN', NULL),
('mc-cn-ph3-p1', 'Adaptive Linguistics — The Arena', 'Mastered Adaptive Linguistics in Phase 3 (The Arena) for China.', 'pillar', 'middle_class', 'P1', 3, 'CN', NULL),
('mc-cn-ph3-p2', 'Professional Branding — The Arena', 'Mastered Professional Branding in Phase 3 (The Arena) for China.', 'pillar', 'middle_class', 'P2', 3, 'CN', NULL),
('mc-cn-ph3-p3', 'Social Navigation — The Arena', 'Mastered Social Navigation in Phase 3 (The Arena) for China.', 'pillar', 'middle_class', 'P3', 3, 'CN', NULL),
('mc-cn-ph3-phase', 'The Arena — China', 'Completed all three pillars of Phase 3 (The Arena) for China.', 'phase', 'middle_class', NULL, 3, 'CN', NULL),
('elite-cn-ph3-phase', 'The Arena (Elite) — China', 'Mastered the Elite track of Phase 3 (The Arena) for China.', 'phase', 'elite', NULL, 3, 'CN', NULL),
('mc-cn-ph4-p1', 'Adaptive Linguistics — The Sanctum', 'Mastered Adaptive Linguistics in Phase 4 (The Sanctum) for China.', 'pillar', 'middle_class', 'P1', 4, 'CN', NULL),
('mc-cn-ph4-p2', 'Professional Branding — The Sanctum', 'Mastered Professional Branding in Phase 4 (The Sanctum) for China.', 'pillar', 'middle_class', 'P2', 4, 'CN', NULL),
('mc-cn-ph4-p3', 'Social Navigation — The Sanctum', 'Mastered Social Navigation in Phase 4 (The Sanctum) for China.', 'pillar', 'middle_class', 'P3', 4, 'CN', NULL),
('mc-cn-ph4-phase', 'The Sanctum — China', 'Completed all three pillars of Phase 4 (The Sanctum) for China.', 'phase', 'middle_class', NULL, 4, 'CN', NULL),
('elite-cn-ph4-phase', 'The Sanctum (Elite) — China', 'Mastered the Elite track of Phase 4 (The Sanctum) for China.', 'phase', 'elite', NULL, 4, 'CN', NULL),
('mc-cn-ph5-p1', 'Adaptive Linguistics — The Summit', 'Mastered Adaptive Linguistics in Phase 5 (The Summit) for China.', 'pillar', 'middle_class', 'P1', 5, 'CN', NULL),
('mc-cn-ph5-p2', 'Professional Branding — The Summit', 'Mastered Professional Branding in Phase 5 (The Summit) for China.', 'pillar', 'middle_class', 'P2', 5, 'CN', NULL),
('mc-cn-ph5-p3', 'Social Navigation — The Summit', 'Mastered Social Navigation in Phase 5 (The Summit) for China.', 'pillar', 'middle_class', 'P3', 5, 'CN', NULL),
('mc-cn-ph5-phase', 'The Summit — China', 'Completed all three pillars of Phase 5 (The Summit) for China.', 'phase', 'middle_class', NULL, 5, 'CN', NULL),
('elite-cn-ph5-phase', 'The Summit (Elite) — China', 'Mastered the Elite track of Phase 5 (The Summit) for China.', 'phase', 'elite', NULL, 5, 'CN', NULL),
('mc-cn-country', 'Gecertificeerd voor China — Middenklasse', 'Earned all five Middle Class phase badges for China.', 'country', 'middle_class', NULL, NULL, 'CN', NULL),
('elite-cn-country', 'Gecertificeerd voor China — Elite', 'Earned all five Elite phase badges for China.', 'country', 'elite', NULL, NULL, 'CN', NULL),
('mc-jp-ph1-p1', 'Adaptive Linguistics — The Foyer', 'Mastered Adaptive Linguistics in Phase 1 (The Foyer) for Japan.', 'pillar', 'middle_class', 'P1', 1, 'JP', NULL),
('mc-jp-ph1-p2', 'Professional Branding — The Foyer', 'Mastered Professional Branding in Phase 1 (The Foyer) for Japan.', 'pillar', 'middle_class', 'P2', 1, 'JP', NULL),
('mc-jp-ph1-p3', 'Social Navigation — The Foyer', 'Mastered Social Navigation in Phase 1 (The Foyer) for Japan.', 'pillar', 'middle_class', 'P3', 1, 'JP', NULL),
('mc-jp-ph1-phase', 'The Foyer — Japan', 'Completed all three pillars of Phase 1 (The Foyer) for Japan.', 'phase', 'middle_class', NULL, 1, 'JP', NULL),
('elite-jp-ph1-phase', 'The Foyer (Elite) — Japan', 'Mastered the Elite track of Phase 1 (The Foyer) for Japan.', 'phase', 'elite', NULL, 1, 'JP', NULL),
('mc-jp-ph2-p1', 'Adaptive Linguistics — The Salon', 'Mastered Adaptive Linguistics in Phase 2 (The Salon) for Japan.', 'pillar', 'middle_class', 'P1', 2, 'JP', NULL),
('mc-jp-ph2-p2', 'Professional Branding — The Salon', 'Mastered Professional Branding in Phase 2 (The Salon) for Japan.', 'pillar', 'middle_class', 'P2', 2, 'JP', NULL),
('mc-jp-ph2-p3', 'Social Navigation — The Salon', 'Mastered Social Navigation in Phase 2 (The Salon) for Japan.', 'pillar', 'middle_class', 'P3', 2, 'JP', NULL),
('mc-jp-ph2-phase', 'The Salon — Japan', 'Completed all three pillars of Phase 2 (The Salon) for Japan.', 'phase', 'middle_class', NULL, 2, 'JP', NULL),
('elite-jp-ph2-phase', 'The Salon (Elite) — Japan', 'Mastered the Elite track of Phase 2 (The Salon) for Japan.', 'phase', 'elite', NULL, 2, 'JP', NULL),
('mc-jp-ph3-p1', 'Adaptive Linguistics — The Arena', 'Mastered Adaptive Linguistics in Phase 3 (The Arena) for Japan.', 'pillar', 'middle_class', 'P1', 3, 'JP', NULL),
('mc-jp-ph3-p2', 'Professional Branding — The Arena', 'Mastered Professional Branding in Phase 3 (The Arena) for Japan.', 'pillar', 'middle_class', 'P2', 3, 'JP', NULL),
('mc-jp-ph3-p3', 'Social Navigation — The Arena', 'Mastered Social Navigation in Phase 3 (The Arena) for Japan.', 'pillar', 'middle_class', 'P3', 3, 'JP', NULL),
('mc-jp-ph3-phase', 'The Arena — Japan', 'Completed all three pillars of Phase 3 (The Arena) for Japan.', 'phase', 'middle_class', NULL, 3, 'JP', NULL),
('elite-jp-ph3-phase', 'The Arena (Elite) — Japan', 'Mastered the Elite track of Phase 3 (The Arena) for Japan.', 'phase', 'elite', NULL, 3, 'JP', NULL),
('mc-jp-ph4-p1', 'Adaptive Linguistics — The Sanctum', 'Mastered Adaptive Linguistics in Phase 4 (The Sanctum) for Japan.', 'pillar', 'middle_class', 'P1', 4, 'JP', NULL),
('mc-jp-ph4-p2', 'Professional Branding — The Sanctum', 'Mastered Professional Branding in Phase 4 (The Sanctum) for Japan.', 'pillar', 'middle_class', 'P2', 4, 'JP', NULL),
('mc-jp-ph4-p3', 'Social Navigation — The Sanctum', 'Mastered Social Navigation in Phase 4 (The Sanctum) for Japan.', 'pillar', 'middle_class', 'P3', 4, 'JP', NULL),
('mc-jp-ph4-phase', 'The Sanctum — Japan', 'Completed all three pillars of Phase 4 (The Sanctum) for Japan.', 'phase', 'middle_class', NULL, 4, 'JP', NULL),
('elite-jp-ph4-phase', 'The Sanctum (Elite) — Japan', 'Mastered the Elite track of Phase 4 (The Sanctum) for Japan.', 'phase', 'elite', NULL, 4, 'JP', NULL),
('mc-jp-ph5-p1', 'Adaptive Linguistics — The Summit', 'Mastered Adaptive Linguistics in Phase 5 (The Summit) for Japan.', 'pillar', 'middle_class', 'P1', 5, 'JP', NULL),
('mc-jp-ph5-p2', 'Professional Branding — The Summit', 'Mastered Professional Branding in Phase 5 (The Summit) for Japan.', 'pillar', 'middle_class', 'P2', 5, 'JP', NULL),
('mc-jp-ph5-p3', 'Social Navigation — The Summit', 'Mastered Social Navigation in Phase 5 (The Summit) for Japan.', 'pillar', 'middle_class', 'P3', 5, 'JP', NULL),
('mc-jp-ph5-phase', 'The Summit — Japan', 'Completed all three pillars of Phase 5 (The Summit) for Japan.', 'phase', 'middle_class', NULL, 5, 'JP', NULL),
('elite-jp-ph5-phase', 'The Summit (Elite) — Japan', 'Mastered the Elite track of Phase 5 (The Summit) for Japan.', 'phase', 'elite', NULL, 5, 'JP', NULL),
('mc-jp-country', 'Gecertificeerd voor Japan — Middenklasse', 'Earned all five Middle Class phase badges for Japan.', 'country', 'middle_class', NULL, NULL, 'JP', NULL),
('elite-jp-country', 'Gecertificeerd voor Japan — Elite', 'Earned all five Elite phase badges for Japan.', 'country', 'elite', NULL, NULL, 'JP', NULL),
('mc-fr-ph1-p1', 'Adaptive Linguistics — The Foyer', 'Mastered Adaptive Linguistics in Phase 1 (The Foyer) for France.', 'pillar', 'middle_class', 'P1', 1, 'FR', NULL),
('mc-fr-ph1-p2', 'Professional Branding — The Foyer', 'Mastered Professional Branding in Phase 1 (The Foyer) for France.', 'pillar', 'middle_class', 'P2', 1, 'FR', NULL),
('mc-fr-ph1-p3', 'Social Navigation — The Foyer', 'Mastered Social Navigation in Phase 1 (The Foyer) for France.', 'pillar', 'middle_class', 'P3', 1, 'FR', NULL),
('mc-fr-ph1-phase', 'The Foyer — France', 'Completed all three pillars of Phase 1 (The Foyer) for France.', 'phase', 'middle_class', NULL, 1, 'FR', NULL),
('elite-fr-ph1-phase', 'The Foyer (Elite) — France', 'Mastered the Elite track of Phase 1 (The Foyer) for France.', 'phase', 'elite', NULL, 1, 'FR', NULL),
('mc-fr-ph2-p1', 'Adaptive Linguistics — The Salon', 'Mastered Adaptive Linguistics in Phase 2 (The Salon) for France.', 'pillar', 'middle_class', 'P1', 2, 'FR', NULL),
('mc-fr-ph2-p2', 'Professional Branding — The Salon', 'Mastered Professional Branding in Phase 2 (The Salon) for France.', 'pillar', 'middle_class', 'P2', 2, 'FR', NULL),
('mc-fr-ph2-p3', 'Social Navigation — The Salon', 'Mastered Social Navigation in Phase 2 (The Salon) for France.', 'pillar', 'middle_class', 'P3', 2, 'FR', NULL),
('mc-fr-ph2-phase', 'The Salon — France', 'Completed all three pillars of Phase 2 (The Salon) for France.', 'phase', 'middle_class', NULL, 2, 'FR', NULL),
('elite-fr-ph2-phase', 'The Salon (Elite) — France', 'Mastered the Elite track of Phase 2 (The Salon) for France.', 'phase', 'elite', NULL, 2, 'FR', NULL),
('mc-fr-ph3-p1', 'Adaptive Linguistics — The Arena', 'Mastered Adaptive Linguistics in Phase 3 (The Arena) for France.', 'pillar', 'middle_class', 'P1', 3, 'FR', NULL),
('mc-fr-ph3-p2', 'Professional Branding — The Arena', 'Mastered Professional Branding in Phase 3 (The Arena) for France.', 'pillar', 'middle_class', 'P2', 3, 'FR', NULL),
('mc-fr-ph3-p3', 'Social Navigation — The Arena', 'Mastered Social Navigation in Phase 3 (The Arena) for France.', 'pillar', 'middle_class', 'P3', 3, 'FR', NULL),
('mc-fr-ph3-phase', 'The Arena — France', 'Completed all three pillars of Phase 3 (The Arena) for France.', 'phase', 'middle_class', NULL, 3, 'FR', NULL),
('elite-fr-ph3-phase', 'The Arena (Elite) — France', 'Mastered the Elite track of Phase 3 (The Arena) for France.', 'phase', 'elite', NULL, 3, 'FR', NULL),
('mc-fr-ph4-p1', 'Adaptive Linguistics — The Sanctum', 'Mastered Adaptive Linguistics in Phase 4 (The Sanctum) for France.', 'pillar', 'middle_class', 'P1', 4, 'FR', NULL),
('mc-fr-ph4-p2', 'Professional Branding — The Sanctum', 'Mastered Professional Branding in Phase 4 (The Sanctum) for France.', 'pillar', 'middle_class', 'P2', 4, 'FR', NULL),
('mc-fr-ph4-p3', 'Social Navigation — The Sanctum', 'Mastered Social Navigation in Phase 4 (The Sanctum) for France.', 'pillar', 'middle_class', 'P3', 4, 'FR', NULL),
('mc-fr-ph4-phase', 'The Sanctum — France', 'Completed all three pillars of Phase 4 (The Sanctum) for France.', 'phase', 'middle_class', NULL, 4, 'FR', NULL),
('elite-fr-ph4-phase', 'The Sanctum (Elite) — France', 'Mastered the Elite track of Phase 4 (The Sanctum) for France.', 'phase', 'elite', NULL, 4, 'FR', NULL),
('mc-fr-ph5-p1', 'Adaptive Linguistics — The Summit', 'Mastered Adaptive Linguistics in Phase 5 (The Summit) for France.', 'pillar', 'middle_class', 'P1', 5, 'FR', NULL),
('mc-fr-ph5-p2', 'Professional Branding — The Summit', 'Mastered Professional Branding in Phase 5 (The Summit) for France.', 'pillar', 'middle_class', 'P2', 5, 'FR', NULL),
('mc-fr-ph5-p3', 'Social Navigation — The Summit', 'Mastered Social Navigation in Phase 5 (The Summit) for France.', 'pillar', 'middle_class', 'P3', 5, 'FR', NULL),
('mc-fr-ph5-phase', 'The Summit — France', 'Completed all three pillars of Phase 5 (The Summit) for France.', 'phase', 'middle_class', NULL, 5, 'FR', NULL),
('elite-fr-ph5-phase', 'The Summit (Elite) — France', 'Mastered the Elite track of Phase 5 (The Summit) for France.', 'phase', 'elite', NULL, 5, 'FR', NULL),
('mc-fr-country', 'Gecertificeerd voor France — Middenklasse', 'Earned all five Middle Class phase badges for France.', 'country', 'middle_class', NULL, NULL, 'FR', NULL),
('elite-fr-country', 'Gecertificeerd voor France — Elite', 'Earned all five Elite phase badges for France.', 'country', 'elite', NULL, NULL, 'FR', NULL),
('mc-de-ph1-p1', 'Adaptive Linguistics — The Foyer', 'Mastered Adaptive Linguistics in Phase 1 (The Foyer) for Germany.', 'pillar', 'middle_class', 'P1', 1, 'DE', NULL),
('mc-de-ph1-p2', 'Professional Branding — The Foyer', 'Mastered Professional Branding in Phase 1 (The Foyer) for Germany.', 'pillar', 'middle_class', 'P2', 1, 'DE', NULL),
('mc-de-ph1-p3', 'Social Navigation — The Foyer', 'Mastered Social Navigation in Phase 1 (The Foyer) for Germany.', 'pillar', 'middle_class', 'P3', 1, 'DE', NULL),
('mc-de-ph1-phase', 'The Foyer — Germany', 'Completed all three pillars of Phase 1 (The Foyer) for Germany.', 'phase', 'middle_class', NULL, 1, 'DE', NULL),
('elite-de-ph1-phase', 'The Foyer (Elite) — Germany', 'Mastered the Elite track of Phase 1 (The Foyer) for Germany.', 'phase', 'elite', NULL, 1, 'DE', NULL),
('mc-de-ph2-p1', 'Adaptive Linguistics — The Salon', 'Mastered Adaptive Linguistics in Phase 2 (The Salon) for Germany.', 'pillar', 'middle_class', 'P1', 2, 'DE', NULL),
('mc-de-ph2-p2', 'Professional Branding — The Salon', 'Mastered Professional Branding in Phase 2 (The Salon) for Germany.', 'pillar', 'middle_class', 'P2', 2, 'DE', NULL),
('mc-de-ph2-p3', 'Social Navigation — The Salon', 'Mastered Social Navigation in Phase 2 (The Salon) for Germany.', 'pillar', 'middle_class', 'P3', 2, 'DE', NULL),
('mc-de-ph2-phase', 'The Salon — Germany', 'Completed all three pillars of Phase 2 (The Salon) for Germany.', 'phase', 'middle_class', NULL, 2, 'DE', NULL),
('elite-de-ph2-phase', 'The Salon (Elite) — Germany', 'Mastered the Elite track of Phase 2 (The Salon) for Germany.', 'phase', 'elite', NULL, 2, 'DE', NULL),
('mc-de-ph3-p1', 'Adaptive Linguistics — The Arena', 'Mastered Adaptive Linguistics in Phase 3 (The Arena) for Germany.', 'pillar', 'middle_class', 'P1', 3, 'DE', NULL),
('mc-de-ph3-p2', 'Professional Branding — The Arena', 'Mastered Professional Branding in Phase 3 (The Arena) for Germany.', 'pillar', 'middle_class', 'P2', 3, 'DE', NULL),
('mc-de-ph3-p3', 'Social Navigation — The Arena', 'Mastered Social Navigation in Phase 3 (The Arena) for Germany.', 'pillar', 'middle_class', 'P3', 3, 'DE', NULL),
('mc-de-ph3-phase', 'The Arena — Germany', 'Completed all three pillars of Phase 3 (The Arena) for Germany.', 'phase', 'middle_class', NULL, 3, 'DE', NULL),
('elite-de-ph3-phase', 'The Arena (Elite) — Germany', 'Mastered the Elite track of Phase 3 (The Arena) for Germany.', 'phase', 'elite', NULL, 3, 'DE', NULL),
('mc-de-ph4-p1', 'Adaptive Linguistics — The Sanctum', 'Mastered Adaptive Linguistics in Phase 4 (The Sanctum) for Germany.', 'pillar', 'middle_class', 'P1', 4, 'DE', NULL),
('mc-de-ph4-p2', 'Professional Branding — The Sanctum', 'Mastered Professional Branding in Phase 4 (The Sanctum) for Germany.', 'pillar', 'middle_class', 'P2', 4, 'DE', NULL),
('mc-de-ph4-p3', 'Social Navigation — The Sanctum', 'Mastered Social Navigation in Phase 4 (The Sanctum) for Germany.', 'pillar', 'middle_class', 'P3', 4, 'DE', NULL),
('mc-de-ph4-phase', 'The Sanctum — Germany', 'Completed all three pillars of Phase 4 (The Sanctum) for Germany.', 'phase', 'middle_class', NULL, 4, 'DE', NULL),
('elite-de-ph4-phase', 'The Sanctum (Elite) — Germany', 'Mastered the Elite track of Phase 4 (The Sanctum) for Germany.', 'phase', 'elite', NULL, 4, 'DE', NULL),
('mc-de-ph5-p1', 'Adaptive Linguistics — The Summit', 'Mastered Adaptive Linguistics in Phase 5 (The Summit) for Germany.', 'pillar', 'middle_class', 'P1', 5, 'DE', NULL),
('mc-de-ph5-p2', 'Professional Branding — The Summit', 'Mastered Professional Branding in Phase 5 (The Summit) for Germany.', 'pillar', 'middle_class', 'P2', 5, 'DE', NULL),
('mc-de-ph5-p3', 'Social Navigation — The Summit', 'Mastered Social Navigation in Phase 5 (The Summit) for Germany.', 'pillar', 'middle_class', 'P3', 5, 'DE', NULL),
('mc-de-ph5-phase', 'The Summit — Germany', 'Completed all three pillars of Phase 5 (The Summit) for Germany.', 'phase', 'middle_class', NULL, 5, 'DE', NULL),
('elite-de-ph5-phase', 'The Summit (Elite) — Germany', 'Mastered the Elite track of Phase 5 (The Summit) for Germany.', 'phase', 'elite', NULL, 5, 'DE', NULL),
('mc-de-country', 'Gecertificeerd voor Germany — Middenklasse', 'Earned all five Middle Class phase badges for Germany.', 'country', 'middle_class', NULL, NULL, 'DE', NULL),
('elite-de-country', 'Gecertificeerd voor Germany — Elite', 'Earned all five Elite phase badges for Germany.', 'country', 'elite', NULL, NULL, 'DE', NULL),
('mc-nl-ph1-p1', 'Adaptive Linguistics — The Foyer', 'Mastered Adaptive Linguistics in Phase 1 (The Foyer) for Netherlands.', 'pillar', 'middle_class', 'P1', 1, 'NL', NULL),
('mc-nl-ph1-p2', 'Professional Branding — The Foyer', 'Mastered Professional Branding in Phase 1 (The Foyer) for Netherlands.', 'pillar', 'middle_class', 'P2', 1, 'NL', NULL),
('mc-nl-ph1-p3', 'Social Navigation — The Foyer', 'Mastered Social Navigation in Phase 1 (The Foyer) for Netherlands.', 'pillar', 'middle_class', 'P3', 1, 'NL', NULL),
('mc-nl-ph1-phase', 'The Foyer — Netherlands', 'Completed all three pillars of Phase 1 (The Foyer) for Netherlands.', 'phase', 'middle_class', NULL, 1, 'NL', NULL),
('elite-nl-ph1-phase', 'The Foyer (Elite) — Netherlands', 'Mastered the Elite track of Phase 1 (The Foyer) for Netherlands.', 'phase', 'elite', NULL, 1, 'NL', NULL),
('mc-nl-ph2-p1', 'Adaptive Linguistics — The Salon', 'Mastered Adaptive Linguistics in Phase 2 (The Salon) for Netherlands.', 'pillar', 'middle_class', 'P1', 2, 'NL', NULL),
('mc-nl-ph2-p2', 'Professional Branding — The Salon', 'Mastered Professional Branding in Phase 2 (The Salon) for Netherlands.', 'pillar', 'middle_class', 'P2', 2, 'NL', NULL),
('mc-nl-ph2-p3', 'Social Navigation — The Salon', 'Mastered Social Navigation in Phase 2 (The Salon) for Netherlands.', 'pillar', 'middle_class', 'P3', 2, 'NL', NULL),
('mc-nl-ph2-phase', 'The Salon — Netherlands', 'Completed all three pillars of Phase 2 (The Salon) for Netherlands.', 'phase', 'middle_class', NULL, 2, 'NL', NULL),
('elite-nl-ph2-phase', 'The Salon (Elite) — Netherlands', 'Mastered the Elite track of Phase 2 (The Salon) for Netherlands.', 'phase', 'elite', NULL, 2, 'NL', NULL),
('mc-nl-ph3-p1', 'Adaptive Linguistics — The Arena', 'Mastered Adaptive Linguistics in Phase 3 (The Arena) for Netherlands.', 'pillar', 'middle_class', 'P1', 3, 'NL', NULL),
('mc-nl-ph3-p2', 'Professional Branding — The Arena', 'Mastered Professional Branding in Phase 3 (The Arena) for Netherlands.', 'pillar', 'middle_class', 'P2', 3, 'NL', NULL),
('mc-nl-ph3-p3', 'Social Navigation — The Arena', 'Mastered Social Navigation in Phase 3 (The Arena) for Netherlands.', 'pillar', 'middle_class', 'P3', 3, 'NL', NULL),
('mc-nl-ph3-phase', 'The Arena — Netherlands', 'Completed all three pillars of Phase 3 (The Arena) for Netherlands.', 'phase', 'middle_class', NULL, 3, 'NL', NULL),
('elite-nl-ph3-phase', 'The Arena (Elite) — Netherlands', 'Mastered the Elite track of Phase 3 (The Arena) for Netherlands.', 'phase', 'elite', NULL, 3, 'NL', NULL),
('mc-nl-ph4-p1', 'Adaptive Linguistics — The Sanctum', 'Mastered Adaptive Linguistics in Phase 4 (The Sanctum) for Netherlands.', 'pillar', 'middle_class', 'P1', 4, 'NL', NULL),
('mc-nl-ph4-p2', 'Professional Branding — The Sanctum', 'Mastered Professional Branding in Phase 4 (The Sanctum) for Netherlands.', 'pillar', 'middle_class', 'P2', 4, 'NL', NULL),
('mc-nl-ph4-p3', 'Social Navigation — The Sanctum', 'Mastered Social Navigation in Phase 4 (The Sanctum) for Netherlands.', 'pillar', 'middle_class', 'P3', 4, 'NL', NULL),
('mc-nl-ph4-phase', 'The Sanctum — Netherlands', 'Completed all three pillars of Phase 4 (The Sanctum) for Netherlands.', 'phase', 'middle_class', NULL, 4, 'NL', NULL),
('elite-nl-ph4-phase', 'The Sanctum (Elite) — Netherlands', 'Mastered the Elite track of Phase 4 (The Sanctum) for Netherlands.', 'phase', 'elite', NULL, 4, 'NL', NULL),
('mc-nl-ph5-p1', 'Adaptive Linguistics — The Summit', 'Mastered Adaptive Linguistics in Phase 5 (The Summit) for Netherlands.', 'pillar', 'middle_class', 'P1', 5, 'NL', NULL),
('mc-nl-ph5-p2', 'Professional Branding — The Summit', 'Mastered Professional Branding in Phase 5 (The Summit) for Netherlands.', 'pillar', 'middle_class', 'P2', 5, 'NL', NULL),
('mc-nl-ph5-p3', 'Social Navigation — The Summit', 'Mastered Social Navigation in Phase 5 (The Summit) for Netherlands.', 'pillar', 'middle_class', 'P3', 5, 'NL', NULL),
('mc-nl-ph5-phase', 'The Summit — Netherlands', 'Completed all three pillars of Phase 5 (The Summit) for Netherlands.', 'phase', 'middle_class', NULL, 5, 'NL', NULL),
('elite-nl-ph5-phase', 'The Summit (Elite) — Netherlands', 'Mastered the Elite track of Phase 5 (The Summit) for Netherlands.', 'phase', 'elite', NULL, 5, 'NL', NULL),
('mc-nl-country', 'Gecertificeerd voor Netherlands — Middenklasse', 'Earned all five Middle Class phase badges for Netherlands.', 'country', 'middle_class', NULL, NULL, 'NL', NULL),
('elite-nl-country', 'Gecertificeerd voor Netherlands — Elite', 'Earned all five Elite phase badges for Netherlands.', 'country', 'elite', NULL, NULL, 'NL', NULL),
('mc-au-ph1-p1', 'Adaptive Linguistics — The Foyer', 'Mastered Adaptive Linguistics in Phase 1 (The Foyer) for Australia.', 'pillar', 'middle_class', 'P1', 1, 'AU', NULL),
('mc-au-ph1-p2', 'Professional Branding — The Foyer', 'Mastered Professional Branding in Phase 1 (The Foyer) for Australia.', 'pillar', 'middle_class', 'P2', 1, 'AU', NULL),
('mc-au-ph1-p3', 'Social Navigation — The Foyer', 'Mastered Social Navigation in Phase 1 (The Foyer) for Australia.', 'pillar', 'middle_class', 'P3', 1, 'AU', NULL),
('mc-au-ph1-phase', 'The Foyer — Australia', 'Completed all three pillars of Phase 1 (The Foyer) for Australia.', 'phase', 'middle_class', NULL, 1, 'AU', NULL),
('elite-au-ph1-phase', 'The Foyer (Elite) — Australia', 'Mastered the Elite track of Phase 1 (The Foyer) for Australia.', 'phase', 'elite', NULL, 1, 'AU', NULL),
('mc-au-ph2-p1', 'Adaptive Linguistics — The Salon', 'Mastered Adaptive Linguistics in Phase 2 (The Salon) for Australia.', 'pillar', 'middle_class', 'P1', 2, 'AU', NULL),
('mc-au-ph2-p2', 'Professional Branding — The Salon', 'Mastered Professional Branding in Phase 2 (The Salon) for Australia.', 'pillar', 'middle_class', 'P2', 2, 'AU', NULL),
('mc-au-ph2-p3', 'Social Navigation — The Salon', 'Mastered Social Navigation in Phase 2 (The Salon) for Australia.', 'pillar', 'middle_class', 'P3', 2, 'AU', NULL),
('mc-au-ph2-phase', 'The Salon — Australia', 'Completed all three pillars of Phase 2 (The Salon) for Australia.', 'phase', 'middle_class', NULL, 2, 'AU', NULL),
('elite-au-ph2-phase', 'The Salon (Elite) — Australia', 'Mastered the Elite track of Phase 2 (The Salon) for Australia.', 'phase', 'elite', NULL, 2, 'AU', NULL),
('mc-au-ph3-p1', 'Adaptive Linguistics — The Arena', 'Mastered Adaptive Linguistics in Phase 3 (The Arena) for Australia.', 'pillar', 'middle_class', 'P1', 3, 'AU', NULL),
('mc-au-ph3-p2', 'Professional Branding — The Arena', 'Mastered Professional Branding in Phase 3 (The Arena) for Australia.', 'pillar', 'middle_class', 'P2', 3, 'AU', NULL),
('mc-au-ph3-p3', 'Social Navigation — The Arena', 'Mastered Social Navigation in Phase 3 (The Arena) for Australia.', 'pillar', 'middle_class', 'P3', 3, 'AU', NULL),
('mc-au-ph3-phase', 'The Arena — Australia', 'Completed all three pillars of Phase 3 (The Arena) for Australia.', 'phase', 'middle_class', NULL, 3, 'AU', NULL),
('elite-au-ph3-phase', 'The Arena (Elite) — Australia', 'Mastered the Elite track of Phase 3 (The Arena) for Australia.', 'phase', 'elite', NULL, 3, 'AU', NULL),
('mc-au-ph4-p1', 'Adaptive Linguistics — The Sanctum', 'Mastered Adaptive Linguistics in Phase 4 (The Sanctum) for Australia.', 'pillar', 'middle_class', 'P1', 4, 'AU', NULL),
('mc-au-ph4-p2', 'Professional Branding — The Sanctum', 'Mastered Professional Branding in Phase 4 (The Sanctum) for Australia.', 'pillar', 'middle_class', 'P2', 4, 'AU', NULL),
('mc-au-ph4-p3', 'Social Navigation — The Sanctum', 'Mastered Social Navigation in Phase 4 (The Sanctum) for Australia.', 'pillar', 'middle_class', 'P3', 4, 'AU', NULL),
('mc-au-ph4-phase', 'The Sanctum — Australia', 'Completed all three pillars of Phase 4 (The Sanctum) for Australia.', 'phase', 'middle_class', NULL, 4, 'AU', NULL),
('elite-au-ph4-phase', 'The Sanctum (Elite) — Australia', 'Mastered the Elite track of Phase 4 (The Sanctum) for Australia.', 'phase', 'elite', NULL, 4, 'AU', NULL),
('mc-au-ph5-p1', 'Adaptive Linguistics — The Summit', 'Mastered Adaptive Linguistics in Phase 5 (The Summit) for Australia.', 'pillar', 'middle_class', 'P1', 5, 'AU', NULL),
('mc-au-ph5-p2', 'Professional Branding — The Summit', 'Mastered Professional Branding in Phase 5 (The Summit) for Australia.', 'pillar', 'middle_class', 'P2', 5, 'AU', NULL),
('mc-au-ph5-p3', 'Social Navigation — The Summit', 'Mastered Social Navigation in Phase 5 (The Summit) for Australia.', 'pillar', 'middle_class', 'P3', 5, 'AU', NULL),
('mc-au-ph5-phase', 'The Summit — Australia', 'Completed all three pillars of Phase 5 (The Summit) for Australia.', 'phase', 'middle_class', NULL, 5, 'AU', NULL),
('elite-au-ph5-phase', 'The Summit (Elite) — Australia', 'Mastered the Elite track of Phase 5 (The Summit) for Australia.', 'phase', 'elite', NULL, 5, 'AU', NULL),
('mc-au-country', 'Gecertificeerd voor Australia — Middenklasse', 'Earned all five Middle Class phase badges for Australia.', 'country', 'middle_class', NULL, NULL, 'AU', NULL),
('elite-au-country', 'Gecertificeerd voor Australia — Elite', 'Earned all five Elite phase badges for Australia.', 'country', 'elite', NULL, NULL, 'AU', NULL),
('mc-ca-ph1-p1', 'Adaptive Linguistics — The Foyer', 'Mastered Adaptive Linguistics in Phase 1 (The Foyer) for Canada.', 'pillar', 'middle_class', 'P1', 1, 'CA', NULL),
('mc-ca-ph1-p2', 'Professional Branding — The Foyer', 'Mastered Professional Branding in Phase 1 (The Foyer) for Canada.', 'pillar', 'middle_class', 'P2', 1, 'CA', NULL),
('mc-ca-ph1-p3', 'Social Navigation — The Foyer', 'Mastered Social Navigation in Phase 1 (The Foyer) for Canada.', 'pillar', 'middle_class', 'P3', 1, 'CA', NULL),
('mc-ca-ph1-phase', 'The Foyer — Canada', 'Completed all three pillars of Phase 1 (The Foyer) for Canada.', 'phase', 'middle_class', NULL, 1, 'CA', NULL),
('elite-ca-ph1-phase', 'The Foyer (Elite) — Canada', 'Mastered the Elite track of Phase 1 (The Foyer) for Canada.', 'phase', 'elite', NULL, 1, 'CA', NULL),
('mc-ca-ph2-p1', 'Adaptive Linguistics — The Salon', 'Mastered Adaptive Linguistics in Phase 2 (The Salon) for Canada.', 'pillar', 'middle_class', 'P1', 2, 'CA', NULL),
('mc-ca-ph2-p2', 'Professional Branding — The Salon', 'Mastered Professional Branding in Phase 2 (The Salon) for Canada.', 'pillar', 'middle_class', 'P2', 2, 'CA', NULL),
('mc-ca-ph2-p3', 'Social Navigation — The Salon', 'Mastered Social Navigation in Phase 2 (The Salon) for Canada.', 'pillar', 'middle_class', 'P3', 2, 'CA', NULL),
('mc-ca-ph2-phase', 'The Salon — Canada', 'Completed all three pillars of Phase 2 (The Salon) for Canada.', 'phase', 'middle_class', NULL, 2, 'CA', NULL),
('elite-ca-ph2-phase', 'The Salon (Elite) — Canada', 'Mastered the Elite track of Phase 2 (The Salon) for Canada.', 'phase', 'elite', NULL, 2, 'CA', NULL),
('mc-ca-ph3-p1', 'Adaptive Linguistics — The Arena', 'Mastered Adaptive Linguistics in Phase 3 (The Arena) for Canada.', 'pillar', 'middle_class', 'P1', 3, 'CA', NULL),
('mc-ca-ph3-p2', 'Professional Branding — The Arena', 'Mastered Professional Branding in Phase 3 (The Arena) for Canada.', 'pillar', 'middle_class', 'P2', 3, 'CA', NULL),
('mc-ca-ph3-p3', 'Social Navigation — The Arena', 'Mastered Social Navigation in Phase 3 (The Arena) for Canada.', 'pillar', 'middle_class', 'P3', 3, 'CA', NULL),
('mc-ca-ph3-phase', 'The Arena — Canada', 'Completed all three pillars of Phase 3 (The Arena) for Canada.', 'phase', 'middle_class', NULL, 3, 'CA', NULL),
('elite-ca-ph3-phase', 'The Arena (Elite) — Canada', 'Mastered the Elite track of Phase 3 (The Arena) for Canada.', 'phase', 'elite', NULL, 3, 'CA', NULL),
('mc-ca-ph4-p1', 'Adaptive Linguistics — The Sanctum', 'Mastered Adaptive Linguistics in Phase 4 (The Sanctum) for Canada.', 'pillar', 'middle_class', 'P1', 4, 'CA', NULL),
('mc-ca-ph4-p2', 'Professional Branding — The Sanctum', 'Mastered Professional Branding in Phase 4 (The Sanctum) for Canada.', 'pillar', 'middle_class', 'P2', 4, 'CA', NULL),
('mc-ca-ph4-p3', 'Social Navigation — The Sanctum', 'Mastered Social Navigation in Phase 4 (The Sanctum) for Canada.', 'pillar', 'middle_class', 'P3', 4, 'CA', NULL),
('mc-ca-ph4-phase', 'The Sanctum — Canada', 'Completed all three pillars of Phase 4 (The Sanctum) for Canada.', 'phase', 'middle_class', NULL, 4, 'CA', NULL),
('elite-ca-ph4-phase', 'The Sanctum (Elite) — Canada', 'Mastered the Elite track of Phase 4 (The Sanctum) for Canada.', 'phase', 'elite', NULL, 4, 'CA', NULL),
('mc-ca-ph5-p1', 'Adaptive Linguistics — The Summit', 'Mastered Adaptive Linguistics in Phase 5 (The Summit) for Canada.', 'pillar', 'middle_class', 'P1', 5, 'CA', NULL),
('mc-ca-ph5-p2', 'Professional Branding — The Summit', 'Mastered Professional Branding in Phase 5 (The Summit) for Canada.', 'pillar', 'middle_class', 'P2', 5, 'CA', NULL),
('mc-ca-ph5-p3', 'Social Navigation — The Summit', 'Mastered Social Navigation in Phase 5 (The Summit) for Canada.', 'pillar', 'middle_class', 'P3', 5, 'CA', NULL),
('mc-ca-ph5-phase', 'The Summit — Canada', 'Completed all three pillars of Phase 5 (The Summit) for Canada.', 'phase', 'middle_class', NULL, 5, 'CA', NULL),
('elite-ca-ph5-phase', 'The Summit (Elite) — Canada', 'Mastered the Elite track of Phase 5 (The Summit) for Canada.', 'phase', 'elite', NULL, 5, 'CA', NULL),
('mc-ca-country', 'Gecertificeerd voor Canada — Middenklasse', 'Earned all five Middle Class phase badges for Canada.', 'country', 'middle_class', NULL, NULL, 'CA', NULL),
('elite-ca-country', 'Gecertificeerd voor Canada — Elite', 'Earned all five Elite phase badges for Canada.', 'country', 'elite', NULL, NULL, 'CA', NULL),
('mc-it-ph1-p1', 'Adaptive Linguistics — The Foyer', 'Mastered Adaptive Linguistics in Phase 1 (The Foyer) for Italy.', 'pillar', 'middle_class', 'P1', 1, 'IT', NULL),
('mc-it-ph1-p2', 'Professional Branding — The Foyer', 'Mastered Professional Branding in Phase 1 (The Foyer) for Italy.', 'pillar', 'middle_class', 'P2', 1, 'IT', NULL),
('mc-it-ph1-p3', 'Social Navigation — The Foyer', 'Mastered Social Navigation in Phase 1 (The Foyer) for Italy.', 'pillar', 'middle_class', 'P3', 1, 'IT', NULL),
('mc-it-ph1-phase', 'The Foyer — Italy', 'Completed all three pillars of Phase 1 (The Foyer) for Italy.', 'phase', 'middle_class', NULL, 1, 'IT', NULL),
('elite-it-ph1-phase', 'The Foyer (Elite) — Italy', 'Mastered the Elite track of Phase 1 (The Foyer) for Italy.', 'phase', 'elite', NULL, 1, 'IT', NULL),
('mc-it-ph2-p1', 'Adaptive Linguistics — The Salon', 'Mastered Adaptive Linguistics in Phase 2 (The Salon) for Italy.', 'pillar', 'middle_class', 'P1', 2, 'IT', NULL),
('mc-it-ph2-p2', 'Professional Branding — The Salon', 'Mastered Professional Branding in Phase 2 (The Salon) for Italy.', 'pillar', 'middle_class', 'P2', 2, 'IT', NULL),
('mc-it-ph2-p3', 'Social Navigation — The Salon', 'Mastered Social Navigation in Phase 2 (The Salon) for Italy.', 'pillar', 'middle_class', 'P3', 2, 'IT', NULL),
('mc-it-ph2-phase', 'The Salon — Italy', 'Completed all three pillars of Phase 2 (The Salon) for Italy.', 'phase', 'middle_class', NULL, 2, 'IT', NULL),
('elite-it-ph2-phase', 'The Salon (Elite) — Italy', 'Mastered the Elite track of Phase 2 (The Salon) for Italy.', 'phase', 'elite', NULL, 2, 'IT', NULL),
('mc-it-ph3-p1', 'Adaptive Linguistics — The Arena', 'Mastered Adaptive Linguistics in Phase 3 (The Arena) for Italy.', 'pillar', 'middle_class', 'P1', 3, 'IT', NULL),
('mc-it-ph3-p2', 'Professional Branding — The Arena', 'Mastered Professional Branding in Phase 3 (The Arena) for Italy.', 'pillar', 'middle_class', 'P2', 3, 'IT', NULL),
('mc-it-ph3-p3', 'Social Navigation — The Arena', 'Mastered Social Navigation in Phase 3 (The Arena) for Italy.', 'pillar', 'middle_class', 'P3', 3, 'IT', NULL),
('mc-it-ph3-phase', 'The Arena — Italy', 'Completed all three pillars of Phase 3 (The Arena) for Italy.', 'phase', 'middle_class', NULL, 3, 'IT', NULL),
('elite-it-ph3-phase', 'The Arena (Elite) — Italy', 'Mastered the Elite track of Phase 3 (The Arena) for Italy.', 'phase', 'elite', NULL, 3, 'IT', NULL),
('mc-it-ph4-p1', 'Adaptive Linguistics — The Sanctum', 'Mastered Adaptive Linguistics in Phase 4 (The Sanctum) for Italy.', 'pillar', 'middle_class', 'P1', 4, 'IT', NULL),
('mc-it-ph4-p2', 'Professional Branding — The Sanctum', 'Mastered Professional Branding in Phase 4 (The Sanctum) for Italy.', 'pillar', 'middle_class', 'P2', 4, 'IT', NULL),
('mc-it-ph4-p3', 'Social Navigation — The Sanctum', 'Mastered Social Navigation in Phase 4 (The Sanctum) for Italy.', 'pillar', 'middle_class', 'P3', 4, 'IT', NULL),
('mc-it-ph4-phase', 'The Sanctum — Italy', 'Completed all three pillars of Phase 4 (The Sanctum) for Italy.', 'phase', 'middle_class', NULL, 4, 'IT', NULL),
('elite-it-ph4-phase', 'The Sanctum (Elite) — Italy', 'Mastered the Elite track of Phase 4 (The Sanctum) for Italy.', 'phase', 'elite', NULL, 4, 'IT', NULL),
('mc-it-ph5-p1', 'Adaptive Linguistics — The Summit', 'Mastered Adaptive Linguistics in Phase 5 (The Summit) for Italy.', 'pillar', 'middle_class', 'P1', 5, 'IT', NULL),
('mc-it-ph5-p2', 'Professional Branding — The Summit', 'Mastered Professional Branding in Phase 5 (The Summit) for Italy.', 'pillar', 'middle_class', 'P2', 5, 'IT', NULL),
('mc-it-ph5-p3', 'Social Navigation — The Summit', 'Mastered Social Navigation in Phase 5 (The Summit) for Italy.', 'pillar', 'middle_class', 'P3', 5, 'IT', NULL),
('mc-it-ph5-phase', 'The Summit — Italy', 'Completed all three pillars of Phase 5 (The Summit) for Italy.', 'phase', 'middle_class', NULL, 5, 'IT', NULL),
('elite-it-ph5-phase', 'The Summit (Elite) — Italy', 'Mastered the Elite track of Phase 5 (The Summit) for Italy.', 'phase', 'elite', NULL, 5, 'IT', NULL),
('mc-it-country', 'Gecertificeerd voor Italy — Middenklasse', 'Earned all five Middle Class phase badges for Italy.', 'country', 'middle_class', NULL, NULL, 'IT', NULL),
('elite-it-country', 'Gecertificeerd voor Italy — Elite', 'Earned all five Elite phase badges for Italy.', 'country', 'elite', NULL, NULL, 'IT', NULL),
('mc-in-ph1-p1', 'Adaptive Linguistics — The Foyer', 'Mastered Adaptive Linguistics in Phase 1 (The Foyer) for India.', 'pillar', 'middle_class', 'P1', 1, 'IN', NULL),
('mc-in-ph1-p2', 'Professional Branding — The Foyer', 'Mastered Professional Branding in Phase 1 (The Foyer) for India.', 'pillar', 'middle_class', 'P2', 1, 'IN', NULL),
('mc-in-ph1-p3', 'Social Navigation — The Foyer', 'Mastered Social Navigation in Phase 1 (The Foyer) for India.', 'pillar', 'middle_class', 'P3', 1, 'IN', NULL),
('mc-in-ph1-phase', 'The Foyer — India', 'Completed all three pillars of Phase 1 (The Foyer) for India.', 'phase', 'middle_class', NULL, 1, 'IN', NULL),
('elite-in-ph1-phase', 'The Foyer (Elite) — India', 'Mastered the Elite track of Phase 1 (The Foyer) for India.', 'phase', 'elite', NULL, 1, 'IN', NULL),
('mc-in-ph2-p1', 'Adaptive Linguistics — The Salon', 'Mastered Adaptive Linguistics in Phase 2 (The Salon) for India.', 'pillar', 'middle_class', 'P1', 2, 'IN', NULL),
('mc-in-ph2-p2', 'Professional Branding — The Salon', 'Mastered Professional Branding in Phase 2 (The Salon) for India.', 'pillar', 'middle_class', 'P2', 2, 'IN', NULL),
('mc-in-ph2-p3', 'Social Navigation — The Salon', 'Mastered Social Navigation in Phase 2 (The Salon) for India.', 'pillar', 'middle_class', 'P3', 2, 'IN', NULL),
('mc-in-ph2-phase', 'The Salon — India', 'Completed all three pillars of Phase 2 (The Salon) for India.', 'phase', 'middle_class', NULL, 2, 'IN', NULL),
('elite-in-ph2-phase', 'The Salon (Elite) — India', 'Mastered the Elite track of Phase 2 (The Salon) for India.', 'phase', 'elite', NULL, 2, 'IN', NULL),
('mc-in-ph3-p1', 'Adaptive Linguistics — The Arena', 'Mastered Adaptive Linguistics in Phase 3 (The Arena) for India.', 'pillar', 'middle_class', 'P1', 3, 'IN', NULL),
('mc-in-ph3-p2', 'Professional Branding — The Arena', 'Mastered Professional Branding in Phase 3 (The Arena) for India.', 'pillar', 'middle_class', 'P2', 3, 'IN', NULL),
('mc-in-ph3-p3', 'Social Navigation — The Arena', 'Mastered Social Navigation in Phase 3 (The Arena) for India.', 'pillar', 'middle_class', 'P3', 3, 'IN', NULL),
('mc-in-ph3-phase', 'The Arena — India', 'Completed all three pillars of Phase 3 (The Arena) for India.', 'phase', 'middle_class', NULL, 3, 'IN', NULL),
('elite-in-ph3-phase', 'The Arena (Elite) — India', 'Mastered the Elite track of Phase 3 (The Arena) for India.', 'phase', 'elite', NULL, 3, 'IN', NULL),
('mc-in-ph4-p1', 'Adaptive Linguistics — The Sanctum', 'Mastered Adaptive Linguistics in Phase 4 (The Sanctum) for India.', 'pillar', 'middle_class', 'P1', 4, 'IN', NULL),
('mc-in-ph4-p2', 'Professional Branding — The Sanctum', 'Mastered Professional Branding in Phase 4 (The Sanctum) for India.', 'pillar', 'middle_class', 'P2', 4, 'IN', NULL),
('mc-in-ph4-p3', 'Social Navigation — The Sanctum', 'Mastered Social Navigation in Phase 4 (The Sanctum) for India.', 'pillar', 'middle_class', 'P3', 4, 'IN', NULL),
('mc-in-ph4-phase', 'The Sanctum — India', 'Completed all three pillars of Phase 4 (The Sanctum) for India.', 'phase', 'middle_class', NULL, 4, 'IN', NULL),
('elite-in-ph4-phase', 'The Sanctum (Elite) — India', 'Mastered the Elite track of Phase 4 (The Sanctum) for India.', 'phase', 'elite', NULL, 4, 'IN', NULL),
('mc-in-ph5-p1', 'Adaptive Linguistics — The Summit', 'Mastered Adaptive Linguistics in Phase 5 (The Summit) for India.', 'pillar', 'middle_class', 'P1', 5, 'IN', NULL),
('mc-in-ph5-p2', 'Professional Branding — The Summit', 'Mastered Professional Branding in Phase 5 (The Summit) for India.', 'pillar', 'middle_class', 'P2', 5, 'IN', NULL),
('mc-in-ph5-p3', 'Social Navigation — The Summit', 'Mastered Social Navigation in Phase 5 (The Summit) for India.', 'pillar', 'middle_class', 'P3', 5, 'IN', NULL),
('mc-in-ph5-phase', 'The Summit — India', 'Completed all three pillars of Phase 5 (The Summit) for India.', 'phase', 'middle_class', NULL, 5, 'IN', NULL),
('elite-in-ph5-phase', 'The Summit (Elite) — India', 'Mastered the Elite track of Phase 5 (The Summit) for India.', 'phase', 'elite', NULL, 5, 'IN', NULL),
('mc-in-country', 'Gecertificeerd voor India — Middenklasse', 'Earned all five Middle Class phase badges for India.', 'country', 'middle_class', NULL, NULL, 'IN', NULL),
('elite-in-country', 'Gecertificeerd voor India — Elite', 'Earned all five Elite phase badges for India.', 'country', 'elite', NULL, NULL, 'IN', NULL),
('mc-es-ph1-p1', 'Adaptive Linguistics — The Foyer', 'Mastered Adaptive Linguistics in Phase 1 (The Foyer) for Spain.', 'pillar', 'middle_class', 'P1', 1, 'ES', NULL),
('mc-es-ph1-p2', 'Professional Branding — The Foyer', 'Mastered Professional Branding in Phase 1 (The Foyer) for Spain.', 'pillar', 'middle_class', 'P2', 1, 'ES', NULL),
('mc-es-ph1-p3', 'Social Navigation — The Foyer', 'Mastered Social Navigation in Phase 1 (The Foyer) for Spain.', 'pillar', 'middle_class', 'P3', 1, 'ES', NULL),
('mc-es-ph1-phase', 'The Foyer — Spain', 'Completed all three pillars of Phase 1 (The Foyer) for Spain.', 'phase', 'middle_class', NULL, 1, 'ES', NULL),
('elite-es-ph1-phase', 'The Foyer (Elite) — Spain', 'Mastered the Elite track of Phase 1 (The Foyer) for Spain.', 'phase', 'elite', NULL, 1, 'ES', NULL),
('mc-es-ph2-p1', 'Adaptive Linguistics — The Salon', 'Mastered Adaptive Linguistics in Phase 2 (The Salon) for Spain.', 'pillar', 'middle_class', 'P1', 2, 'ES', NULL),
('mc-es-ph2-p2', 'Professional Branding — The Salon', 'Mastered Professional Branding in Phase 2 (The Salon) for Spain.', 'pillar', 'middle_class', 'P2', 2, 'ES', NULL),
('mc-es-ph2-p3', 'Social Navigation — The Salon', 'Mastered Social Navigation in Phase 2 (The Salon) for Spain.', 'pillar', 'middle_class', 'P3', 2, 'ES', NULL),
('mc-es-ph2-phase', 'The Salon — Spain', 'Completed all three pillars of Phase 2 (The Salon) for Spain.', 'phase', 'middle_class', NULL, 2, 'ES', NULL),
('elite-es-ph2-phase', 'The Salon (Elite) — Spain', 'Mastered the Elite track of Phase 2 (The Salon) for Spain.', 'phase', 'elite', NULL, 2, 'ES', NULL),
('mc-es-ph3-p1', 'Adaptive Linguistics — The Arena', 'Mastered Adaptive Linguistics in Phase 3 (The Arena) for Spain.', 'pillar', 'middle_class', 'P1', 3, 'ES', NULL),
('mc-es-ph3-p2', 'Professional Branding — The Arena', 'Mastered Professional Branding in Phase 3 (The Arena) for Spain.', 'pillar', 'middle_class', 'P2', 3, 'ES', NULL),
('mc-es-ph3-p3', 'Social Navigation — The Arena', 'Mastered Social Navigation in Phase 3 (The Arena) for Spain.', 'pillar', 'middle_class', 'P3', 3, 'ES', NULL),
('mc-es-ph3-phase', 'The Arena — Spain', 'Completed all three pillars of Phase 3 (The Arena) for Spain.', 'phase', 'middle_class', NULL, 3, 'ES', NULL),
('elite-es-ph3-phase', 'The Arena (Elite) — Spain', 'Mastered the Elite track of Phase 3 (The Arena) for Spain.', 'phase', 'elite', NULL, 3, 'ES', NULL),
('mc-es-ph4-p1', 'Adaptive Linguistics — The Sanctum', 'Mastered Adaptive Linguistics in Phase 4 (The Sanctum) for Spain.', 'pillar', 'middle_class', 'P1', 4, 'ES', NULL),
('mc-es-ph4-p2', 'Professional Branding — The Sanctum', 'Mastered Professional Branding in Phase 4 (The Sanctum) for Spain.', 'pillar', 'middle_class', 'P2', 4, 'ES', NULL),
('mc-es-ph4-p3', 'Social Navigation — The Sanctum', 'Mastered Social Navigation in Phase 4 (The Sanctum) for Spain.', 'pillar', 'middle_class', 'P3', 4, 'ES', NULL),
('mc-es-ph4-phase', 'The Sanctum — Spain', 'Completed all three pillars of Phase 4 (The Sanctum) for Spain.', 'phase', 'middle_class', NULL, 4, 'ES', NULL),
('elite-es-ph4-phase', 'The Sanctum (Elite) — Spain', 'Mastered the Elite track of Phase 4 (The Sanctum) for Spain.', 'phase', 'elite', NULL, 4, 'ES', NULL),
('mc-es-ph5-p1', 'Adaptive Linguistics — The Summit', 'Mastered Adaptive Linguistics in Phase 5 (The Summit) for Spain.', 'pillar', 'middle_class', 'P1', 5, 'ES', NULL),
('mc-es-ph5-p2', 'Professional Branding — The Summit', 'Mastered Professional Branding in Phase 5 (The Summit) for Spain.', 'pillar', 'middle_class', 'P2', 5, 'ES', NULL),
('mc-es-ph5-p3', 'Social Navigation — The Summit', 'Mastered Social Navigation in Phase 5 (The Summit) for Spain.', 'pillar', 'middle_class', 'P3', 5, 'ES', NULL),
('mc-es-ph5-phase', 'The Summit — Spain', 'Completed all three pillars of Phase 5 (The Summit) for Spain.', 'phase', 'middle_class', NULL, 5, 'ES', NULL),
('elite-es-ph5-phase', 'The Summit (Elite) — Spain', 'Mastered the Elite track of Phase 5 (The Summit) for Spain.', 'phase', 'elite', NULL, 5, 'ES', NULL),
('mc-es-country', 'Gecertificeerd voor Spain — Middenklasse', 'Earned all five Middle Class phase badges for Spain.', 'country', 'middle_class', NULL, NULL, 'ES', NULL),
('elite-es-country', 'Gecertificeerd voor Spain — Elite', 'Earned all five Elite phase badges for Spain.', 'country', 'elite', NULL, NULL, 'ES', NULL),
('mc-pt-ph1-p1', 'Adaptive Linguistics — The Foyer', 'Mastered Adaptive Linguistics in Phase 1 (The Foyer) for Portugal.', 'pillar', 'middle_class', 'P1', 1, 'PT', NULL),
('mc-pt-ph1-p2', 'Professional Branding — The Foyer', 'Mastered Professional Branding in Phase 1 (The Foyer) for Portugal.', 'pillar', 'middle_class', 'P2', 1, 'PT', NULL),
('mc-pt-ph1-p3', 'Social Navigation — The Foyer', 'Mastered Social Navigation in Phase 1 (The Foyer) for Portugal.', 'pillar', 'middle_class', 'P3', 1, 'PT', NULL),
('mc-pt-ph1-phase', 'The Foyer — Portugal', 'Completed all three pillars of Phase 1 (The Foyer) for Portugal.', 'phase', 'middle_class', NULL, 1, 'PT', NULL),
('elite-pt-ph1-phase', 'The Foyer (Elite) — Portugal', 'Mastered the Elite track of Phase 1 (The Foyer) for Portugal.', 'phase', 'elite', NULL, 1, 'PT', NULL),
('mc-pt-ph2-p1', 'Adaptive Linguistics — The Salon', 'Mastered Adaptive Linguistics in Phase 2 (The Salon) for Portugal.', 'pillar', 'middle_class', 'P1', 2, 'PT', NULL),
('mc-pt-ph2-p2', 'Professional Branding — The Salon', 'Mastered Professional Branding in Phase 2 (The Salon) for Portugal.', 'pillar', 'middle_class', 'P2', 2, 'PT', NULL),
('mc-pt-ph2-p3', 'Social Navigation — The Salon', 'Mastered Social Navigation in Phase 2 (The Salon) for Portugal.', 'pillar', 'middle_class', 'P3', 2, 'PT', NULL),
('mc-pt-ph2-phase', 'The Salon — Portugal', 'Completed all three pillars of Phase 2 (The Salon) for Portugal.', 'phase', 'middle_class', NULL, 2, 'PT', NULL),
('elite-pt-ph2-phase', 'The Salon (Elite) — Portugal', 'Mastered the Elite track of Phase 2 (The Salon) for Portugal.', 'phase', 'elite', NULL, 2, 'PT', NULL),
('mc-pt-ph3-p1', 'Adaptive Linguistics — The Arena', 'Mastered Adaptive Linguistics in Phase 3 (The Arena) for Portugal.', 'pillar', 'middle_class', 'P1', 3, 'PT', NULL),
('mc-pt-ph3-p2', 'Professional Branding — The Arena', 'Mastered Professional Branding in Phase 3 (The Arena) for Portugal.', 'pillar', 'middle_class', 'P2', 3, 'PT', NULL),
('mc-pt-ph3-p3', 'Social Navigation — The Arena', 'Mastered Social Navigation in Phase 3 (The Arena) for Portugal.', 'pillar', 'middle_class', 'P3', 3, 'PT', NULL),
('mc-pt-ph3-phase', 'The Arena — Portugal', 'Completed all three pillars of Phase 3 (The Arena) for Portugal.', 'phase', 'middle_class', NULL, 3, 'PT', NULL),
('elite-pt-ph3-phase', 'The Arena (Elite) — Portugal', 'Mastered the Elite track of Phase 3 (The Arena) for Portugal.', 'phase', 'elite', NULL, 3, 'PT', NULL),
('mc-pt-ph4-p1', 'Adaptive Linguistics — The Sanctum', 'Mastered Adaptive Linguistics in Phase 4 (The Sanctum) for Portugal.', 'pillar', 'middle_class', 'P1', 4, 'PT', NULL),
('mc-pt-ph4-p2', 'Professional Branding — The Sanctum', 'Mastered Professional Branding in Phase 4 (The Sanctum) for Portugal.', 'pillar', 'middle_class', 'P2', 4, 'PT', NULL),
('mc-pt-ph4-p3', 'Social Navigation — The Sanctum', 'Mastered Social Navigation in Phase 4 (The Sanctum) for Portugal.', 'pillar', 'middle_class', 'P3', 4, 'PT', NULL),
('mc-pt-ph4-phase', 'The Sanctum — Portugal', 'Completed all three pillars of Phase 4 (The Sanctum) for Portugal.', 'phase', 'middle_class', NULL, 4, 'PT', NULL),
('elite-pt-ph4-phase', 'The Sanctum (Elite) — Portugal', 'Mastered the Elite track of Phase 4 (The Sanctum) for Portugal.', 'phase', 'elite', NULL, 4, 'PT', NULL),
('mc-pt-ph5-p1', 'Adaptive Linguistics — The Summit', 'Mastered Adaptive Linguistics in Phase 5 (The Summit) for Portugal.', 'pillar', 'middle_class', 'P1', 5, 'PT', NULL),
('mc-pt-ph5-p2', 'Professional Branding — The Summit', 'Mastered Professional Branding in Phase 5 (The Summit) for Portugal.', 'pillar', 'middle_class', 'P2', 5, 'PT', NULL),
('mc-pt-ph5-p3', 'Social Navigation — The Summit', 'Mastered Social Navigation in Phase 5 (The Summit) for Portugal.', 'pillar', 'middle_class', 'P3', 5, 'PT', NULL),
('mc-pt-ph5-phase', 'The Summit — Portugal', 'Completed all three pillars of Phase 5 (The Summit) for Portugal.', 'phase', 'middle_class', NULL, 5, 'PT', NULL),
('elite-pt-ph5-phase', 'The Summit (Elite) — Portugal', 'Mastered the Elite track of Phase 5 (The Summit) for Portugal.', 'phase', 'elite', NULL, 5, 'PT', NULL),
('mc-pt-country', 'Gecertificeerd voor Portugal — Middenklasse', 'Earned all five Middle Class phase badges for Portugal.', 'country', 'middle_class', NULL, NULL, 'PT', NULL),
('elite-pt-country', 'Gecertificeerd voor Portugal — Elite', 'Earned all five Elite phase badges for Portugal.', 'country', 'elite', NULL, NULL, 'PT', NULL),
('mc-sg-ph1-p1', 'Adaptive Linguistics — The Foyer', 'Mastered Adaptive Linguistics in Phase 1 (The Foyer) for Singapore.', 'pillar', 'middle_class', 'P1', 1, 'SG', NULL),
('mc-sg-ph1-p2', 'Professional Branding — The Foyer', 'Mastered Professional Branding in Phase 1 (The Foyer) for Singapore.', 'pillar', 'middle_class', 'P2', 1, 'SG', NULL),
('mc-sg-ph1-p3', 'Social Navigation — The Foyer', 'Mastered Social Navigation in Phase 1 (The Foyer) for Singapore.', 'pillar', 'middle_class', 'P3', 1, 'SG', NULL),
('mc-sg-ph1-phase', 'The Foyer — Singapore', 'Completed all three pillars of Phase 1 (The Foyer) for Singapore.', 'phase', 'middle_class', NULL, 1, 'SG', NULL),
('elite-sg-ph1-phase', 'The Foyer (Elite) — Singapore', 'Mastered the Elite track of Phase 1 (The Foyer) for Singapore.', 'phase', 'elite', NULL, 1, 'SG', NULL),
('mc-sg-ph2-p1', 'Adaptive Linguistics — The Salon', 'Mastered Adaptive Linguistics in Phase 2 (The Salon) for Singapore.', 'pillar', 'middle_class', 'P1', 2, 'SG', NULL),
('mc-sg-ph2-p2', 'Professional Branding — The Salon', 'Mastered Professional Branding in Phase 2 (The Salon) for Singapore.', 'pillar', 'middle_class', 'P2', 2, 'SG', NULL),
('mc-sg-ph2-p3', 'Social Navigation — The Salon', 'Mastered Social Navigation in Phase 2 (The Salon) for Singapore.', 'pillar', 'middle_class', 'P3', 2, 'SG', NULL),
('mc-sg-ph2-phase', 'The Salon — Singapore', 'Completed all three pillars of Phase 2 (The Salon) for Singapore.', 'phase', 'middle_class', NULL, 2, 'SG', NULL),
('elite-sg-ph2-phase', 'The Salon (Elite) — Singapore', 'Mastered the Elite track of Phase 2 (The Salon) for Singapore.', 'phase', 'elite', NULL, 2, 'SG', NULL),
('mc-sg-ph3-p1', 'Adaptive Linguistics — The Arena', 'Mastered Adaptive Linguistics in Phase 3 (The Arena) for Singapore.', 'pillar', 'middle_class', 'P1', 3, 'SG', NULL),
('mc-sg-ph3-p2', 'Professional Branding — The Arena', 'Mastered Professional Branding in Phase 3 (The Arena) for Singapore.', 'pillar', 'middle_class', 'P2', 3, 'SG', NULL),
('mc-sg-ph3-p3', 'Social Navigation — The Arena', 'Mastered Social Navigation in Phase 3 (The Arena) for Singapore.', 'pillar', 'middle_class', 'P3', 3, 'SG', NULL),
('mc-sg-ph3-phase', 'The Arena — Singapore', 'Completed all three pillars of Phase 3 (The Arena) for Singapore.', 'phase', 'middle_class', NULL, 3, 'SG', NULL),
('elite-sg-ph3-phase', 'The Arena (Elite) — Singapore', 'Mastered the Elite track of Phase 3 (The Arena) for Singapore.', 'phase', 'elite', NULL, 3, 'SG', NULL),
('mc-sg-ph4-p1', 'Adaptive Linguistics — The Sanctum', 'Mastered Adaptive Linguistics in Phase 4 (The Sanctum) for Singapore.', 'pillar', 'middle_class', 'P1', 4, 'SG', NULL),
('mc-sg-ph4-p2', 'Professional Branding — The Sanctum', 'Mastered Professional Branding in Phase 4 (The Sanctum) for Singapore.', 'pillar', 'middle_class', 'P2', 4, 'SG', NULL),
('mc-sg-ph4-p3', 'Social Navigation — The Sanctum', 'Mastered Social Navigation in Phase 4 (The Sanctum) for Singapore.', 'pillar', 'middle_class', 'P3', 4, 'SG', NULL),
('mc-sg-ph4-phase', 'The Sanctum — Singapore', 'Completed all three pillars of Phase 4 (The Sanctum) for Singapore.', 'phase', 'middle_class', NULL, 4, 'SG', NULL),
('elite-sg-ph4-phase', 'The Sanctum (Elite) — Singapore', 'Mastered the Elite track of Phase 4 (The Sanctum) for Singapore.', 'phase', 'elite', NULL, 4, 'SG', NULL),
('mc-sg-ph5-p1', 'Adaptive Linguistics — The Summit', 'Mastered Adaptive Linguistics in Phase 5 (The Summit) for Singapore.', 'pillar', 'middle_class', 'P1', 5, 'SG', NULL),
('mc-sg-ph5-p2', 'Professional Branding — The Summit', 'Mastered Professional Branding in Phase 5 (The Summit) for Singapore.', 'pillar', 'middle_class', 'P2', 5, 'SG', NULL),
('mc-sg-ph5-p3', 'Social Navigation — The Summit', 'Mastered Social Navigation in Phase 5 (The Summit) for Singapore.', 'pillar', 'middle_class', 'P3', 5, 'SG', NULL),
('mc-sg-ph5-phase', 'The Summit — Singapore', 'Completed all three pillars of Phase 5 (The Summit) for Singapore.', 'phase', 'middle_class', NULL, 5, 'SG', NULL),
('elite-sg-ph5-phase', 'The Summit (Elite) — Singapore', 'Mastered the Elite track of Phase 5 (The Summit) for Singapore.', 'phase', 'elite', NULL, 5, 'SG', NULL),
('mc-sg-country', 'Gecertificeerd voor Singapore — Middenklasse', 'Earned all five Middle Class phase badges for Singapore.', 'country', 'middle_class', NULL, NULL, 'SG', NULL),
('elite-sg-country', 'Gecertificeerd voor Singapore — Elite', 'Earned all five Elite phase badges for Singapore.', 'country', 'elite', NULL, NULL, 'SG', NULL),
('mc-br-ph1-p1', 'Adaptive Linguistics — The Foyer', 'Mastered Adaptive Linguistics in Phase 1 (The Foyer) for Brazil.', 'pillar', 'middle_class', 'P1', 1, 'BR', NULL),
('mc-br-ph1-p2', 'Professional Branding — The Foyer', 'Mastered Professional Branding in Phase 1 (The Foyer) for Brazil.', 'pillar', 'middle_class', 'P2', 1, 'BR', NULL),
('mc-br-ph1-p3', 'Social Navigation — The Foyer', 'Mastered Social Navigation in Phase 1 (The Foyer) for Brazil.', 'pillar', 'middle_class', 'P3', 1, 'BR', NULL),
('mc-br-ph1-phase', 'The Foyer — Brazil', 'Completed all three pillars of Phase 1 (The Foyer) for Brazil.', 'phase', 'middle_class', NULL, 1, 'BR', NULL),
('elite-br-ph1-phase', 'The Foyer (Elite) — Brazil', 'Mastered the Elite track of Phase 1 (The Foyer) for Brazil.', 'phase', 'elite', NULL, 1, 'BR', NULL),
('mc-br-ph2-p1', 'Adaptive Linguistics — The Salon', 'Mastered Adaptive Linguistics in Phase 2 (The Salon) for Brazil.', 'pillar', 'middle_class', 'P1', 2, 'BR', NULL),
('mc-br-ph2-p2', 'Professional Branding — The Salon', 'Mastered Professional Branding in Phase 2 (The Salon) for Brazil.', 'pillar', 'middle_class', 'P2', 2, 'BR', NULL),
('mc-br-ph2-p3', 'Social Navigation — The Salon', 'Mastered Social Navigation in Phase 2 (The Salon) for Brazil.', 'pillar', 'middle_class', 'P3', 2, 'BR', NULL),
('mc-br-ph2-phase', 'The Salon — Brazil', 'Completed all three pillars of Phase 2 (The Salon) for Brazil.', 'phase', 'middle_class', NULL, 2, 'BR', NULL),
('elite-br-ph2-phase', 'The Salon (Elite) — Brazil', 'Mastered the Elite track of Phase 2 (The Salon) for Brazil.', 'phase', 'elite', NULL, 2, 'BR', NULL),
('mc-br-ph3-p1', 'Adaptive Linguistics — The Arena', 'Mastered Adaptive Linguistics in Phase 3 (The Arena) for Brazil.', 'pillar', 'middle_class', 'P1', 3, 'BR', NULL),
('mc-br-ph3-p2', 'Professional Branding — The Arena', 'Mastered Professional Branding in Phase 3 (The Arena) for Brazil.', 'pillar', 'middle_class', 'P2', 3, 'BR', NULL),
('mc-br-ph3-p3', 'Social Navigation — The Arena', 'Mastered Social Navigation in Phase 3 (The Arena) for Brazil.', 'pillar', 'middle_class', 'P3', 3, 'BR', NULL),
('mc-br-ph3-phase', 'The Arena — Brazil', 'Completed all three pillars of Phase 3 (The Arena) for Brazil.', 'phase', 'middle_class', NULL, 3, 'BR', NULL),
('elite-br-ph3-phase', 'The Arena (Elite) — Brazil', 'Mastered the Elite track of Phase 3 (The Arena) for Brazil.', 'phase', 'elite', NULL, 3, 'BR', NULL),
('mc-br-ph4-p1', 'Adaptive Linguistics — The Sanctum', 'Mastered Adaptive Linguistics in Phase 4 (The Sanctum) for Brazil.', 'pillar', 'middle_class', 'P1', 4, 'BR', NULL),
('mc-br-ph4-p2', 'Professional Branding — The Sanctum', 'Mastered Professional Branding in Phase 4 (The Sanctum) for Brazil.', 'pillar', 'middle_class', 'P2', 4, 'BR', NULL),
('mc-br-ph4-p3', 'Social Navigation — The Sanctum', 'Mastered Social Navigation in Phase 4 (The Sanctum) for Brazil.', 'pillar', 'middle_class', 'P3', 4, 'BR', NULL),
('mc-br-ph4-phase', 'The Sanctum — Brazil', 'Completed all three pillars of Phase 4 (The Sanctum) for Brazil.', 'phase', 'middle_class', NULL, 4, 'BR', NULL),
('elite-br-ph4-phase', 'The Sanctum (Elite) — Brazil', 'Mastered the Elite track of Phase 4 (The Sanctum) for Brazil.', 'phase', 'elite', NULL, 4, 'BR', NULL),
('mc-br-ph5-p1', 'Adaptive Linguistics — The Summit', 'Mastered Adaptive Linguistics in Phase 5 (The Summit) for Brazil.', 'pillar', 'middle_class', 'P1', 5, 'BR', NULL),
('mc-br-ph5-p2', 'Professional Branding — The Summit', 'Mastered Professional Branding in Phase 5 (The Summit) for Brazil.', 'pillar', 'middle_class', 'P2', 5, 'BR', NULL),
('mc-br-ph5-p3', 'Social Navigation — The Summit', 'Mastered Social Navigation in Phase 5 (The Summit) for Brazil.', 'pillar', 'middle_class', 'P3', 5, 'BR', NULL),
('mc-br-ph5-phase', 'The Summit — Brazil', 'Completed all three pillars of Phase 5 (The Summit) for Brazil.', 'phase', 'middle_class', NULL, 5, 'BR', NULL),
('elite-br-ph5-phase', 'The Summit (Elite) — Brazil', 'Mastered the Elite track of Phase 5 (The Summit) for Brazil.', 'phase', 'elite', NULL, 5, 'BR', NULL),
('mc-br-country', 'Gecertificeerd voor Brazil — Middenklasse', 'Earned all five Middle Class phase badges for Brazil.', 'country', 'middle_class', NULL, NULL, 'BR', NULL),
('elite-br-country', 'Gecertificeerd voor Brazil — Elite', 'Earned all five Elite phase badges for Brazil.', 'country', 'elite', NULL, NULL, 'BR', NULL),
('mc-za-ph1-p1', 'Adaptive Linguistics — The Foyer', 'Mastered Adaptive Linguistics in Phase 1 (The Foyer) for South Africa.', 'pillar', 'middle_class', 'P1', 1, 'ZA', NULL),
('mc-za-ph1-p2', 'Professional Branding — The Foyer', 'Mastered Professional Branding in Phase 1 (The Foyer) for South Africa.', 'pillar', 'middle_class', 'P2', 1, 'ZA', NULL),
('mc-za-ph1-p3', 'Social Navigation — The Foyer', 'Mastered Social Navigation in Phase 1 (The Foyer) for South Africa.', 'pillar', 'middle_class', 'P3', 1, 'ZA', NULL),
('mc-za-ph1-phase', 'The Foyer — South Africa', 'Completed all three pillars of Phase 1 (The Foyer) for South Africa.', 'phase', 'middle_class', NULL, 1, 'ZA', NULL),
('elite-za-ph1-phase', 'The Foyer (Elite) — South Africa', 'Mastered the Elite track of Phase 1 (The Foyer) for South Africa.', 'phase', 'elite', NULL, 1, 'ZA', NULL),
('mc-za-ph2-p1', 'Adaptive Linguistics — The Salon', 'Mastered Adaptive Linguistics in Phase 2 (The Salon) for South Africa.', 'pillar', 'middle_class', 'P1', 2, 'ZA', NULL),
('mc-za-ph2-p2', 'Professional Branding — The Salon', 'Mastered Professional Branding in Phase 2 (The Salon) for South Africa.', 'pillar', 'middle_class', 'P2', 2, 'ZA', NULL),
('mc-za-ph2-p3', 'Social Navigation — The Salon', 'Mastered Social Navigation in Phase 2 (The Salon) for South Africa.', 'pillar', 'middle_class', 'P3', 2, 'ZA', NULL),
('mc-za-ph2-phase', 'The Salon — South Africa', 'Completed all three pillars of Phase 2 (The Salon) for South Africa.', 'phase', 'middle_class', NULL, 2, 'ZA', NULL),
('elite-za-ph2-phase', 'The Salon (Elite) — South Africa', 'Mastered the Elite track of Phase 2 (The Salon) for South Africa.', 'phase', 'elite', NULL, 2, 'ZA', NULL),
('mc-za-ph3-p1', 'Adaptive Linguistics — The Arena', 'Mastered Adaptive Linguistics in Phase 3 (The Arena) for South Africa.', 'pillar', 'middle_class', 'P1', 3, 'ZA', NULL),
('mc-za-ph3-p2', 'Professional Branding — The Arena', 'Mastered Professional Branding in Phase 3 (The Arena) for South Africa.', 'pillar', 'middle_class', 'P2', 3, 'ZA', NULL),
('mc-za-ph3-p3', 'Social Navigation — The Arena', 'Mastered Social Navigation in Phase 3 (The Arena) for South Africa.', 'pillar', 'middle_class', 'P3', 3, 'ZA', NULL),
('mc-za-ph3-phase', 'The Arena — South Africa', 'Completed all three pillars of Phase 3 (The Arena) for South Africa.', 'phase', 'middle_class', NULL, 3, 'ZA', NULL),
('elite-za-ph3-phase', 'The Arena (Elite) — South Africa', 'Mastered the Elite track of Phase 3 (The Arena) for South Africa.', 'phase', 'elite', NULL, 3, 'ZA', NULL),
('mc-za-ph4-p1', 'Adaptive Linguistics — The Sanctum', 'Mastered Adaptive Linguistics in Phase 4 (The Sanctum) for South Africa.', 'pillar', 'middle_class', 'P1', 4, 'ZA', NULL),
('mc-za-ph4-p2', 'Professional Branding — The Sanctum', 'Mastered Professional Branding in Phase 4 (The Sanctum) for South Africa.', 'pillar', 'middle_class', 'P2', 4, 'ZA', NULL),
('mc-za-ph4-p3', 'Social Navigation — The Sanctum', 'Mastered Social Navigation in Phase 4 (The Sanctum) for South Africa.', 'pillar', 'middle_class', 'P3', 4, 'ZA', NULL),
('mc-za-ph4-phase', 'The Sanctum — South Africa', 'Completed all three pillars of Phase 4 (The Sanctum) for South Africa.', 'phase', 'middle_class', NULL, 4, 'ZA', NULL),
('elite-za-ph4-phase', 'The Sanctum (Elite) — South Africa', 'Mastered the Elite track of Phase 4 (The Sanctum) for South Africa.', 'phase', 'elite', NULL, 4, 'ZA', NULL),
('mc-za-ph5-p1', 'Adaptive Linguistics — The Summit', 'Mastered Adaptive Linguistics in Phase 5 (The Summit) for South Africa.', 'pillar', 'middle_class', 'P1', 5, 'ZA', NULL),
('mc-za-ph5-p2', 'Professional Branding — The Summit', 'Mastered Professional Branding in Phase 5 (The Summit) for South Africa.', 'pillar', 'middle_class', 'P2', 5, 'ZA', NULL),
('mc-za-ph5-p3', 'Social Navigation — The Summit', 'Mastered Social Navigation in Phase 5 (The Summit) for South Africa.', 'pillar', 'middle_class', 'P3', 5, 'ZA', NULL),
('mc-za-ph5-phase', 'The Summit — South Africa', 'Completed all three pillars of Phase 5 (The Summit) for South Africa.', 'phase', 'middle_class', NULL, 5, 'ZA', NULL),
('elite-za-ph5-phase', 'The Summit (Elite) — South Africa', 'Mastered the Elite track of Phase 5 (The Summit) for South Africa.', 'phase', 'elite', NULL, 5, 'ZA', NULL),
('mc-za-country', 'Gecertificeerd voor South Africa — Middenklasse', 'Earned all five Middle Class phase badges for South Africa.', 'country', 'middle_class', NULL, NULL, 'ZA', NULL),
('elite-za-country', 'Gecertificeerd voor South Africa — Elite', 'Earned all five Elite phase badges for South Africa.', 'country', 'elite', NULL, NULL, 'ZA', NULL),
('mc-mx-ph1-p1', 'Adaptive Linguistics — The Foyer', 'Mastered Adaptive Linguistics in Phase 1 (The Foyer) for Mexico.', 'pillar', 'middle_class', 'P1', 1, 'MX', NULL),
('mc-mx-ph1-p2', 'Professional Branding — The Foyer', 'Mastered Professional Branding in Phase 1 (The Foyer) for Mexico.', 'pillar', 'middle_class', 'P2', 1, 'MX', NULL),
('mc-mx-ph1-p3', 'Social Navigation — The Foyer', 'Mastered Social Navigation in Phase 1 (The Foyer) for Mexico.', 'pillar', 'middle_class', 'P3', 1, 'MX', NULL),
('mc-mx-ph1-phase', 'The Foyer — Mexico', 'Completed all three pillars of Phase 1 (The Foyer) for Mexico.', 'phase', 'middle_class', NULL, 1, 'MX', NULL),
('elite-mx-ph1-phase', 'The Foyer (Elite) — Mexico', 'Mastered the Elite track of Phase 1 (The Foyer) for Mexico.', 'phase', 'elite', NULL, 1, 'MX', NULL),
('mc-mx-ph2-p1', 'Adaptive Linguistics — The Salon', 'Mastered Adaptive Linguistics in Phase 2 (The Salon) for Mexico.', 'pillar', 'middle_class', 'P1', 2, 'MX', NULL),
('mc-mx-ph2-p2', 'Professional Branding — The Salon', 'Mastered Professional Branding in Phase 2 (The Salon) for Mexico.', 'pillar', 'middle_class', 'P2', 2, 'MX', NULL),
('mc-mx-ph2-p3', 'Social Navigation — The Salon', 'Mastered Social Navigation in Phase 2 (The Salon) for Mexico.', 'pillar', 'middle_class', 'P3', 2, 'MX', NULL),
('mc-mx-ph2-phase', 'The Salon — Mexico', 'Completed all three pillars of Phase 2 (The Salon) for Mexico.', 'phase', 'middle_class', NULL, 2, 'MX', NULL),
('elite-mx-ph2-phase', 'The Salon (Elite) — Mexico', 'Mastered the Elite track of Phase 2 (The Salon) for Mexico.', 'phase', 'elite', NULL, 2, 'MX', NULL),
('mc-mx-ph3-p1', 'Adaptive Linguistics — The Arena', 'Mastered Adaptive Linguistics in Phase 3 (The Arena) for Mexico.', 'pillar', 'middle_class', 'P1', 3, 'MX', NULL),
('mc-mx-ph3-p2', 'Professional Branding — The Arena', 'Mastered Professional Branding in Phase 3 (The Arena) for Mexico.', 'pillar', 'middle_class', 'P2', 3, 'MX', NULL),
('mc-mx-ph3-p3', 'Social Navigation — The Arena', 'Mastered Social Navigation in Phase 3 (The Arena) for Mexico.', 'pillar', 'middle_class', 'P3', 3, 'MX', NULL),
('mc-mx-ph3-phase', 'The Arena — Mexico', 'Completed all three pillars of Phase 3 (The Arena) for Mexico.', 'phase', 'middle_class', NULL, 3, 'MX', NULL),
('elite-mx-ph3-phase', 'The Arena (Elite) — Mexico', 'Mastered the Elite track of Phase 3 (The Arena) for Mexico.', 'phase', 'elite', NULL, 3, 'MX', NULL),
('mc-mx-ph4-p1', 'Adaptive Linguistics — The Sanctum', 'Mastered Adaptive Linguistics in Phase 4 (The Sanctum) for Mexico.', 'pillar', 'middle_class', 'P1', 4, 'MX', NULL),
('mc-mx-ph4-p2', 'Professional Branding — The Sanctum', 'Mastered Professional Branding in Phase 4 (The Sanctum) for Mexico.', 'pillar', 'middle_class', 'P2', 4, 'MX', NULL),
('mc-mx-ph4-p3', 'Social Navigation — The Sanctum', 'Mastered Social Navigation in Phase 4 (The Sanctum) for Mexico.', 'pillar', 'middle_class', 'P3', 4, 'MX', NULL),
('mc-mx-ph4-phase', 'The Sanctum — Mexico', 'Completed all three pillars of Phase 4 (The Sanctum) for Mexico.', 'phase', 'middle_class', NULL, 4, 'MX', NULL),
('elite-mx-ph4-phase', 'The Sanctum (Elite) — Mexico', 'Mastered the Elite track of Phase 4 (The Sanctum) for Mexico.', 'phase', 'elite', NULL, 4, 'MX', NULL),
('mc-mx-ph5-p1', 'Adaptive Linguistics — The Summit', 'Mastered Adaptive Linguistics in Phase 5 (The Summit) for Mexico.', 'pillar', 'middle_class', 'P1', 5, 'MX', NULL),
('mc-mx-ph5-p2', 'Professional Branding — The Summit', 'Mastered Professional Branding in Phase 5 (The Summit) for Mexico.', 'pillar', 'middle_class', 'P2', 5, 'MX', NULL),
('mc-mx-ph5-p3', 'Social Navigation — The Summit', 'Mastered Social Navigation in Phase 5 (The Summit) for Mexico.', 'pillar', 'middle_class', 'P3', 5, 'MX', NULL),
('mc-mx-ph5-phase', 'The Summit — Mexico', 'Completed all three pillars of Phase 5 (The Summit) for Mexico.', 'phase', 'middle_class', NULL, 5, 'MX', NULL),
('elite-mx-ph5-phase', 'The Summit (Elite) — Mexico', 'Mastered the Elite track of Phase 5 (The Summit) for Mexico.', 'phase', 'elite', NULL, 5, 'MX', NULL),
('mc-mx-country', 'Gecertificeerd voor Mexico — Middenklasse', 'Earned all five Middle Class phase badges for Mexico.', 'country', 'middle_class', NULL, NULL, 'MX', NULL),
('elite-mx-country', 'Gecertificeerd voor Mexico — Elite', 'Earned all five Elite phase badges for Mexico.', 'country', 'elite', NULL, NULL, 'MX', NULL),
('mc-co-ph1-p1', 'Adaptive Linguistics — The Foyer', 'Mastered Adaptive Linguistics in Phase 1 (The Foyer) for Colombia.', 'pillar', 'middle_class', 'P1', 1, 'CO', NULL),
('mc-co-ph1-p2', 'Professional Branding — The Foyer', 'Mastered Professional Branding in Phase 1 (The Foyer) for Colombia.', 'pillar', 'middle_class', 'P2', 1, 'CO', NULL),
('mc-co-ph1-p3', 'Social Navigation — The Foyer', 'Mastered Social Navigation in Phase 1 (The Foyer) for Colombia.', 'pillar', 'middle_class', 'P3', 1, 'CO', NULL),
('mc-co-ph1-phase', 'The Foyer — Colombia', 'Completed all three pillars of Phase 1 (The Foyer) for Colombia.', 'phase', 'middle_class', NULL, 1, 'CO', NULL),
('elite-co-ph1-phase', 'The Foyer (Elite) — Colombia', 'Mastered the Elite track of Phase 1 (The Foyer) for Colombia.', 'phase', 'elite', NULL, 1, 'CO', NULL),
('mc-co-ph2-p1', 'Adaptive Linguistics — The Salon', 'Mastered Adaptive Linguistics in Phase 2 (The Salon) for Colombia.', 'pillar', 'middle_class', 'P1', 2, 'CO', NULL),
('mc-co-ph2-p2', 'Professional Branding — The Salon', 'Mastered Professional Branding in Phase 2 (The Salon) for Colombia.', 'pillar', 'middle_class', 'P2', 2, 'CO', NULL),
('mc-co-ph2-p3', 'Social Navigation — The Salon', 'Mastered Social Navigation in Phase 2 (The Salon) for Colombia.', 'pillar', 'middle_class', 'P3', 2, 'CO', NULL),
('mc-co-ph2-phase', 'The Salon — Colombia', 'Completed all three pillars of Phase 2 (The Salon) for Colombia.', 'phase', 'middle_class', NULL, 2, 'CO', NULL),
('elite-co-ph2-phase', 'The Salon (Elite) — Colombia', 'Mastered the Elite track of Phase 2 (The Salon) for Colombia.', 'phase', 'elite', NULL, 2, 'CO', NULL),
('mc-co-ph3-p1', 'Adaptive Linguistics — The Arena', 'Mastered Adaptive Linguistics in Phase 3 (The Arena) for Colombia.', 'pillar', 'middle_class', 'P1', 3, 'CO', NULL),
('mc-co-ph3-p2', 'Professional Branding — The Arena', 'Mastered Professional Branding in Phase 3 (The Arena) for Colombia.', 'pillar', 'middle_class', 'P2', 3, 'CO', NULL),
('mc-co-ph3-p3', 'Social Navigation — The Arena', 'Mastered Social Navigation in Phase 3 (The Arena) for Colombia.', 'pillar', 'middle_class', 'P3', 3, 'CO', NULL),
('mc-co-ph3-phase', 'The Arena — Colombia', 'Completed all three pillars of Phase 3 (The Arena) for Colombia.', 'phase', 'middle_class', NULL, 3, 'CO', NULL),
('elite-co-ph3-phase', 'The Arena (Elite) — Colombia', 'Mastered the Elite track of Phase 3 (The Arena) for Colombia.', 'phase', 'elite', NULL, 3, 'CO', NULL),
('mc-co-ph4-p1', 'Adaptive Linguistics — The Sanctum', 'Mastered Adaptive Linguistics in Phase 4 (The Sanctum) for Colombia.', 'pillar', 'middle_class', 'P1', 4, 'CO', NULL),
('mc-co-ph4-p2', 'Professional Branding — The Sanctum', 'Mastered Professional Branding in Phase 4 (The Sanctum) for Colombia.', 'pillar', 'middle_class', 'P2', 4, 'CO', NULL),
('mc-co-ph4-p3', 'Social Navigation — The Sanctum', 'Mastered Social Navigation in Phase 4 (The Sanctum) for Colombia.', 'pillar', 'middle_class', 'P3', 4, 'CO', NULL),
('mc-co-ph4-phase', 'The Sanctum — Colombia', 'Completed all three pillars of Phase 4 (The Sanctum) for Colombia.', 'phase', 'middle_class', NULL, 4, 'CO', NULL),
('elite-co-ph4-phase', 'The Sanctum (Elite) — Colombia', 'Mastered the Elite track of Phase 4 (The Sanctum) for Colombia.', 'phase', 'elite', NULL, 4, 'CO', NULL),
('mc-co-ph5-p1', 'Adaptive Linguistics — The Summit', 'Mastered Adaptive Linguistics in Phase 5 (The Summit) for Colombia.', 'pillar', 'middle_class', 'P1', 5, 'CO', NULL),
('mc-co-ph5-p2', 'Professional Branding — The Summit', 'Mastered Professional Branding in Phase 5 (The Summit) for Colombia.', 'pillar', 'middle_class', 'P2', 5, 'CO', NULL),
('mc-co-ph5-p3', 'Social Navigation — The Summit', 'Mastered Social Navigation in Phase 5 (The Summit) for Colombia.', 'pillar', 'middle_class', 'P3', 5, 'CO', NULL),
('mc-co-ph5-phase', 'The Summit — Colombia', 'Completed all three pillars of Phase 5 (The Summit) for Colombia.', 'phase', 'middle_class', NULL, 5, 'CO', NULL),
('elite-co-ph5-phase', 'The Summit (Elite) — Colombia', 'Mastered the Elite track of Phase 5 (The Summit) for Colombia.', 'phase', 'elite', NULL, 5, 'CO', NULL),
('mc-co-country', 'Gecertificeerd voor Colombia — Middenklasse', 'Earned all five Middle Class phase badges for Colombia.', 'country', 'middle_class', NULL, NULL, 'CO', NULL),
('elite-co-country', 'Gecertificeerd voor Colombia — Elite', 'Earned all five Elite phase badges for Colombia.', 'country', 'elite', NULL, NULL, 'CO', NULL),
('mc-be-ph1-p1', 'Adaptive Linguistics — The Foyer', 'Mastered Adaptive Linguistics in Phase 1 (The Foyer) for Belgium.', 'pillar', 'middle_class', 'P1', 1, 'BE', NULL),
('mc-be-ph1-p2', 'Professional Branding — The Foyer', 'Mastered Professional Branding in Phase 1 (The Foyer) for Belgium.', 'pillar', 'middle_class', 'P2', 1, 'BE', NULL),
('mc-be-ph1-p3', 'Social Navigation — The Foyer', 'Mastered Social Navigation in Phase 1 (The Foyer) for Belgium.', 'pillar', 'middle_class', 'P3', 1, 'BE', NULL),
('mc-be-ph1-phase', 'The Foyer — Belgium', 'Completed all three pillars of Phase 1 (The Foyer) for Belgium.', 'phase', 'middle_class', NULL, 1, 'BE', NULL),
('elite-be-ph1-phase', 'The Foyer (Elite) — Belgium', 'Mastered the Elite track of Phase 1 (The Foyer) for Belgium.', 'phase', 'elite', NULL, 1, 'BE', NULL),
('mc-be-ph2-p1', 'Adaptive Linguistics — The Salon', 'Mastered Adaptive Linguistics in Phase 2 (The Salon) for Belgium.', 'pillar', 'middle_class', 'P1', 2, 'BE', NULL),
('mc-be-ph2-p2', 'Professional Branding — The Salon', 'Mastered Professional Branding in Phase 2 (The Salon) for Belgium.', 'pillar', 'middle_class', 'P2', 2, 'BE', NULL),
('mc-be-ph2-p3', 'Social Navigation — The Salon', 'Mastered Social Navigation in Phase 2 (The Salon) for Belgium.', 'pillar', 'middle_class', 'P3', 2, 'BE', NULL),
('mc-be-ph2-phase', 'The Salon — Belgium', 'Completed all three pillars of Phase 2 (The Salon) for Belgium.', 'phase', 'middle_class', NULL, 2, 'BE', NULL),
('elite-be-ph2-phase', 'The Salon (Elite) — Belgium', 'Mastered the Elite track of Phase 2 (The Salon) for Belgium.', 'phase', 'elite', NULL, 2, 'BE', NULL),
('mc-be-ph3-p1', 'Adaptive Linguistics — The Arena', 'Mastered Adaptive Linguistics in Phase 3 (The Arena) for Belgium.', 'pillar', 'middle_class', 'P1', 3, 'BE', NULL),
('mc-be-ph3-p2', 'Professional Branding — The Arena', 'Mastered Professional Branding in Phase 3 (The Arena) for Belgium.', 'pillar', 'middle_class', 'P2', 3, 'BE', NULL),
('mc-be-ph3-p3', 'Social Navigation — The Arena', 'Mastered Social Navigation in Phase 3 (The Arena) for Belgium.', 'pillar', 'middle_class', 'P3', 3, 'BE', NULL),
('mc-be-ph3-phase', 'The Arena — Belgium', 'Completed all three pillars of Phase 3 (The Arena) for Belgium.', 'phase', 'middle_class', NULL, 3, 'BE', NULL),
('elite-be-ph3-phase', 'The Arena (Elite) — Belgium', 'Mastered the Elite track of Phase 3 (The Arena) for Belgium.', 'phase', 'elite', NULL, 3, 'BE', NULL),
('mc-be-ph4-p1', 'Adaptive Linguistics — The Sanctum', 'Mastered Adaptive Linguistics in Phase 4 (The Sanctum) for Belgium.', 'pillar', 'middle_class', 'P1', 4, 'BE', NULL),
('mc-be-ph4-p2', 'Professional Branding — The Sanctum', 'Mastered Professional Branding in Phase 4 (The Sanctum) for Belgium.', 'pillar', 'middle_class', 'P2', 4, 'BE', NULL),
('mc-be-ph4-p3', 'Social Navigation — The Sanctum', 'Mastered Social Navigation in Phase 4 (The Sanctum) for Belgium.', 'pillar', 'middle_class', 'P3', 4, 'BE', NULL),
('mc-be-ph4-phase', 'The Sanctum — Belgium', 'Completed all three pillars of Phase 4 (The Sanctum) for Belgium.', 'phase', 'middle_class', NULL, 4, 'BE', NULL),
('elite-be-ph4-phase', 'The Sanctum (Elite) — Belgium', 'Mastered the Elite track of Phase 4 (The Sanctum) for Belgium.', 'phase', 'elite', NULL, 4, 'BE', NULL),
('mc-be-ph5-p1', 'Adaptive Linguistics — The Summit', 'Mastered Adaptive Linguistics in Phase 5 (The Summit) for Belgium.', 'pillar', 'middle_class', 'P1', 5, 'BE', NULL),
('mc-be-ph5-p2', 'Professional Branding — The Summit', 'Mastered Professional Branding in Phase 5 (The Summit) for Belgium.', 'pillar', 'middle_class', 'P2', 5, 'BE', NULL),
('mc-be-ph5-p3', 'Social Navigation — The Summit', 'Mastered Social Navigation in Phase 5 (The Summit) for Belgium.', 'pillar', 'middle_class', 'P3', 5, 'BE', NULL),
('mc-be-ph5-phase', 'The Summit — Belgium', 'Completed all three pillars of Phase 5 (The Summit) for Belgium.', 'phase', 'middle_class', NULL, 5, 'BE', NULL),
('elite-be-ph5-phase', 'The Summit (Elite) — Belgium', 'Mastered the Elite track of Phase 5 (The Summit) for Belgium.', 'phase', 'elite', NULL, 5, 'BE', NULL),
('mc-be-country', 'Gecertificeerd voor Belgium — Middenklasse', 'Earned all five Middle Class phase badges for Belgium.', 'country', 'middle_class', NULL, NULL, 'BE', NULL),
('elite-be-country', 'Gecertificeerd voor Belgium — Elite', 'Earned all five Elite phase badges for Belgium.', 'country', 'elite', NULL, NULL, 'BE', NULL),
('mc-ch-ph1-p1', 'Adaptive Linguistics — The Foyer', 'Mastered Adaptive Linguistics in Phase 1 (The Foyer) for Switzerland.', 'pillar', 'middle_class', 'P1', 1, 'CH', NULL),
('mc-ch-ph1-p2', 'Professional Branding — The Foyer', 'Mastered Professional Branding in Phase 1 (The Foyer) for Switzerland.', 'pillar', 'middle_class', 'P2', 1, 'CH', NULL),
('mc-ch-ph1-p3', 'Social Navigation — The Foyer', 'Mastered Social Navigation in Phase 1 (The Foyer) for Switzerland.', 'pillar', 'middle_class', 'P3', 1, 'CH', NULL),
('mc-ch-ph1-phase', 'The Foyer — Switzerland', 'Completed all three pillars of Phase 1 (The Foyer) for Switzerland.', 'phase', 'middle_class', NULL, 1, 'CH', NULL),
('elite-ch-ph1-phase', 'The Foyer (Elite) — Switzerland', 'Mastered the Elite track of Phase 1 (The Foyer) for Switzerland.', 'phase', 'elite', NULL, 1, 'CH', NULL),
('mc-ch-ph2-p1', 'Adaptive Linguistics — The Salon', 'Mastered Adaptive Linguistics in Phase 2 (The Salon) for Switzerland.', 'pillar', 'middle_class', 'P1', 2, 'CH', NULL),
('mc-ch-ph2-p2', 'Professional Branding — The Salon', 'Mastered Professional Branding in Phase 2 (The Salon) for Switzerland.', 'pillar', 'middle_class', 'P2', 2, 'CH', NULL),
('mc-ch-ph2-p3', 'Social Navigation — The Salon', 'Mastered Social Navigation in Phase 2 (The Salon) for Switzerland.', 'pillar', 'middle_class', 'P3', 2, 'CH', NULL),
('mc-ch-ph2-phase', 'The Salon — Switzerland', 'Completed all three pillars of Phase 2 (The Salon) for Switzerland.', 'phase', 'middle_class', NULL, 2, 'CH', NULL),
('elite-ch-ph2-phase', 'The Salon (Elite) — Switzerland', 'Mastered the Elite track of Phase 2 (The Salon) for Switzerland.', 'phase', 'elite', NULL, 2, 'CH', NULL),
('mc-ch-ph3-p1', 'Adaptive Linguistics — The Arena', 'Mastered Adaptive Linguistics in Phase 3 (The Arena) for Switzerland.', 'pillar', 'middle_class', 'P1', 3, 'CH', NULL),
('mc-ch-ph3-p2', 'Professional Branding — The Arena', 'Mastered Professional Branding in Phase 3 (The Arena) for Switzerland.', 'pillar', 'middle_class', 'P2', 3, 'CH', NULL),
('mc-ch-ph3-p3', 'Social Navigation — The Arena', 'Mastered Social Navigation in Phase 3 (The Arena) for Switzerland.', 'pillar', 'middle_class', 'P3', 3, 'CH', NULL),
('mc-ch-ph3-phase', 'The Arena — Switzerland', 'Completed all three pillars of Phase 3 (The Arena) for Switzerland.', 'phase', 'middle_class', NULL, 3, 'CH', NULL),
('elite-ch-ph3-phase', 'The Arena (Elite) — Switzerland', 'Mastered the Elite track of Phase 3 (The Arena) for Switzerland.', 'phase', 'elite', NULL, 3, 'CH', NULL),
('mc-ch-ph4-p1', 'Adaptive Linguistics — The Sanctum', 'Mastered Adaptive Linguistics in Phase 4 (The Sanctum) for Switzerland.', 'pillar', 'middle_class', 'P1', 4, 'CH', NULL),
('mc-ch-ph4-p2', 'Professional Branding — The Sanctum', 'Mastered Professional Branding in Phase 4 (The Sanctum) for Switzerland.', 'pillar', 'middle_class', 'P2', 4, 'CH', NULL),
('mc-ch-ph4-p3', 'Social Navigation — The Sanctum', 'Mastered Social Navigation in Phase 4 (The Sanctum) for Switzerland.', 'pillar', 'middle_class', 'P3', 4, 'CH', NULL),
('mc-ch-ph4-phase', 'The Sanctum — Switzerland', 'Completed all three pillars of Phase 4 (The Sanctum) for Switzerland.', 'phase', 'middle_class', NULL, 4, 'CH', NULL),
('elite-ch-ph4-phase', 'The Sanctum (Elite) — Switzerland', 'Mastered the Elite track of Phase 4 (The Sanctum) for Switzerland.', 'phase', 'elite', NULL, 4, 'CH', NULL),
('mc-ch-ph5-p1', 'Adaptive Linguistics — The Summit', 'Mastered Adaptive Linguistics in Phase 5 (The Summit) for Switzerland.', 'pillar', 'middle_class', 'P1', 5, 'CH', NULL),
('mc-ch-ph5-p2', 'Professional Branding — The Summit', 'Mastered Professional Branding in Phase 5 (The Summit) for Switzerland.', 'pillar', 'middle_class', 'P2', 5, 'CH', NULL),
('mc-ch-ph5-p3', 'Social Navigation — The Summit', 'Mastered Social Navigation in Phase 5 (The Summit) for Switzerland.', 'pillar', 'middle_class', 'P3', 5, 'CH', NULL),
('mc-ch-ph5-phase', 'The Summit — Switzerland', 'Completed all three pillars of Phase 5 (The Summit) for Switzerland.', 'phase', 'middle_class', NULL, 5, 'CH', NULL),
('elite-ch-ph5-phase', 'The Summit (Elite) — Switzerland', 'Mastered the Elite track of Phase 5 (The Summit) for Switzerland.', 'phase', 'elite', NULL, 5, 'CH', NULL),
('mc-ch-country', 'Gecertificeerd voor Switzerland — Middenklasse', 'Earned all five Middle Class phase badges for Switzerland.', 'country', 'middle_class', NULL, NULL, 'CH', NULL),
('elite-ch-country', 'Gecertificeerd voor Switzerland — Elite', 'Earned all five Elite phase badges for Switzerland.', 'country', 'elite', NULL, NULL, 'CH', NULL),
('cortea-ambassador', 'Cortéa Ambassadeur', 'Earned all country badges for both Middle Class and Elite registers across all active regions.', 'ambassador', 'middle_class', NULL, NULL, NULL, NULL)
ON CONFLICT (slug) DO NOTHING;