-- Migration 0013: seed cultural_origins for 17 priority Compass regions
  -- Adds origin records for: JP, DE, FR, IT, BE, CH, SG, IN, MX, BR, ES, CO, AE, US, NL, PT, ZA
  -- (GB, CN, CA were seeded in migration 0008.)
  -- Idempotent re-runs are safe: a duplicate guard on (region_code, tradition) prevents double-insert.

  CREATE UNIQUE INDEX IF NOT EXISTS co_region_tradition_unique
    ON cultural_origins (region_code, tradition);

  -- ── JAPAN ────────────────────────────────────────────────────────
INSERT INTO cultural_origins (region_code, domain, tradition, origin_summary, era, influences, connected_rule) VALUES
('JP', 'dining', 'Itadakimasu and Gochisousama', 'The pre-meal phrase ''itadakimasu'' (literally ''I humbly receive'') and the post-meal ''gochisousama deshita'' (''it was a feast'') are rooted in Buddhist and Shinto traditions of gratitude toward all beings — farmers, cooks, and the lives of plants and animals — that contributed to the meal. Codified in the Edo period (1603–1868) as everyday household practice, the phrases survived secularisation as a marker of cultivated respect for food and labour.', 'Edo period (1603–1868), with Buddhist roots', ARRAY['Buddhist non-harm doctrine', 'Shinto reverence for nature', 'Edo merchant household codes'], 'Say ''itadakimasu'' before eating and ''gochisousama deshita'' after; never begin before the host or eldest signals.'),
('JP', 'business', 'Meishi — The Business Card Ritual', 'The meishi (名刺) exchange ritual emerged from Edo-period merchant practice, in which a folded paper bearing one''s name and household seal was presented at first contact to establish standing. After the Meiji Restoration (1868) reorganised society around bureaucratic offices, the printed business card became the primary token of professional identity. The two-handed presentation, slight bow, and careful study of the received card preserve samurai-era protocols of formal introduction.', 'Edo through Meiji eras (17th–19th century)', ARRAY['Edo merchant household seals', 'Samurai introduction protocols', 'Meiji bureaucratic modernisation'], 'Receive a meishi with both hands and a slight bow. Read it carefully and place it respectfully on the table — never pocket it or write on it during the meeting.'),
('JP', 'greetings', 'Ojigi — The Bow', 'Ojigi (お辞儀) as a graduated communicative gesture descends from Heian-era (794–1185) court protocol, in which the depth and duration of a bow signalled relative rank with mathematical precision. The samurai class refined these distinctions; Meiji-era etiquette manuals codified them for the modern professional class. The eshaku (15°), keirei (30°), and saikeirei (45°+) bows persist in business and ceremonial life as a visible grammar of respect.', 'Heian through Meiji periods (8th–19th century)', ARRAY['Heian court protocol', 'Samurai rank etiquette', 'Meiji etiquette manuals'], 'Match the depth of your bow to the formality of the encounter. A slight nod suffices for casual greetings; deeper bows mark gratitude, apology, or respect for seniority.'),
('JP', 'gift-giving', 'Omiyage — Travel Gifts', 'The custom of bringing back small regional gifts (omiyage, お土産) from any trip began with Edo-period pilgrimages to shrines such as Ise. Pilgrims returned with sacred talismans for those who had financially supported the journey; the practice secularised into the obligation to bring colleagues and family region-specific sweets or crafts. The Japan National Railway''s 19th-century expansion industrialised the tradition by producing station-specific specialities at every major stop.', 'Edo period through Meiji railway era', ARRAY['Ise shrine pilgrimage tradition', 'Edo gift-economy reciprocity', 'Meiji railway commerce'], 'After any trip, bring small wrapped regional sweets or specialities for colleagues and close contacts — the gesture matters more than the value.'),
('JP', 'business', 'Honne and Tatemae', 'The distinction between honne (本音, true feeling) and tatemae (建前, the public face one shows) crystallised during the Tokugawa period (1603–1868), when rigid social hierarchies and the proximity of village life made overt disagreement socially destabilising. Confucian ethics absorbed from China reinforced harmony (wa, 和) as the supreme social virtue. Public restraint of personal opinion became — and remains — a mark of maturity and civic care.', 'Tokugawa period through modern era', ARRAY['Confucian harmony ethic', 'Tokugawa village proximity', 'Wa (collective harmony) doctrine'], 'Direct contradiction in public is rare. Read indirect signals carefully; a polite ''it is difficult'' (chotto muzukashii) typically signals refusal.')
ON CONFLICT (region_code, tradition) DO NOTHING;

-- ── GERMANY ────────────────────────────────────────────────────────
INSERT INTO cultural_origins (region_code, domain, tradition, origin_summary, era, influences, connected_rule) VALUES
('DE', 'business', 'Pünktlichkeit — Punctuality as Moral Duty', 'German punctuality has its roots in the Prussian state-building of Frederick the Great (r. 1740–1786), who imposed military timekeeping discipline on the civil service and educational system. The 19th-century industrial expansion under Bismarck institutionalised railway-time across the Reich. Lutheran and Reformed Protestant ethics framed reliable use of time as a moral obligation to one''s neighbour — making lateness a small theft from another''s day.', '18th–19th century (Prussian to Wilhelmine era)', ARRAY['Prussian military discipline', 'Lutheran work ethic', 'Bismarck-era industrial railway time'], 'Arrive precisely on time — neither early nor late. Notify the host immediately if delayed; unexplained tardiness is taken as disrespect.'),
('DE', 'greetings', 'Sie versus Du', 'The formal/informal address distinction (Sie/du) was codified in the 17th century as German absorbed French court influence, replacing the medieval Ihr-form. The Reformation reinforced ''du'' within congregations as a marker of shared brotherhood while ''Sie'' marked civic and professional distance. The 20th century saw uneven democratisation — universities and trades unions adopted ''du'' while the professions and bureaucracy retain ''Sie'' until explicitly invited otherwise.', '17th century onward', ARRAY['French court influence', 'Lutheran congregational equality', 'Wilhelmine bureaucratic formality'], 'Address adults as ''Sie'' and use last names with titles until explicitly invited to use ''du'' and first names. The invitation is a meaningful social gesture.'),
('DE', 'business', 'Sachlichkeit — Direct, Issue-Focused Speech', 'Sachlichkeit (''matter-of-factness'') emerged as an explicit cultural value in the Weimar Republic''s Neue Sachlichkeit movement of the 1920s, which prized objective, unsentimental clarity in art, architecture, and discourse. It built on a longer Enlightenment tradition (Kant, Hegel) of disciplined argument and on Lutheran plain-speech values. In business, Sachlichkeit manifests as direct critique of ideas — never confused with personal hostility.', '1920s Weimar era, with Enlightenment roots', ARRAY['Weimar Neue Sachlichkeit', 'Kantian rationalism', 'Lutheran plain-speech'], 'Direct critique of ideas is normal and not personal. Diplomatic hedging can read as evasive; clarity is a courtesy, not aggression.'),
('DE', 'dining', 'Guten Appetit and Mahlzeit', 'The pre-meal greeting ''Guten Appetit'' descends from the medieval Catholic monastic blessing of the table, which spread into secular use through the Holy Roman Empire. ''Mahlzeit'' (literally ''mealtime''), heard particularly at workplace canteens around midday, originated as a 19th-century industrial-era abbreviation of ''gesegnete Mahlzeit'' (''blessed mealtime''). Both phrases retain their function as small acknowledgements of shared hospitality.', 'Medieval through industrial era', ARRAY['Catholic monastic blessing', 'Holy Roman Empire dining custom', '19th-century industrial canteens'], 'Wait for the host''s ''Guten Appetit!'' before beginning to eat. Returning the greeting to others at the table is normal courtesy.'),
('DE', 'gift-giving', 'Even-Numbered Flowers Taboo', 'The custom of giving flowers in odd numbers (and never thirteen) and avoiding white chrysanthemums or lilies derives from German funerary tradition, in which even-numbered bouquets and these specific blooms are used at gravesites and memorials. The taboo crystallised in the 19th century as the bourgeois flower-giving custom became formalised in etiquette manuals alongside the rise of commercial florists.', '19th century (bourgeois etiquette codification)', ARRAY['Christian funerary tradition', '19th-century bourgeois etiquette', 'Florist trade conventions'], 'Give flowers in odd numbers (never thirteen). Avoid white chrysanthemums and white lilies — both carry funeral associations.')
ON CONFLICT (region_code, tradition) DO NOTHING;

-- ── FRANCE ────────────────────────────────────────────────────────
INSERT INTO cultural_origins (region_code, domain, tradition, origin_summary, era, influences, connected_rule) VALUES
('FR', 'greetings', 'La Bise — The Cheek Kiss', 'La bise — the light cheek-touch with a kiss sound — descends from the Roman ''osculum'', the formal greeting kiss between social equals. It survived in southern Provençal and Italianate court culture and spread through France during the 17th-century salon era as a marker of polite intimacy. The number of kisses (one to four) and starting cheek vary by region — a living folk-geography of French civility.', 'Roman through salon era (1st century BCE – 17th century)', ARRAY['Roman osculum greeting', 'Provençal Mediterranean culture', '17th-century salon civility'], 'Among acquaintances, greet with la bise — light cheek-touches with a kiss sound. Number and starting cheek vary by region; follow the local lead.'),
('FR', 'dining', 'Bread Direct on the Table', 'Placing bread directly on the tablecloth (rather than on a side plate) descends from medieval French dining, when bread served as both food and edible plate (''tranchoir'') for the rich sauces of the period. Even after porcelain plates became universal in the 18th century, the bread''s traditional place beside the main plate persisted. It is broken by hand, never cut with a knife — a residue of medieval table manners that valued the symbolism of breaking bread together.', 'Medieval through Ancien Régime', ARRAY['Medieval tranchoir tradition', 'Ancien Régime table service', 'Catholic bread symbolism'], 'Place your bread directly on the tablecloth beside your plate, and break it with your hands rather than cutting it with a knife.'),
('FR', 'business', 'Vouvoiement — Formal Address', 'The formal ''vous'' as default address for adults outside intimate circles was crystallised by the Académie française in the 17th century under Louis XIV, who codified court speech as a national standard. Cardinal Richelieu''s centralisation made Parisian court usage the model for all professional and bureaucratic life. Even today, the move from ''vous'' to ''tu'' is a deliberate, named act of intimacy (''on peut se tutoyer'').', '17th century (Académie française, Louis XIV court)', ARRAY['Académie française codification', 'Louis XIV court speech', 'Centralised Parisian standard'], 'Default to ''vous'' with all adults outside intimate circles. The shift to ''tu'' is a deliberate gesture; let the senior party invite it.'),
('FR', 'dining', 'The Apéritif Hour', 'The apéritif — a light pre-dinner drink with savoury bites — was popularised in 19th-century French café culture but draws on a longer Mediterranean tradition of preparing the stomach with bitter tonics. The Bourbon court formalised the timing (typically 18:00–20:00) as the social hinge between professional day and family evening. It remains a sacred interval in which conversation is light and unhurried before the main meal.', '19th century (café era), with Bourbon court roots', ARRAY['Mediterranean digestive tradition', 'Bourbon court timing', '19th-century café culture'], 'Accept the offer of an apéritif and treat it as an unhurried social interval — not as a prelude to be rushed through to dinner.'),
('FR', 'dress', 'Soigné — The Discipline of Appearance', 'The cultural premium on being ''soigné'' (well-groomed, considered in dress) was codified at Versailles under Louis XIV, who instructed the aristocracy that personal appearance was a public duty to the king. The 19th-century bourgeoisie inherited the principle and the Parisian fashion houses of the Belle Époque industrialised it. Even now, deliberate dress — even when casual — is read as basic respect for those around you.', '17th century Versailles through Belle Époque', ARRAY['Versailles court protocol', 'Bourgeois etiquette codification', 'Belle Époque Parisian fashion'], 'Dress with deliberate care even in casual contexts. Sloppy or thoughtless attire reads as disrespect for the company you keep.')
ON CONFLICT (region_code, tradition) DO NOTHING;

-- ── ITALY ────────────────────────────────────────────────────────
INSERT INTO cultural_origins (region_code, domain, tradition, origin_summary, era, influences, connected_rule) VALUES
('IT', 'dining', 'No Cappuccino After Eleven', 'The Italian rule against milky coffee after late morning rests on a long folk-medical tradition that warm milk taken on a full stomach impedes digestion. Cappuccino — named for the colour of Capuchin friars'' habits and popularised in 19th-century Vienna and Trieste — was always conceived as a breakfast drink. Post-meal coffee is a small espresso, taken standing at the bar in the rapid morning-or-evening rhythm of Italian café life.', '19th century onward (with folk-medical roots)', ARRAY['Italian folk-medical dietary tradition', 'Capuchin friar dress (linguistic origin)', 'Trieste–Vienna café culture'], 'Order cappuccino only at breakfast. After meals, take a small espresso — never milky coffee, which is read as a digestive misjudgement.'),
('IT', 'greetings', 'Bella Figura', 'Fare bella figura — ''cutting a fine figure'' — is the organising principle of Italian public life. It descends from Renaissance courtly virtue as set out in Castiglione''s Il Cortegiano (1528), in which grace, eloquence, and effortless self-presentation defined the cultivated person. The mercantile city-states (Venice, Florence) reinforced the principle as practical economic capital. To this day, presentation in dress, speech, and bearing is read as a moral marker of self-respect and respect for the company.', 'Renaissance onward (16th century)', ARRAY['Castiglione''s Il Cortegiano', 'Renaissance city-state mercantile culture', 'Catholic emphasis on visible virtue'], 'Public presentation matters — take care with dress, posture, and speech. Sloppiness in public is a small social failure.'),
('IT', 'dining', 'Pasta as Its Own Course', 'The Italian meal structure (antipasto, primo, secondo, contorno, dolce) was codified by 19th-century gastronome Pellegrino Artusi in his 1891 book La Scienza in Cucina, which standardised regional dishes into a national menu structure for the newly unified Italian state. Pasta as a primo (first course, never a side to meat) reflects the historical reality of pasta as the substantial dish for working families, with meat as a smaller separate luxury — an order Italians defend with quiet conviction.', '19th century (Risorgimento era)', ARRAY['Pellegrino Artusi''s La Scienza in Cucina', 'Risorgimento national culinary identity', 'Pre-industrial peasant meal economics'], 'Pasta is a course in itself, not a side dish to meat. Eat it before any meat course, and never with bread used to mop the plate at a formal table.'),
('IT', 'business', 'Family-First Negotiation', 'Italian business culture''s relational, family-centred quality has roots in the Roman patrimonial household (familia) and the Renaissance city-state guilds, in which trade was organised through extended kinship networks. The 19th-century failure of a strong central state in Italy reinforced the family and trusted personal network as the primary unit of economic trust — a pattern now reflected in the dominance of small and medium family-owned firms in the Italian economy.', 'Roman, Renaissance, and Risorgimento eras', ARRAY['Roman familia/patrimonial structure', 'Renaissance guild kinship networks', 'Weak post-Risorgimento central state'], 'Invest in personal relationships before pushing transactional details. Trust must be established person-to-person; deals follow trust, not the reverse.'),
('IT', 'gift-giving', 'Chrysanthemums for the Dead', 'In Italy, chrysanthemums are the funeral flower par excellence — exclusively associated with All Souls'' Day (2 November), when families place them on graves. The association solidified in the 19th century as the chrysanthemum, blooming in autumn, became the standard cemetery flower across Catholic Mediterranean Europe. Giving chrysanthemums to a living person is therefore deeply inauspicious, regardless of the giver''s intention.', '19th century (Catholic All Souls'' tradition)', ARRAY['Catholic All Souls'' Day cemetery custom', '19th-century florist trade conventions', 'Mediterranean autumn agricultural calendar'], 'Never give chrysanthemums as a gift — they are reserved for cemeteries and funerals. Roses or mixed bouquets are safe alternatives.')
ON CONFLICT (region_code, tradition) DO NOTHING;

-- ── BELGIUM ────────────────────────────────────────────────────────
INSERT INTO cultural_origins (region_code, domain, tradition, origin_summary, era, influences, connected_rule) VALUES
('BE', 'greetings', 'Three Kisses on the Cheek', 'Among friends and family, Belgian greeting traditionally involves three light cheek-touches — distinguishing it from the French two and the Dutch (variable) practice. The custom emerged in the 19th-century Catholic south as a formalised version of older Burgundian court greeting protocols. After the linguistic reorganisation of 1962 and the federalisation of Belgium (1993), the three-kiss greeting has become a quiet marker of shared Belgian identity across the linguistic divide.', '19th century, with Burgundian court roots', ARRAY['Burgundian court greeting protocols', 'Catholic southern European custom', 'Post-1993 federal Belgian identity'], 'Among friends, greet with three light cheek-touches. In business or with strangers, a handshake remains the safe default.'),
('BE', 'dining', 'Beer with Cuisine', 'Belgian beer culture''s pairing with food descends from the Trappist and other monastic brewing traditions that emerged in the 19th century after the Napoleonic suppression of monasteries was reversed. Monastic brewers like Westvleteren and Chimay produced beers explicitly intended to accompany meals — a tradition that elevated beer in Belgium to the status wine holds in France. UNESCO inscribed Belgian beer culture on its Intangible Cultural Heritage list in 2016.', '19th century (post-Napoleonic monastic revival)', ARRAY['Trappist monastic brewing', '19th-century monastery restoration', 'UNESCO Intangible Cultural Heritage recognition'], 'Treat beer as Belgians do — with the seriousness given to wine elsewhere. Each beer has a specific glass; refusing the glass is a small slight to the brewer.'),
('BE', 'business', 'Linguistic Neutrality', 'The 1962 language laws and the 1993 federal reorganisation formally divided Belgium into Dutch-speaking Flanders, French-speaking Wallonia, and bilingual Brussels. In professional contexts that cross linguistic boundaries — and especially in Brussels — neutral defaults (English, or carefully balanced French/Dutch) avoid being seen as politically partisan. Choosing the wrong language can read as taking sides in a long communal negotiation.', '1962 language laws through 1993 federalisation', ARRAY['1962 Belgian language laws', '1993 federal constitutional reform', 'Brussels institutional bilingualism'], 'Do not assume language by appearance. Open in English or ask which language is preferred — choosing wrong reads as a political statement.'),
('BE', 'dining', 'Frites — A National Heritage', 'The fried potato (frite) is claimed by Belgium as a 17th-century invention from the Meuse Valley, where villagers reportedly began frying thin-cut potatoes when winter ice prevented their usual fish-frying. The frituur or friterie — the standalone shop dedicated to frites — became a fixture of Belgian street life in the late 19th century and was inscribed on Belgium''s national heritage list in 2014 as a defining cultural institution.', '17th century onward (national heritage status 2014)', ARRAY['Meuse Valley fishing-village tradition', '19th-century urban friterie culture', 'Belgian national heritage policy'], 'Frites are a serious cultural matter. Eat them with mayonnaise (the Belgian default) rather than ketchup — and never call them ''French''.'),
('BE', 'gift-giving', 'Praline as the Gift Standard', 'The Belgian praline — a filled chocolate shell — was invented in 1912 by Jean Neuhaus II at his Brussels confectionery on the Galerie de la Reine. Within a generation, the boxed assortment (ballotin, also a Neuhaus invention) became Belgium''s universal social gift. To bring a box of pralines from a named maison (Neuhaus, Wittamer, Pierre Marcolini) to a host signals refined attention without flamboyance.', '20th century (1912 Neuhaus invention)', ARRAY['Jean Neuhaus II''s praline invention', 'Brussels luxury confectionery culture', 'Galerie de la Reine commercial tradition'], 'Bring a box of pralines from a named maison to any host — modest in size, refined in choice, never supermarket-grade.')
ON CONFLICT (region_code, tradition) DO NOTHING;

-- ── SWITZERLAND ────────────────────────────────────────────────────────
INSERT INTO cultural_origins (region_code, domain, tradition, origin_summary, era, influences, connected_rule) VALUES
('CH', 'business', 'Punctuality as Civic Virtue', 'Swiss punctuality has roots in Calvin''s Geneva of the 16th century, where reliable use of time was preached as a moral obligation to the community. The watchmaking industry that emerged in the Jura valleys in the 17th century made precision timekeeping a national craft and eventually a national identity. Federal railway unification in 1902 standardised time across the cantons; the SBB''s reputation for departures to the second became the visible everyday expression of a deeper civic ethic.', '16th century onward (Calvinist Geneva to federal era)', ARRAY['Calvinist Geneva work ethic', 'Jura watchmaking industry', '1902 federal railway unification'], 'Arrive precisely on time. Lateness is read not as casual but as a moral failure of consideration; notify immediately if delayed even by minutes.'),
('CH', 'greetings', 'Three Kisses or a Handshake', 'Swiss greeting practice splits along linguistic lines: in French-speaking Romandy, friends exchange three light cheek-touches in the Latin tradition; in German-speaking and Italian-speaking regions, a firm handshake (or a single kiss only among close family) prevails. The split was reinforced by the 1848 federal constitution that preserved cantonal cultural autonomy. Reading which greeting suits the context is a daily small exercise in Swiss multilingual fluency.', '19th century onward (1848 federal constitution)', ARRAY['Romandy Latin greeting tradition', 'Germanic cantonal reserve', '1848 federal cantonal autonomy'], 'Default to a firm handshake in business and across linguistic regions. Three cheek-touches are reserved for friends in French-speaking Switzerland.'),
('CH', 'dining', 'Fondue Communal Etiquette', 'Cheese fondue originated as Alpine peasant winter food in the Vaudois and Fribourg cantons, using stale bread and aged cheese — survival cuisine elevated to national symbol after a 1930s Swiss Cheese Union marketing campaign. The communal pot generated its own etiquette: never double-dip, never let bread drop into the pot (penalties from buying drinks to a cold dunk in the lake), and finish the crusty layer at the bottom (la religieuse) ceremonially.', 'Pre-modern Alpine, popularised in the 1930s', ARRAY['Alpine peasant winter cuisine', '1930s Swiss Cheese Union marketing', 'Communal village dining tradition'], 'Spear bread securely on the fork; never lose it in the pot, never double-dip, and join the ceremonial sharing of the crusty ''religieuse'' at the bottom.'),
('CH', 'business', 'Discretion and Privacy', 'Swiss discretion as a cultural and professional virtue was institutionalised by the 1934 Federal Act on Banks and Savings Banks, which made breach of banking confidentiality a criminal offence — partly to protect Jewish depositors fleeing Nazi Germany. The principle radiated outward: discussions of personal wealth, salaries, and political opinions are considered intrusive in ordinary social settings. Discretion, not disclosure, is the default mode of trust.', '20th century (1934 Banking Act onward)', ARRAY['1934 Federal Banking Act', 'Calvinist privacy norms', 'Multilingual federal restraint'], 'Avoid asking about salaries, wealth, or political views in social settings. Privacy is the default; volunteered disclosure marks unusual trust.'),
('CH', 'dress', 'Conservative Understatement', 'Swiss dress conservatism descends from Reformed (Zwinglian and Calvinist) sumptuary traditions of the 16th century, which preached modest attire as outward sign of inward piety. The mercantile prosperity of the 19th century did not produce a flashy dress culture — quality, durability, and discretion remained the markers of a well-judged wardrobe. Understated quality reads as competence; visible logos and conspicuous luxury read as unserious.', '16th century Reformation through modern era', ARRAY['Zwinglian and Calvinist sumptuary tradition', 'Mercantile durability ethic', 'Federal multilingual restraint'], 'Dress with quiet quality; visible logos and conspicuous luxury read as unserious. Understatement signals seriousness.')
ON CONFLICT (region_code, tradition) DO NOTHING;

-- ── SINGAPORE ────────────────────────────────────────────────────────
INSERT INTO cultural_origins (region_code, domain, tradition, origin_summary, era, influences, connected_rule) VALUES
('SG', 'dining', 'Hawker Centre Culture', 'Singapore''s hawker centres were created by the government from 1968 onward as it relocated street vendors into hygienic public food halls under the Hawkers Inquiry Commission. Far from killing the street food tradition, the policy preserved it — and in 2020 UNESCO inscribed Singapore''s hawker culture on its Intangible Cultural Heritage list. Reserving a seat with a packet of tissues (''chope'') is a uniquely Singaporean micro-etiquette born of the system.', '20th century (1968 hawker relocation onward; UNESCO 2020)', ARRAY['1968 Hawkers Inquiry Commission', 'Government public-housing policy', 'UNESCO Intangible Cultural Heritage 2020'], 'Reserve a hawker-centre seat by placing a packet of tissues on the table (''chope''). Return your tray after eating; the system runs on collective courtesy.'),
('SG', 'greetings', 'Multicultural Greeting Protocol', 'Singapore''s CMIO model (Chinese, Malay, Indian, Others) — formalised in the post-1965 nation-building decades under Lee Kuan Yew — institutionalised multi-ethnic equality. In greetings, this means matching the gesture to the recipient: a handshake universally, but a slight nod and right-hand-to-heart for traditional Malay Muslims, an Indian namaste where appropriate, and Chinese given/family-name conventions in business. Cultural switching is a Singaporean professional skill.', '20th century (post-1965 nation-building)', ARRAY['CMIO ethnic-policy framework', 'Lee Kuan Yew nation-building era', 'Post-1965 multicultural compact'], 'Match the greeting to the person — handshake by default, hand to heart for traditional Malay Muslims, namaste where culturally appropriate. Watch for cues.'),
('SG', 'business', 'Kiasu Mindset', '''Kiasu'' (Hokkien: ''afraid to lose'') is a Singaporean self-descriptor for the cultural drive to anticipate every contingency, queue early, and never be at a disadvantage. The trait was crystallised by the post-independence scarcity-anxiety of a small, resource-poor city-state and reinforced by the meritocratic competitive education system established under Lee Kuan Yew. It produces both Singapore''s famous efficiency and a recognisable national humour about itself.', 'Late 20th century (post-1965 era)', ARRAY['Hokkien Chinese linguistic inheritance', 'Post-independence scarcity-anxiety', 'Meritocratic education system'], 'Expect thorough preparation, early arrival, and detailed planning from Singaporean counterparts. Looking unprepared signals you are not taking the work seriously.'),
('SG', 'dining', 'Chopstick and Communal Eating Codes', 'Singapore''s predominantly ethnic-Chinese majority brought Southern Chinese (Hokkien, Teochew, Cantonese) dining codes — including the chopstick taboos against vertical placement (resembles funeral incense), pointing, and tapping the bowl. These codes coexist in hawker centres with Malay (right-hand only) and Indian (right-hand only, communal-plate) traditions. Knowing not to mix codes inappropriately is a marker of cultural fluency in shared public dining.', 'Inherited from Southern Chinese diaspora (19th century onward)', ARRAY['Hokkien/Teochew/Cantonese diaspora customs', 'Malay right-hand dining tradition', 'Indian Tamil dining tradition'], 'Never plant chopsticks vertically in rice, point with them, or tap the bowl. Use only the right hand when eating with Malay or Indian friends in traditional contexts.'),
('SG', 'business', 'Face — Mianzi in a Multicultural Frame', 'The Confucian concept of mianzi (face), inherited from Southern Chinese ancestry, was integrated into Singapore''s modern multicultural professional culture. Causing a counterpart to lose face publicly is the gravest negotiation error — disagreements are surfaced privately, often through trusted intermediaries. The principle is reinforced by Malay ''malu'' (shame-honour) and Indian respect-hierarchy norms, producing a cross-cultural consensus on indirect public conduct.', 'Confucian roots, post-independence multicultural application', ARRAY['Confucian mianzi (face)', 'Malay malu shame-honour code', 'Multicultural professional consensus'], 'Never publicly contradict, criticise, or correct a counterpart. Surface disagreement privately or through a trusted intermediary.')
ON CONFLICT (region_code, tradition) DO NOTHING;

-- ── INDIA ────────────────────────────────────────────────────────
INSERT INTO cultural_origins (region_code, domain, tradition, origin_summary, era, influences, connected_rule) VALUES
('IN', 'greetings', 'Namaste — The Anjali Mudra', 'Namaste — palms pressed together at heart level with a slight bow — is the anjali mudra (gesture of offering) drawn from Vedic and classical Hindu ritual, dating to at least the 2nd millennium BCE. The phrase ''Namaste'' (नमस्ते, ''I bow to you'') addresses the divine within the other. It is universal across age, gender, and caste, and its non-contact nature made it a culturally resonant national greeting through epidemic periods and beyond.', 'Vedic period onward (2nd millennium BCE)', ARRAY['Vedic ritual gesture vocabulary', 'Classical Hindu philosophy', 'Sanskrit greeting tradition'], 'Greet with palms pressed at heart level and a slight bow (''Namaste''). It is universally appropriate across age, gender, and region.'),
('IN', 'dining', 'Right Hand Only', 'Eating with the right hand only descends from Hindu, Jain, Sikh, and Muslim traditions of ritual purity, in which the left hand is reserved for personal hygiene and considered unclean for food contact. The codification appears in the Manusmriti (1st–3rd century CE) and parallel Islamic hadith traditions. The principle extends to passing dishes, accepting gifts, and giving money — using the right hand or both hands signals respect and ritual cleanliness.', 'Classical period onward (Manusmriti, hadith traditions)', ARRAY['Vedic-Hindu ritual purity', 'Islamic hadith on hand use', 'Jain non-violence and purity codes'], 'Eat, pass food, give money, and accept gifts with the right hand (or both hands) only. The left hand is considered ritually unclean for these.'),
('IN', 'gift-giving', 'No Leather Gifts', 'The taboo against leather gifts to Hindu hosts derives from the cow''s status as a sacred animal in Hinduism — a reverence dating to the Vedic period and codified in dharmic texts. Leather goods, particularly cowhide, are considered ritually polluting in many traditional households. Even modernised, urban Hindu families may quietly object; the safe gift defaults are sweets, dry fruits, fine textiles, or non-cow-leather goods.', 'Vedic period onward', ARRAY['Vedic cow-veneration tradition', 'Dharmic ahimsa (non-harm)', 'Brahminical purity codes'], 'Avoid leather gifts (especially cowhide) for Hindu hosts. Sweets, dry fruits, fine textiles, or quality non-leather goods are safe.'),
('IN', 'business', 'Hierarchy and Touching Feet', 'Indian respect for seniority — seen in the gesture of touching an elder''s feet (charan sparsh) — derives from Brahminical and broader dharmic traditions in which the elder embodies inherited wisdom and the family''s accumulated dharma. The gesture appears across the Ramayana and Mahabharata as a marker of righteous character. In professional life, the principle translates into deference to senior decision-makers, even when juniors hold technical expertise.', 'Vedic and epic periods onward', ARRAY['Brahminical respect hierarchy', 'Ramayana/Mahabharata dharmic models', 'Joint-family household structure'], 'Defer visibly to senior figures in meetings — address them first, let them speak first, and avoid contradicting them publicly even when correct.'),
('IN', 'dining', 'Vegetarianism by Community', 'Dietary practice in India varies sharply by community: many Hindus avoid beef, some are strictly vegetarian (often Brahmin, Vaishnava, or Jain communities); Muslims avoid pork and require halal meat; Jains additionally avoid root vegetables and eat only before sundown. Hosting requires careful inquiry, never assumption. The diversity reflects layered religious histories — Vedic, Buddhist, Jain, Islamic, and Sikh — rather than a single national norm.', 'Layered: Vedic, Jain, Islamic, Sikh historical periods', ARRAY['Hindu cow-reverence', 'Jain ahimsa and root-vegetable taboo', 'Islamic halal requirements'], 'Never assume dietary practice. Ask in advance about beef, pork, alcohol, and vegetarianism — and respect Jain restrictions on root vegetables and eating after sundown.')
ON CONFLICT (region_code, tradition) DO NOTHING;

-- ── MEXICO ────────────────────────────────────────────────────────
INSERT INTO cultural_origins (region_code, domain, tradition, origin_summary, era, influences, connected_rule) VALUES
('MX', 'greetings', 'El Abrazo — The Embrace', 'Mexican greeting culture combines an Iberian Mediterranean warmth with indigenous Mesoamerican hospitality codes. Among friends and trusted business contacts, men commonly greet with an abrazo — a brief embrace with back-pats — and women with a single cheek-kiss. The gesture inherits the 16th-century Spanish colonial saludo and the older tradition of physical hospitality central to many indigenous Mexican communities. Refusing the abrazo from a friend reads as cold or distrustful.', 'Colonial era onward (16th century)', ARRAY['Spanish Iberian saludo', 'Mesoamerican hospitality traditions', 'Catholic communal warmth'], 'Among acquaintances, accept the abrazo (men) or single cheek-kiss (women). A handshake-only response from a friend reads as unusually cold.'),
('MX', 'dining', 'Sobremesa', 'Sobremesa — the unhurried conversation that lingers at the table after the meal — is an Iberian inheritance reinforced in Mexico by the centrality of family gathering and the Catholic communal culture of the colonial period. Standing up to leave too quickly after eating reads as treating the meal as transactional rather than relational. In business, the sobremesa is often where the real relationship is built.', 'Iberian colonial inheritance onward', ARRAY['Spanish Iberian dining tradition', 'Catholic communal family culture', 'Hacienda-era hospitality'], 'Linger at the table after the meal for unhurried conversation. Standing up promptly to leave is read as transactional and cold.'),
('MX', 'business', 'Personalismo', 'Personalismo — preferring trusted persons over formal institutions — has its roots in the colonial encomienda and hacienda systems, in which loyalty ran through the patrón rather than the distant Spanish crown. Even in modern professional life, business is conducted through relationships of mutual personal trust; institutional contracts complement but do not replace the bond between principals. New introductions ideally come through a trusted mutual contact.', 'Colonial era through modern era', ARRAY['Encomienda and hacienda patrón systems', 'Catholic compadrazgo (godparent) networks', 'Weak institutional trust legacy'], 'Introductions through trusted mutual contacts open doors institutional approaches do not. Invest in personal relationship before pushing transactional details.'),
('MX', 'gift-giving', 'Marigolds for Día de los Muertos', 'Marigolds (cempasúchil) in Mexico are inseparable from Día de los Muertos (1–2 November), in which their orange petals are scattered to guide the spirits of the dead home. The flower''s sacred-funerary role in the indigenous Aztec religion was preserved through Catholic syncretism after the conquest. Giving marigolds outside this context is therefore inappropriate — they are read as a flower of mourning, not friendship.', 'Pre-Columbian Aztec onward (with Catholic syncretism)', ARRAY['Aztec sacred-funerary flower tradition', 'Catholic All Souls'' syncretism', 'Día de los Muertos public ritual'], 'Avoid marigolds as social gifts — they are reserved for Día de los Muertos and grave offerings. Roses, orchids, or mixed bouquets are appropriate.'),
('MX', 'greetings', 'Don and Doña Honorifics', 'The honorifics ''Don'' (for men) and ''Doña'' (for women), used with the first name, descend from the Spanish Castilian usage that arrived with the conquest in the 16th century. Originally restricted to nobility, they democratised in colonial New Spain to mark senior, respected, or accomplished persons regardless of formal title. Using ''Don'' or ''Doña'' for an elder or a respected senior signals warm respect that the cooler ''Señor/Señora'' lacks.', 'Colonial Spanish onward (16th century)', ARRAY['Castilian noble honorifics', 'Colonial democratisation in New Spain', 'Catholic social hierarchy'], 'Address respected elders and senior figures as ''Don [first name]'' or ''Doña [first name]'' — warmer than ''Señor/Señora'' and a deliberate gesture of regard.')
ON CONFLICT (region_code, tradition) DO NOTHING;

-- ── BRAZIL ────────────────────────────────────────────────────────
INSERT INTO cultural_origins (region_code, domain, tradition, origin_summary, era, influences, connected_rule) VALUES
('BR', 'greetings', 'Cheek Kissing', 'Brazilian cheek-kissing varies by region: one in São Paulo, two in Rio de Janeiro, three in Minas Gerais. The custom blends Portuguese Iberian greeting tradition with the warmth of West African hospitality cultures brought through the colonial period. Even in initial meetings between women (and often between men and women), the kiss precedes the handshake. Refusing it from an acquaintance reads as unusually distant.', 'Colonial era through modern era', ARRAY['Portuguese Iberian greeting', 'West African hospitality traditions', 'Catholic communal warmth'], 'Greet women with one to three cheek-kisses depending on region — São Paulo (one), Rio (two), Minas (three). Watch the local lead.'),
('BR', 'business', 'Jeitinho Brasileiro', 'The ''jeitinho brasileiro'' — the small inventive workaround that bypasses formal obstacles — is a national self-descriptor analysed by sociologist Roberto DaMatta in his 1986 work A Casa e a Rua. It descends from the colonial reality of distant Portuguese law and present local power, in which informal personal arrangements were often the only practical way to act. Today it remains both celebrated as Brazilian creativity and critiqued as a corruption hazard.', 'Colonial era onward (analytical framing 1980s)', ARRAY['Colonial distance from Portuguese institutions', 'Roberto DaMatta sociological analysis', 'Patron-client cultural inheritance'], 'Expect informal workarounds and personal accommodations to be offered as solutions. Demand for rigid procedural correctness can read as cold or naive.'),
('BR', 'dining', 'Long, Hosted Meals', 'The extended, multi-course meal anchored by family or trusted friends is a Portuguese Mediterranean inheritance reinforced by the colonial casa-grande tradition of large hospitality at the plantation house. Even in modern urban Brazil, business meals run long, conversation ranges far beyond the immediate transaction, and the host''s choice of restaurant and orchestration of the table is a meaningful gesture of regard.', 'Colonial casa-grande tradition onward', ARRAY['Portuguese Iberian dining culture', 'Colonial casa-grande hospitality', 'Catholic communal meal tradition'], 'Allow business meals to run long. Conversation will roam well beyond the immediate transaction; rushing to the deal points reads as crass.'),
('BR', 'business', 'The Cordial Brazilian', 'Sergio Buarque de Holanda''s 1936 essay Raízes do Brasil identified the ''cordial Brazilian'' — the personality whose social warmth dissolves formal institutional distance — as a defining national type. The cordiality is not insincere but reflects a culture in which professional and personal life are deeply intertwined, and in which the affective register of a relationship governs the business it can support.', '20th century framing of older cultural patterns', ARRAY['Sergio Buarque de Holanda''s Raízes do Brasil', 'Patron-client colonial inheritance', 'Catholic affective community tradition'], 'Invest in the affective register of the relationship — warmth, personal interest, shared social time. Cold professionalism limits what business can be done.'),
('BR', 'dress', 'Cuidado — Care in Appearance', 'The cultural premium on a ''cuidado'' (well-cared-for) appearance descends from the urban beach-and-promenade culture of 19th-century Rio de Janeiro and the broader Iberian-Mediterranean attention to public presentation. Even in casual or hot-climate contexts, deliberate grooming, fitted clothes, and clean shoes signal self-respect; thoughtless dress is read as a small disrespect for the people one will encounter.', '19th century urban Brazil onward', ARRAY['Iberian Mediterranean dress tradition', '19th-century Rio promenade culture', 'Tropical urban grooming norms'], 'Even in hot climates and casual contexts, dress with deliberate care — fitted clothes, clean shoes, considered grooming. Thoughtless dress reads as disrespect.')
ON CONFLICT (region_code, tradition) DO NOTHING;

-- ── SPAIN ────────────────────────────────────────────────────────
INSERT INTO cultural_origins (region_code, domain, tradition, origin_summary, era, influences, connected_rule) VALUES
('ES', 'dining', 'Sobremesa — Lingering at the Table', 'Sobremesa — the conversation that follows the meal, often as long as the meal itself — is a defining Spanish social institution dating to medieval Castilian and Andalusian table culture. The hours after lunch, especially on weekends, are reserved for unhurried family or friend conversation, often with coffee or a digestif. Standing to leave promptly is read as cold; to be invited to a sobremesa is to be folded into trusted social space.', 'Medieval through modern era', ARRAY['Medieval Castilian dining tradition', 'Andalusian café and tavern culture', 'Catholic communal time'], 'After meals, expect and join the sobremesa — unhurried conversation, often with coffee or a digestif. Leaving promptly reads as cold.'),
('ES', 'dining', 'Tapas as Social Ritual', 'The tapa originated in 19th-century Andalusian tavern culture, where a small dish (''tapa'', cover) was placed over a glass of sherry to keep flies out and to encourage drinkers to eat. The custom spread north through Spain and evolved into the modern tapeo — moving between bars for small plates and conversation. The tapeo''s social function is communal flow rather than meal: standing, sharing, and circulating matter as much as the food itself.', '19th century Andalusia onward', ARRAY['Andalusian sherry tavern tradition', 'Iberian small-plate custom', 'Mediterranean social drinking culture'], 'On a tapeo, expect to move between bars rather than settle. Share plates from the centre, stand or stay light, and treat conversation as the main course.'),
('ES', 'greetings', 'Two-Cheek Kiss', 'Among friends and family, Spanish greeting is two light cheek-touches — left cheek first, then right — with a kiss sound. The custom shares the broader Mediterranean Roman ''osculum'' tradition and persisted as a marker of warm intimacy through Spain''s diverse regional cultures. Business introductions among strangers default to a firm handshake; the kiss is reserved for personal warmth.', 'Roman through modern era', ARRAY['Roman osculum tradition', 'Mediterranean regional culture', 'Catholic communal warmth'], 'Among friends, greet women (and women greeting men) with two light cheek-touches starting on the left. Handshakes remain default for business strangers.'),
('ES', 'business', 'The Late Schedule', 'Spain''s distinctively late daily schedule — lunch at 14:00–15:30, dinner at 21:00–22:30 — was reinforced in 1940 when Franco moved Spain into Central European Time to align with Nazi Germany, despite Spain''s geographical position aligning with GMT. The clock shifted, but the solar-aligned daily rhythm did not, leaving Spain perpetually ''one hour late'' relative to its time zone. The pattern is cultural infrastructure now — meetings and meals reflect it.', 'Reinforced by 1940 timezone shift', ARRAY['1940 Franco timezone alignment with Berlin', 'Mediterranean siesta tradition', 'Solar-aligned agricultural rhythms'], 'Plan around the late schedule — lunch at 14:00–15:30, dinner from 21:00 onward. Proposing a 19:00 dinner reads as oddly early.'),
('ES', 'gift-giving', 'Wine Etiquette and Flower Taboos', 'Spanish gift-giving conventions for hosts include good-quality wine (or cava), boxed sweets, or flowers — with care to avoid yellow flowers (linked to ill-luck and historically to the Inquisition''s penitential garments) and chrysanthemums (cemetery flowers, as across Catholic Mediterranean Europe). The taboos are old enough that even non-superstitious Spaniards observe them; younger urban hosts may not, but the safe path is to default away from yellow.', 'Inquisition-era origins through modern florist conventions', ARRAY['Inquisition penitential symbolism', 'Catholic All Souls'' chrysanthemum tradition', 'Iberian florist conventions'], 'Bring wine, cava, or quality boxed sweets to a host. Avoid yellow flowers (ill-luck) and chrysanthemums (cemetery) when choosing a bouquet.')
ON CONFLICT (region_code, tradition) DO NOTHING;

-- ── COLOMBIA ────────────────────────────────────────────────────────
INSERT INTO cultural_origins (region_code, domain, tradition, origin_summary, era, influences, connected_rule) VALUES
('CO', 'greetings', 'Buenos Días Formality', 'Colombian social interaction is anchored by the obligatory ''Buenos días'' / ''Buenas tardes'' / ''Buenas noches'' greeting on entering shops, lifts, taxis, or any shared space. The practice descends from Catholic Spanish colonial culture and is reinforced in Colombia by a particularly formal Andean Spanish that takes politeness as a marker of upbringing (''una buena educación''). Skipping the greeting reads as not just rude but badly raised.', 'Colonial Spanish onward', ARRAY['Catholic Spanish colonial culture', 'Andean formal Spanish tradition', 'Bogotá highland courtesy norms'], 'Greet on entering any shared space — shop, lift, taxi, waiting room — with ''Buenos días'' or the time-appropriate equivalent. Skipping it reads as badly raised.'),
('CO', 'business', 'Universal Use of ''Usted''', 'Unusually for Latin America, Colombian Spanish (especially in Bogotá and the Andean interior) often uses the formal ''usted'' even within families and between close friends — a practice descended from colonial Castilian formality preserved more strongly in Colombia than in most other Spanish-speaking countries. The Colombian Academy of Language has documented this distinct norm. In business, ''usted'' is the default and persists through long professional relationships.', 'Colonial onward (preserved more strongly than regional peers)', ARRAY['Colonial Castilian formality', 'Andean highland courtesy preservation', 'Colombian Academy of Language norms'], 'Use ''usted'' as the default with all adults — including in long-standing professional relationships. Switching to ''tú'' is unusual and personal.'),
('CO', 'dining', 'Tinto Coffee Culture', 'The ''tinto'' — a small black coffee, taken many times a day — is the structuring social ritual of Colombian work and hospitality. Coffee cultivation expanded across the central Andes from the 1850s and built modern Colombia''s economic and cultural backbone; by the 20th century, the Federación Nacional de Cafeteros had codified coffee as national identity. Offering tinto to a visitor is the basic gesture of welcome; refusing repeatedly is read as standoffish.', '19th century coffee expansion onward', ARRAY['19th-century Andean coffee economy', 'Federación Nacional de Cafeteros cultural work', 'Spanish hospitality tradition'], 'Accept the offer of tinto — the small black coffee — when a Colombian host or office offers it. It is the basic gesture of welcome.'),
('CO', 'business', 'Personalismo and Patience', 'Colombian business culture, like much of Latin America, is built on personal trust before transactional detail — a heritage of colonial encomienda relationships and Catholic compadrazgo (godparenthood) networks of obligation. Meetings often open with substantial personal conversation, decisions move at relationship-pace, and pushing for closure too quickly can damage rather than accelerate the deal.', 'Colonial era through modern era', ARRAY['Encomienda patron-client tradition', 'Catholic compadrazgo networks', 'Andean formal courtesy culture'], 'Open meetings with genuine personal conversation. Pushing for closure too quickly can damage rather than accelerate a Colombian deal.'),
('CO', 'gift-giving', 'Funeral Flower Taboos', 'As across Catholic Mediterranean and Latin culture, marigolds and lilies in Colombia carry funeral and All Souls'' associations and are inappropriate as social gifts. Roses (especially red and yellow), tulips, and orchids — Colombia''s national flower — are safe and welcomed choices. The country''s prominence as a global cut-flower exporter means quality fresh flowers are expected when given.', 'Catholic colonial tradition through modern florist trade', ARRAY['Catholic All Souls'' tradition', 'Colombian cut-flower export industry', 'Andean orchid cultural symbolism'], 'Avoid lilies and marigolds (funeral flowers). Roses, tulips, or orchids — the national flower — are safe and welcomed.')
ON CONFLICT (region_code, tradition) DO NOTHING;

-- ── UAE ────────────────────────────────────────────────────────
INSERT INTO cultural_origins (region_code, domain, tradition, origin_summary, era, influences, connected_rule) VALUES
('AE', 'greetings', 'Right Hand Only', 'The Emirati and broader Islamic practice of using the right hand for greetings, eating, and giving derives from the hadith traditions of the Prophet Muhammad, in which the left hand is reserved for personal hygiene and considered ritually impure for these acts. The principle, codified in the early Islamic period (7th century), governs handshakes, the acceptance of gifts and food, and the giving of business cards. Use of the left hand reads as a basic failure of cultural awareness.', 'Early Islamic period onward (7th century)', ARRAY['Hadith of the Prophet Muhammad', 'Islamic ritual purity codes', 'Bedouin tribal hospitality customs'], 'Use the right hand only for handshakes, accepting gifts and food, giving business cards, and eating. The left hand is ritually inappropriate for these acts.'),
('AE', 'business', 'The Majlis', 'The majlis (literally ''sitting place'') is the traditional Bedouin council in which tribal leaders heard petitions, mediated disputes, and built consensus — a practice UNESCO inscribed on its Intangible Cultural Heritage list in 2015. In modern Emirati business, the majlis survives as the unhurried opening conversation in a meeting room or sheikh''s reception, in which the relationship is established before any transactional content. Skipping the majlis reads as crass and Western.', 'Pre-Islamic Bedouin onward (UNESCO 2015 recognition)', ARRAY['Pre-Islamic Bedouin council tradition', 'Islamic shura (consultation) principle', 'UNESCO Intangible Cultural Heritage 2015'], 'Settle into the majlis-style opening conversation patiently. Pushing to business content too quickly violates the customary order of relationship before transaction.'),
('AE', 'dining', 'Coffee and Dates — Gahwa Hospitality', 'The serving of Arabic coffee (gahwa) and dates is the founding gesture of Emirati and broader Gulf Arab hospitality, descended from Bedouin desert tradition where offering food and drink to any visitor — friend or stranger — was a sacred obligation. UNESCO inscribed Arabic coffee culture in 2015. The gahwa pourer waits for the guest to gently shake the small cup side-to-side to signal that no more is wanted.', 'Pre-Islamic Bedouin onward (UNESCO 2015)', ARRAY['Bedouin desert hospitality obligation', 'Yemeni–Ethiopian coffee origins', 'UNESCO Intangible Cultural Heritage 2015'], 'Accept the offered gahwa and dates; refusal reads as refusal of hospitality. Signal you have had enough by gently shaking the small cup side-to-side.'),
('AE', 'gift-giving', 'No Alcohol or Pork', 'Islamic dietary prohibitions on alcohol (khamr) and pork are foundational, set out in the Qur''an and reinforced through hadith. While alcohol is available to non-Muslims in licensed venues across the UAE, gifting alcohol or pork products to an Emirati host is inappropriate regardless of personal observance level — the gesture itself transgresses the religious-cultural boundary. Safe gifts include high-quality dates, Arabic sweets, perfumes (oud, attar), and fine textiles.', 'Islamic foundational era (7th century)', ARRAY['Qur''anic prohibition of khamr and pork', 'Hadith dietary codification', 'Gulf Arab gift traditions'], 'Never gift alcohol or pork products to an Emirati host. Quality dates, Arabic sweets, oud or attar perfumes, and fine textiles are safe and welcomed.'),
('AE', 'dress', 'Modest Attire', 'Emirati expectations of modest dress descend from Islamic principles of haya (modesty) set out in the Qur''an and hadith, and reinforced by Gulf Arab cultural codes. For visitors, this means covered shoulders and knees in public spaces, conservative business attire (full suit, long sleeves) in professional contexts, and additional covering at mosques and government buildings. The standard tightens further during Ramadan.', 'Islamic foundational era onward', ARRAY['Qur''anic principle of haya (modesty)', 'Gulf Arab cultural conservatism', 'Tribal honour codes around presentation'], 'Cover shoulders and knees in public; wear conservative business attire (full suit) for professional meetings. Tighten the standard further at mosques and during Ramadan.')
ON CONFLICT (region_code, tradition) DO NOTHING;

-- ── UNITED STATES ────────────────────────────────────────────────────────
INSERT INTO cultural_origins (region_code, domain, tradition, origin_summary, era, influences, connected_rule) VALUES
('US', 'greetings', 'The Firm Handshake', 'The American firm handshake as a marker of trustworthy character descends from a confluence of Quaker plain-dealing tradition (which preferred the handshake to deferential bows or hat-doffings as a mark of human equality) and 19th-century military and frontier culture, in which a confident grip signalled reliable character to strangers. The ''firm'' qualifier became a near-universal piece of American business advice by the early 20th century.', '17th-century Quaker through 20th-century business culture', ARRAY['Quaker egalitarian plain-dealing', '19th-century frontier character culture', '20th-century American business advice tradition'], 'Offer a firm — not crushing — handshake with direct eye contact. A weak grip is read as evasive or low-confidence.'),
('US', 'business', 'First-Name Basis', 'The American default to first names, even across hierarchies, descends from frontier egalitarianism and from the post-WWII corporate culture that explicitly broke with European formality as a marker of American managerial modernity. Quaker and Methodist plain-speech traditions reinforced the pattern. The first-name default is now so standard that excessive formality (Mr/Ms, titles) can read as cold or oddly hierarchical in mainstream American professional life.', 'Frontier era through post-WWII corporate culture', ARRAY['Frontier egalitarian tradition', 'Quaker and Methodist plain-speech', 'Post-WWII American corporate informality'], 'Use first names as the default in American professional contexts. Excessive Mr/Ms formality reads as oddly cold or hierarchical.'),
('US', 'dining', 'Tipping Culture', 'American tipping culture descends from post-Civil War Reconstruction, when restaurant and railway employers used the European tip — until then a discretionary gratuity — as a substitute for paying newly-freed Black workers a wage. The 1938 Fair Labor Standards Act formalised the ''tipped minimum wage'', binding restaurant economics to customer-paid gratuities. The 15–20% (now 20–25%) standard is therefore not optional in the way many international visitors assume — staff income depends on it.', 'Post-Civil War onward (formalised 1938 FLSA)', ARRAY['Post-Reconstruction wage suppression', 'European discretionary tip imported and transformed', '1938 Fair Labor Standards Act tipped minimum wage'], 'Tip 18–22% on restaurant bills as standard, not as exceptional reward. Staff wages legally depend on it; under-tipping has real economic consequences.'),
('US', 'business', 'Direct Yes/No Communication', 'American directness in professional speech — explicit yes/no answers, surfaced disagreement, and stated preferences — draws on Quaker plain-speech, frontier pragmatism, and the 20th-century management theory tradition (Drucker, Deming) that prized clear communication as operational necessity. Indirect or hedged answers, common in many cultures as politeness, can read in American contexts as evasive or untrustworthy.', 'Quaker through 20th-century management tradition', ARRAY['Quaker plain-speech tradition', 'Frontier pragmatic communication', '20th-century American management theory'], 'Give clear, explicit yes/no answers. Hedged or indirect responses, polite elsewhere, can read in American business contexts as evasive or untrustworthy.'),
('US', 'dining', 'The Doggy Bag', 'Taking home uneaten restaurant food in a ''doggy bag'' was normalised during the Great Depression of the 1930s as a thrift practice and accelerated by post-war American restaurant portion sizes. Unlike many cultures where leaving leftovers signals satiation and respect for the host, the American norm treats taking food home as practical respect for the food itself and for one''s own household. Asking for a ''box'' or ''to go'' is entirely standard at all but the most formal restaurants.', 'Great Depression onward (1930s)', ARRAY['Great Depression thrift culture', 'Post-war American portion inflation', 'Protestant anti-waste ethic'], 'It is normal and unembarrassing to ask for a ''to-go box'' for uneaten restaurant food. Doing so signals practical respect, not poor manners.')
ON CONFLICT (region_code, tradition) DO NOTHING;

-- ── NETHERLANDS ────────────────────────────────────────────────────────
INSERT INTO cultural_origins (region_code, domain, tradition, origin_summary, era, influences, connected_rule) VALUES
('NL', 'business', 'Going Dutch', 'The phrase ''going Dutch'' — splitting a bill evenly — reflects a deep Dutch cultural preference, rooted in Calvinist thrift and a long mercantile-republican tradition of equality among trading partners. The 17th-century Dutch Republic''s commercial culture treated mutual financial independence as a guarantor of free relationships; one party paying for another could create unwelcome obligation. Even in dating, splitting bills is unremarkable; in business, expense-sharing among peers is the norm.', '17th-century Dutch Republic onward', ARRAY['Calvinist thrift tradition', 'Dutch Republic mercantile equality', 'Anti-obligation independence ethic'], 'Expect bills to be split evenly with peers, including in business. One party covering the whole bill can create unwelcome sense of obligation.'),
('NL', 'greetings', 'Three Cheek-Kisses Among Friends', 'Among Dutch friends and family — particularly in the Catholic south — greetings between women (and between men and women) involve three light cheek-touches, alternating sides. The custom is informal and contextual: in the Calvinist north and in business, the firm handshake remains default. The split mirrors the older religious-cultural geography of the Netherlands between Catholic Brabant/Limburg and Protestant Holland.', 'Older Catholic-Protestant cultural divide', ARRAY['Catholic southern Dutch greeting tradition', 'Calvinist northern reserve', 'Burgundian Low Countries inheritance'], 'Three cheek-touches are reserved for friends and family, more common in the Catholic south. Default to a firm handshake in business and with strangers.'),
('NL', 'greetings', 'Direct Speech as Respect', 'Dutch directness as a positive social value descends from Calvinist plain-speech tradition (16th-century Reformation), reinforced by the egalitarian mercantile culture of the Dutch Republic in which direct dealing among equals was a guarantor of trust. Indirect or diplomatic hedging is read in Dutch culture not as politeness but as evasion — the assumption is that an honest counterpart will tell you what they think.', '16th-century Reformation onward', ARRAY['Calvinist plain-speech tradition', 'Dutch Republic mercantile equality', 'Anti-aristocratic civic culture'], 'Direct critique and clear yes/no answers are read as respect, not aggression. Diplomatic hedging is read as evasive and lowers, not raises, trust.'),
('NL', 'business', 'Polderen — Consensus Decision-Making', 'The ''poldermodel'' of consensus-seeking decision-making takes its name from the historical necessity of cooperation among landholders in the Dutch polders (reclaimed lowland), where any party''s neglect of the dykes could flood the others'' land. Medieval water boards (waterschappen, dating to the 13th century) were among Europe''s earliest proto-democratic institutions. The principle — patient negotiation until all relevant parties can accept the outcome — survives in modern Dutch boards, government, and corporate governance.', 'Medieval water boards (13th century) onward', ARRAY['Medieval waterschap (water board) governance', 'Calvinist consensus tradition', '20th-century neo-corporatist labour relations'], 'Expect patient consensus-building rather than top-down decisions. Pushing for unilateral closure can damage rather than accelerate Dutch decision-making.'),
('NL', 'gift-giving', 'Modest Gifts Only', 'Dutch gift conventions favour the modest and considered — flowers, a bottle of wine, a book — over the lavish or expensive. The preference descends from the same Calvinist anti-ostentation tradition that shaped Dutch dress, architecture, and dining. Expensive gifts can read not as generous but as inappropriate — even faintly suspicious of currying favour. The cultural maxim ''doe maar gewoon, dan doe je al gek genoeg'' (''just act normal — that''s already odd enough'') captures the principle.', '16th-century Reformation onward', ARRAY['Calvinist anti-ostentation tradition', 'Mercantile understatement', 'Egalitarian civic culture'], 'Bring modest, considered gifts to a Dutch host — flowers, wine, a book. Lavish or expensive gifts read as inappropriate or even suspect.')
ON CONFLICT (region_code, tradition) DO NOTHING;

-- ── PORTUGAL ────────────────────────────────────────────────────────
INSERT INTO cultural_origins (region_code, domain, tradition, origin_summary, era, influences, connected_rule) VALUES
('PT', 'dining', 'Bacalhau — The National Cod', 'Portugal has a famously enormous repertoire of bacalhau (salt cod) dishes — said to number 365, one for each day of the year. The tradition descends from the 15th–16th-century Portuguese Atlantic exploration, when fleets fishing the Newfoundland Grand Banks brought home salt-preserved cod that became central to Catholic fast-day cuisine. Even today, Christmas Eve dinner is traditionally bacalhau cozido — a culinary continuity that links modern Portugal to its Age of Exploration heritage.', '15th–16th-century Atlantic exploration onward', ARRAY['Portuguese Atlantic cod fishing', 'Catholic fast-day cuisine', 'Age of Exploration trade economics'], 'Bacalhau is the national dish — accept and enjoy when offered. Christmas Eve bacalhau cozido is a culinary continuity treated with quiet seriousness.'),
('PT', 'greetings', 'Two Cheek-Kisses Among Women', 'Among friends and family, Portuguese greeting between women — and between women and men — involves two light cheek-touches, starting on the right cheek (the reverse of the Spanish convention). The custom shares the broader Iberian Mediterranean Roman tradition. Business introductions and male-male meetings default to a firm handshake; the kisses are reserved for established personal warmth.', 'Roman Mediterranean tradition through modern era', ARRAY['Roman osculum greeting', 'Iberian Mediterranean greeting culture', 'Catholic communal warmth'], 'Greet women friends with two light cheek-touches starting on the right cheek. Default to a firm handshake in business and male-male meetings.'),
('PT', 'business', 'Saudade-Inflected Pace', 'Portuguese professional pace runs slower than Northern European norms — a quality often ascribed culturally to ''saudade'', the Portuguese-Galician concept of melancholic longing that values reflection, depth, and the long view. The trait has practical roots in the Iberian Mediterranean tradition of relationship-first business and in Portugal''s historical position as Europe''s western edge, oriented toward a slower Atlantic and African pace rather than continental urgency.', 'Iberian Mediterranean tradition', ARRAY['Saudade reflective cultural concept', 'Iberian Mediterranean relationship-first culture', 'Atlantic-oriented historical pace'], 'Allow more time than Northern European norms suggest. Pushing for fast closure can damage relationship-first Portuguese business pace.'),
('PT', 'dining', 'Late Dinner Schedule', 'Portuguese dinner runs later than most of Northern Europe — typically from 20:00 onward, with restaurant kitchens often busiest at 21:00–22:00. The schedule reflects the broader Iberian Mediterranean rhythm shared with Spain, modulated by Portugal''s correct geographical positioning in GMT (unlike Spain, which shifted to CET in 1940). Proposing a 19:00 dinner reads as oddly early; the cultural prime time is later.', 'Iberian Mediterranean tradition', ARRAY['Iberian Mediterranean meal rhythm', 'Solar-aligned daily schedule', 'Catholic late-evening sociability'], 'Plan dinner for 20:00 or later — restaurant kitchens are often busiest at 21:00–22:00. Earlier proposals read as oddly hurried.'),
('PT', 'gift-giving', 'Avoid Lilies and Red Flowers', 'As across Catholic Mediterranean Europe, Portuguese florist tradition reserves lilies and chrysanthemums for funerals and All Souls'' Day cemetery offerings. Red flowers, particularly red carnations, additionally carry strong political associations with the 1974 Carnation Revolution — appropriate to the date, but charged in everyday gift contexts. Safe choices for hosts include mixed bouquets, roses (other than red), or potted plants.', 'Catholic Mediterranean tradition; 1974 political layer', ARRAY['Catholic All Souls'' chrysanthemum tradition', '1974 Carnation Revolution political symbolism', 'Iberian florist conventions'], 'Avoid lilies and chrysanthemums (funeral flowers) and red carnations (1974 Carnation Revolution association). Mixed bouquets or potted plants are safe.')
ON CONFLICT (region_code, tradition) DO NOTHING;

-- ── SOUTH AFRICA ────────────────────────────────────────────────────────
INSERT INTO cultural_origins (region_code, domain, tradition, origin_summary, era, influences, connected_rule) VALUES
('ZA', 'greetings', 'Multilingual Greeting', 'South Africa''s 1996 Constitution recognises eleven official languages — Zulu, Xhosa, Afrikaans, English, Sepedi, Setswana, Sesotho, Tsonga, Swati, Venda, Ndebele — each with significant speaker populations. Among South Africans, exchanging a greeting in the other person''s home language (''Sawubona'' in Zulu, ''Molo'' in Xhosa, ''Goeie dag'' in Afrikaans) is a small but powerful gesture of post-apartheid civic respect. English alone is comprehensible everywhere but reads as the least personally invested choice.', 'Post-1994 democratic era (1996 Constitution)', ARRAY['1996 Constitutional recognition of 11 languages', 'Post-apartheid Truth and Reconciliation civic culture', 'Bantu greeting traditions of mutual recognition'], 'Learn at least one greeting in the home language of those you''ll meet — ''Sawubona'' (Zulu), ''Molo'' (Xhosa), ''Goeie dag'' (Afrikaans). The gesture is read as serious respect.'),
('ZA', 'dining', 'The Braai as Social Institution', 'The braai (Afrikaans for ''barbecue'') is the central South African social ritual, transcending racial, linguistic, and class lines as one of the country''s most genuinely shared institutions. Its roots blend Voortrekker open-fire cooking, Cape Malay marinades, and African open-fire traditions across the subcontinent. National Heritage Day (24 September) is widely celebrated as ''National Braai Day'', a rare unifying cultural practice in a famously plural society. Hosting a braai is a meaningful gesture of inclusion.', '19th-century Voortrekker through modern era', ARRAY['Voortrekker open-fire cooking', 'Cape Malay marinade tradition', 'African open-fire culinary heritage'], 'Accept any invitation to a braai — it is the central South African social ritual and the host''s gesture of inclusion. Bring meat, drink, or salad; offer to help at the fire.'),
('ZA', 'business', 'Ubuntu — I Am Because We Are', 'Ubuntu — the southern African philosophy that ''umuntu ngumuntu ngabantu'' (''a person is a person through other persons'') — frames identity as fundamentally communal and ethical responsibility as mutual. The concept was central to the post-apartheid Truth and Reconciliation Commission (1995–2002) under Archbishop Desmond Tutu, who explicitly grounded restorative justice in Ubuntu rather than purely retributive justice. In modern South African business, Ubuntu translates into expectation of community-aware, relational decision-making.', 'Pre-colonial Bantu philosophy; post-1994 civic centrality', ARRAY['Bantu philosophical tradition', 'Truth and Reconciliation Commission framing', 'Archbishop Desmond Tutu''s ethical leadership'], 'Frame decisions in terms of impact on the wider team and community, not just narrow stakeholder interest. Ubuntu-aware language signals serious engagement.'),
('ZA', 'greetings', 'The Three-Stage Handshake', 'The ''African handshake'' or ''thumb handshake'' — three stages: standard grip, then thumb grip, then return to standard — emerged in 20th-century township and pan-African solidarity culture and spread widely after 1994 across South African public life. It is now a common informal greeting between friends, colleagues, and across racial lines, distinct from the more formal Western handshake used for first introductions and across hierarchies.', '20th-century township culture; post-1994 mainstream', ARRAY['Pan-African solidarity greetings', 'Township informal culture', 'Post-1994 cross-racial informal contact'], 'Among friends and informal colleagues, expect the three-stage ''thumb handshake'' — standard grip, thumb grip, return. Western handshake remains default for formal first contact.'),
('ZA', 'gift-giving', 'Avoid the Left Hand', 'Across South Africa''s African and Indian communities — and increasingly observed as cross-cultural courtesy — gifts, money, and food should be passed and received with the right hand or with both hands. The convention has parallel roots in African traditional codes of respect (in which the left hand carries connotations of impurity in many Bantu cultures) and in the Indian Hindu and Muslim communities'' similar conventions. Using the left hand is read as rude or careless.', 'Layered: Bantu, Hindu, Islamic traditions', ARRAY['Bantu traditional respect codes', 'Indian-South African Hindu and Muslim conventions', 'Post-1994 cross-cultural courtesy practice'], 'Pass and receive gifts, money, and food with the right hand or both hands. Using the left hand reads as rude across most South African communities.')
ON CONFLICT (region_code, tradition) DO NOTHING;

