import { pgTable, serial, text, integer, jsonb, timestamp, index, uniqueIndex } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export interface LearningTrackOption {
  text: string;
  answer_tier: 1 | 2 | 3;
  motivation: string;
}

export const learningTrackQuestionsTable = pgTable(
  "learning_track_questions",
  {
    id:                 serial("id").primaryKey(),
    register:           text("register").notNull(),
    research_pillar:    text("research_pillar"),
    phase:              integer("phase").notNull(),
    level:              integer("level").notNull(),
    region_code:        text("region_code").notNull(),
    demographic:        text("demographic").notNull(),
    question_text:      text("question_text").notNull(),
    historical_context: text("historical_context"),
    options:            jsonb("options").$type<LearningTrackOption[]>().notNull().default([]),
    lang:               text("lang").notNull().default("en"),
    /**
     * Optional `situational_interests` codes that this question is most
     * relevant to (e.g. ["business", "gastronomy"]). The selection cascade
     * uses these to re-rank within the matching pool.
     */
    interest_tags:      jsonb("interest_tags").$type<string[]>().notNull().default([]),
    /**
     * Master Framework v1.1 — §11.6
     * Replaces the single `register` field with an array so a question can
     * belong to multiple registers. Used as a score-boost signal by the
     * selection engine (never as a hard WHERE filter).
     */
    register_relevance:      jsonb("register_relevance").$type<string[]>().notNull().default([]),
    /**
     * Archetypes for which this question is most relevant.
     * Used as a re-rank boost, not as a filter.
     * Example: ["host_entertainer", "civic_citizen"]
     */
    applicable_archetypes:   jsonb("applicable_archetypes").$type<string[]>().notNull().default([]),
    /**
     * Social-circle tags from interest_catalog taxonomy = 'social_circles'.
     * Boosts question ranking when the user's social_circles overlap.
     */
    social_circle_tags:      jsonb("social_circle_tags").$type<string[]>().notNull().default([]),
    /**
     * Cultural-interest tags from interest_catalog taxonomy = 'cultural_interests'.
     */
    cultural_interest_tags:  jsonb("cultural_interest_tags").$type<string[]>().notNull().default([]),
    /**
     * Cultural tag IDs from the canonical tag registry (cultural_tags table).
     * Array of tag_id strings, e.g. ["pda-couples-public", "alcohol-consumption-social-norm"].
     * Used by the learning engine for:
     *   - Laag A (country filter): excluded tags → hard remove; recommended → +6; not_recommended → −5
     *   - Laag B (profile boost): overlap with user interest slugs → +8 per match (max +24)
     * Populated by the auto-tagger script or manually in the YAML source file.
     * Default [] = not yet tagged (auto-tagger processes these).
     */
    cultural_tags:           jsonb("cultural_tags").$type<string[]>().notNull().default([]),
    /**
     * Primary Refinement Compass dimension this question trains.
     * One of: attentiveness | composure | discernment | diplomacy | presence
     * REQUIRED on every question (import pipeline enforces non-null).
     */
    primary_dimension:       text("primary_dimension"),
    /**
     * Secondary Compass dimension (optional, lower weight in scoring).
     */
    secondary_dimension:     text("secondary_dimension"),
    created_at:         timestamp("created_at").defaultNow(),
    /**
     * Computed hash for idempotent imports.
     * Generated by the DB: md5(region_code | register | research_pillar | phase | level | demographic | lang | question_text)
     * Seeds use onConflictDoNothing() against this unique index to skip duplicates.
     */
    question_hash:      text("question_hash").generatedAlwaysAs(
      sql`md5(region_code || '|' || register || '|' || COALESCE(research_pillar, '') || '|' || phase::text || '|' || level::text || '|' || demographic || '|' || lang || '|' || question_text)`
    ),
  },
  (table) => [
    index("ltq_lookup_idx").on(
      table.region_code,
      table.register,
      table.phase,
      table.research_pillar,
      table.demographic,
      table.level,
    ),
    uniqueIndex("ltq_hash_idx").on(table.question_hash),
  ],
);

export const insertLearningTrackQuestionSchema = createInsertSchema(learningTrackQuestionsTable, {
  // @ts-expect-error — drizzle-zod refinement type mismatch on question_hash; pre-existing
  question_hash: z.string().optional(),
});
export type InsertLearningTrackQuestion = z.infer<typeof insertLearningTrackQuestionSchema>;
export type LearningTrackQuestion = typeof learningTrackQuestionsTable.$inferSelect;
